#!/usr/bin/env python3
"""Generate `lean/RustLeanTests/LeanTests.lean` from `#[rust_lean_test]`
functions found anywhere under `source/src/`.

For each `#[rust_lean_test] pub fn <name>() -> bool` we emit
`#guard <fully-qualified-name> == .ok true`, where the fully qualified
name is read out of `lean/RustLeanTests/Funs.lean` rather than guessed
from the source path: Aeneas's builtin name map rewrites some module
components (notably `core` → `core_models`, `alloc` → `alloc_models`),
so the Lean def's location is not always derivable from the Rust file
path. Reading the extracted def list directly keeps the gen script
agnostic to that mapping.

The Lean build then fails for any test whose Aeneas translation does
not evaluate to `Result.ok true`.

Invoked from the Makefile after `make extract`. Idempotent.
"""

import pathlib
import re
import sys

HERE = pathlib.Path(__file__).resolve().parent
SRC_ROOT = HERE / "source" / "src"
FUNS = HERE / "lean" / "RustLeanTests" / "Funs.lean"
OUT = HERE / "lean" / "RustLeanTests" / "LeanTests.lean"

# Crate namespace that Aeneas wraps every def in (must match `name` in
# `source/Cargo.toml`).
CRATE_NAMESPACE = "rust_lean_tests"

# Marker attribute + `pub fn NAME() -> bool`. Body is ignored.
ATTR_FN_RE = re.compile(
    r"#\[\s*rust_lean_test\s*\]"
    r"(?:\s*#\[[^\]]*\])*"
    r"\s*pub\s+fn\s+(?P<name>[A-Za-z_][A-Za-z0-9_]*)\s*\(\s*\)"
    r"\s*->\s*bool",
    re.MULTILINE,
)

# Strip Rust comments. We don't care about precision (no string-literal
# awareness, etc.) — we just need commented-out test attributes to stop
# matching ATTR_FN_RE so contributors can disable a test with `/* ... */`
# or `//` lines and have gen-lean-tests respect it.
BLOCK_COMMENT_RE = re.compile(r"/\*.*?\*/", re.DOTALL)
LINE_COMMENT_RE = re.compile(r"//[^\n]*")


def strip_comments(src: str) -> str:
    src = BLOCK_COMMENT_RE.sub("", src)
    src = LINE_COMMENT_RE.sub("", src)
    return src

# Matches `def <dotted.path>.<name> ...` in the extracted Funs.lean.
# Captures the dotted path prefix (without the trailing name).
DEF_RE_TEMPLATE = r"^def\s+(?P<path>(?:[A-Za-z_][A-Za-z0-9_]*\.)*){name}\s"


def collect_source_tests() -> list[str]:
    """Return ordered list of `#[rust_lean_test]` function names found
    in the source tree."""
    names: list[str] = []
    seen: set[str] = set()
    for rs in sorted(SRC_ROOT.rglob("*.rs")):
        for m in ATTR_FN_RE.finditer(strip_comments(rs.read_text())):
            n = m.group("name")
            if n in seen:
                sys.exit(f"gen_lean_tests.py: duplicate test name: {n} (in {rs})")
            seen.add(n)
            names.append(n)
    return names


def qualify(name: str, funs_text: str) -> str:
    """Find `def <path>.<name>` in Funs.lean and return the fully
    qualified Lean name `<crate>.<path>.<name>`."""
    m = re.search(DEF_RE_TEMPLATE.format(name=re.escape(name)), funs_text, re.MULTILINE)
    if m is None:
        sys.exit(
            f"gen_lean_tests.py: `{name}` is annotated `#[rust_lean_test]` in the "
            f"Rust source but no matching `def` was found in {FUNS.name}. "
            f"Either Aeneas didn't extract it, or its body relies on something "
            f"the extraction pipeline silently dropped."
        )
    return f"{CRATE_NAMESPACE}.{m.group('path')}{name}"


def render(qualified: list[str]) -> str:
    lines = [
        "-- AUTO-GENERATED by rust_lean_equiv_test/gen_lean_tests.py.",
        "-- DO NOT EDIT. One `#guard` per `#[rust_lean_test]` function in",
        "-- `source/src/**/*.rs`. Each guard fails the Lean build if",
        "-- Aeneas's translation does not evaluate to `Result.ok true`.",
        "import RustLeanTests.Funs",
        "",
        # Default cap is 100 errors per file; with hundreds of guards a",
        # single broken extraction would otherwise hide all the others.",
        "set_option maxErrors 10000",
        "",
    ]
    lines.extend(f"#guard {fq} == .ok true" for fq in qualified)
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    if not SRC_ROOT.exists():
        sys.exit(f"gen_lean_tests.py: source dir not found: {SRC_ROOT}")
    if not FUNS.exists():
        sys.exit(
            f"gen_lean_tests.py: extracted {FUNS} not found. "
            f"Run `make extract` first (the Makefile sequences this)."
        )
    funs_text = FUNS.read_text()
    names = collect_source_tests()
    qualified = [qualify(n, funs_text) for n in names]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(render(qualified))
    print(f"gen_lean_tests.py: wrote {OUT.relative_to(HERE)} ({len(qualified)} tests)")


if __name__ == "__main__":
    main()
