-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [core_models]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes.
import Aeneas.Primitives
import Aeneas.Types
import Aeneas.PureFuns
open core core.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000
-- open core_models removed

/-- [core::cmp::impls::{core::cmp::PartialOrd<&0 (B)> for &1 (A)}::lt]:
    Source: '/rustc/library/core/src/cmp.rs', lines 2133:8-2133:40
    Name pattern: [core::cmp::impls::{core::cmp::PartialOrd<&'1 @A, &'0 @B>}::lt]
    Visibility: public -/
@[rust_fun "core::cmp::impls::{core::cmp::PartialOrd<&'1 @A, &'0 @B>}::lt"]
axiom Shared1A.Insts.CoreCmpPartialOrdShared0B.lt
  {A : Type} {B : Type} (PartialOrdInst : core.cmp.PartialOrd A B) :
  A → B → Result Bool

/-- [core::cmp::impls::{core::cmp::PartialOrd<&0 (B)> for &1 (A)}::gt]:
    Source: '/rustc/library/core/src/cmp.rs', lines 2141:8-2141:40
    Name pattern: [core::cmp::impls::{core::cmp::PartialOrd<&'1 @A, &'0 @B>}::gt]
    Visibility: public -/
@[rust_fun "core::cmp::impls::{core::cmp::PartialOrd<&'1 @A, &'0 @B>}::gt"]
axiom Shared1A.Insts.CoreCmpPartialOrdShared0B.gt
  {A : Type} {B : Type} (PartialOrdInst : core.cmp.PartialOrd A B) :
  A → B → Result Bool

/-- [core::slice::cmp::{core::cmp::PartialEq<[U]> for [T]}::eq]:
    Source: '/rustc/library/core/src/slice/cmp.rs', lines 18:4-18:37
    Name pattern: [core::slice::cmp::{core::cmp::PartialEq<[@T], [@U]>}::eq]
    Visibility: public -/
@[rust_fun "core::slice::cmp::{core::cmp::PartialEq<[@T], [@U]>}::eq"]
axiom Slice.Insts.CoreCmpPartialEqSlice.eq
  {T : Type} {U : Type} (cmpPartialEqInst : core.cmp.PartialEq T U) :
  Slice T → Slice U → Result Bool

/-- [hax_lib::assume]:
    Source: '/home/alex/Projects/hax-evit/aeneas-mvcgen/hax-lib/src/implementation.rs', lines 94:0-94:29
    Name pattern: [hax_lib::assume]
    Visibility: public -/
@[rust_fun "hax_lib::assume"]
def hax_lib.assume : hax_lib.prop.Prop → Result Unit := fun _ => ok ()

/-- [hax_lib::int::{core::cmp::PartialOrd<hax_lib::int::Int> for hax_lib::int::Int}::le]:
    Source: '/home/alex/Projects/hax-evit/aeneas-mvcgen/hax-lib/src/int/mod.rs', lines 16:42-16:52
    Name pattern: [hax_lib::int::{core::cmp::PartialOrd<hax_lib::int::Int, hax_lib::int::Int>}::le]
    Visibility: public -/
@[rust_fun
  "hax_lib::int::{core::cmp::PartialOrd<hax_lib::int::Int, hax_lib::int::Int>}::le"]
def hax_lib.int.Int.Insts.CoreCmpPartialOrdInt.le
  : _root_.Int → _root_.Int → Result Bool :=
  fun a b => ok (decide (a ≤ b))

/-- [hax_lib::int::{core::ops::arith::Add<hax_lib::int::Int, hax_lib::int::Int> for hax_lib::int::Int}::add]:
    Source: '/home/alex/Projects/hax-evit/aeneas-mvcgen/hax-lib/src/int/mod.rs', lines 37:4-37:45
    Name pattern: [hax_lib::int::{core::ops::arith::Add<hax_lib::int::Int, hax_lib::int::Int, hax_lib::int::Int>}::add]
    Visibility: public -/
@[rust_fun
  "hax_lib::int::{core::ops::arith::Add<hax_lib::int::Int, hax_lib::int::Int, hax_lib::int::Int>}::add"]
def hax_lib.int.Int.Insts.CoreOpsArithAddIntInt.add
  : _root_.Int → _root_.Int → Result hax_lib.int.Int :=
  fun a b => ok (a + b)

/-- [hax_lib::int::{core::ops::arith::Sub<hax_lib::int::Int, hax_lib::int::Int> for hax_lib::int::Int}::sub]:
    Source: '/home/alex/Projects/hax-evit/aeneas-mvcgen/hax-lib/src/int/mod.rs', lines 53:4-53:45
    Name pattern: [hax_lib::int::{core::ops::arith::Sub<hax_lib::int::Int, hax_lib::int::Int, hax_lib::int::Int>}::sub]
    Visibility: public -/
@[rust_fun
  "hax_lib::int::{core::ops::arith::Sub<hax_lib::int::Int, hax_lib::int::Int, hax_lib::int::Int>}::sub"]
def hax_lib.int.Int.Insts.CoreOpsArithSubIntInt.sub
  : _root_.Int → _root_.Int → Result hax_lib.int.Int :=
  fun a b => ok (a - b)

/-- [hax_lib::int::{core::ops::arith::Mul<hax_lib::int::Int, hax_lib::int::Int> for hax_lib::int::Int}::mul]:
    Source: '/home/alex/Projects/hax-evit/aeneas-mvcgen/hax-lib/src/int/mod.rs', lines 61:4-61:45
    Name pattern: [hax_lib::int::{core::ops::arith::Mul<hax_lib::int::Int, hax_lib::int::Int, hax_lib::int::Int>}::mul]
    Visibility: public -/
@[rust_fun
  "hax_lib::int::{core::ops::arith::Mul<hax_lib::int::Int, hax_lib::int::Int, hax_lib::int::Int>}::mul"]
def hax_lib.int.Int.Insts.CoreOpsArithMulIntInt.mul
  : _root_.Int → _root_.Int → Result hax_lib.int.Int :=
  fun a b => ok (a * b)

/-- [hax_lib::int::{hax_lib::int::ToInt for u8}::to_int]:
    Source: '/home/alex/Projects/hax-evit/aeneas-mvcgen/hax-lib/src/int/mod.rs', lines 124:12-124:34
    Name pattern: [hax_lib::int::{hax_lib::int::ToInt<u8>}::to_int]
    Visibility: public -/
@[rust_fun "hax_lib::int::{hax_lib::int::ToInt<u8>}::to_int"]
def U8.Insts.Hax_libIntToInt.to_int : Std.U8 → Result hax_lib.int.Int :=
  fun x => ok (Int.ofNat x.toNat)

/-- [hax_lib::int::{hax_lib::int::ToInt for u16}::to_int]:
    Source: '/home/alex/Projects/hax-evit/aeneas-mvcgen/hax-lib/src/int/mod.rs', lines 124:12-124:34
    Name pattern: [hax_lib::int::{hax_lib::int::ToInt<u16>}::to_int]
    Visibility: public -/
@[rust_fun "hax_lib::int::{hax_lib::int::ToInt<u16>}::to_int"]
def U16.Insts.Hax_libIntToInt.to_int : Std.U16 → Result hax_lib.int.Int :=
  fun x => ok (Int.ofNat x.toNat)

/-- [hax_lib::int::{hax_lib::int::ToInt for u32}::to_int]:
    Source: '/home/alex/Projects/hax-evit/aeneas-mvcgen/hax-lib/src/int/mod.rs', lines 124:12-124:34
    Name pattern: [hax_lib::int::{hax_lib::int::ToInt<u32>}::to_int]
    Visibility: public -/
@[rust_fun "hax_lib::int::{hax_lib::int::ToInt<u32>}::to_int"]
def U32.Insts.Hax_libIntToInt.to_int : Std.U32 → Result hax_lib.int.Int :=
  fun x => ok (Int.ofNat x.toNat)

/-- [hax_lib::int::{hax_lib::int::ToInt for u64}::to_int]:
    Source: '/home/alex/Projects/hax-evit/aeneas-mvcgen/hax-lib/src/int/mod.rs', lines 124:12-124:34
    Name pattern: [hax_lib::int::{hax_lib::int::ToInt<u64>}::to_int]
    Visibility: public -/
@[rust_fun "hax_lib::int::{hax_lib::int::ToInt<u64>}::to_int"]
def U64.Insts.Hax_libIntToInt.to_int : Std.U64 → Result hax_lib.int.Int :=
  fun x => ok (Int.ofNat x.toNat)

/-- [hax_lib::int::{hax_lib::int::ToInt for u128}::to_int]:
    Source: '/home/alex/Projects/hax-evit/aeneas-mvcgen/hax-lib/src/int/mod.rs', lines 124:12-124:34
    Name pattern: [hax_lib::int::{hax_lib::int::ToInt<u128>}::to_int]
    Visibility: public -/
@[rust_fun "hax_lib::int::{hax_lib::int::ToInt<u128>}::to_int"]
def U128.Insts.Hax_libIntToInt.to_int : Std.U128 → Result hax_lib.int.Int :=
  fun x => ok (Int.ofNat x.toNat)

/-- [hax_lib::int::{hax_lib::int::ToInt for usize}::to_int]:
    Source: '/home/alex/Projects/hax-evit/aeneas-mvcgen/hax-lib/src/int/mod.rs', lines 124:12-124:34
    Name pattern: [hax_lib::int::{hax_lib::int::ToInt<usize>}::to_int]
    Visibility: public -/
@[rust_fun "hax_lib::int::{hax_lib::int::ToInt<usize>}::to_int"]
def Usize.Insts.Hax_libIntToInt.to_int : Std.Usize → Result hax_lib.int.Int :=
  fun x => ok (Int.ofNat x.toNat)

/-- [hax_lib::int::{hax_lib::int::ToInt for i8}::to_int]:
    Source: '/home/alex/Projects/hax-evit/aeneas-mvcgen/hax-lib/src/int/mod.rs', lines 124:12-124:34
    Name pattern: [hax_lib::int::{hax_lib::int::ToInt<i8>}::to_int]
    Visibility: public -/
@[rust_fun "hax_lib::int::{hax_lib::int::ToInt<i8>}::to_int"]
def I8.Insts.Hax_libIntToInt.to_int : Std.I8 → Result hax_lib.int.Int :=
  fun x => ok x.toInt

/-- [hax_lib::int::{hax_lib::int::ToInt for i16}::to_int]:
    Source: '/home/alex/Projects/hax-evit/aeneas-mvcgen/hax-lib/src/int/mod.rs', lines 124:12-124:34
    Name pattern: [hax_lib::int::{hax_lib::int::ToInt<i16>}::to_int]
    Visibility: public -/
@[rust_fun "hax_lib::int::{hax_lib::int::ToInt<i16>}::to_int"]
def I16.Insts.Hax_libIntToInt.to_int : Std.I16 → Result hax_lib.int.Int :=
  fun x => ok x.toInt

/-- [hax_lib::int::{hax_lib::int::ToInt for i32}::to_int]:
    Source: '/home/alex/Projects/hax-evit/aeneas-mvcgen/hax-lib/src/int/mod.rs', lines 124:12-124:34
    Name pattern: [hax_lib::int::{hax_lib::int::ToInt<i32>}::to_int]
    Visibility: public -/
@[rust_fun "hax_lib::int::{hax_lib::int::ToInt<i32>}::to_int"]
def I32.Insts.Hax_libIntToInt.to_int : Std.I32 → Result hax_lib.int.Int :=
  fun x => ok x.toInt

/-- [hax_lib::int::{hax_lib::int::ToInt for i64}::to_int]:
    Source: '/home/alex/Projects/hax-evit/aeneas-mvcgen/hax-lib/src/int/mod.rs', lines 124:12-124:34
    Name pattern: [hax_lib::int::{hax_lib::int::ToInt<i64>}::to_int]
    Visibility: public -/
@[rust_fun "hax_lib::int::{hax_lib::int::ToInt<i64>}::to_int"]
def I64.Insts.Hax_libIntToInt.to_int : Std.I64 → Result hax_lib.int.Int :=
  fun x => ok x.toInt

/-- [hax_lib::int::{hax_lib::int::ToInt for i128}::to_int]:
    Source: '/home/alex/Projects/hax-evit/aeneas-mvcgen/hax-lib/src/int/mod.rs', lines 124:12-124:34
    Name pattern: [hax_lib::int::{hax_lib::int::ToInt<i128>}::to_int]
    Visibility: public -/
@[rust_fun "hax_lib::int::{hax_lib::int::ToInt<i128>}::to_int"]
def I128.Insts.Hax_libIntToInt.to_int : Std.I128 → Result hax_lib.int.Int :=
  fun x => ok x.toInt

/-- [hax_lib::int::{hax_lib::int::ToInt for isize}::to_int]:
    Source: '/home/alex/Projects/hax-evit/aeneas-mvcgen/hax-lib/src/int/mod.rs', lines 124:12-124:34
    Name pattern: [hax_lib::int::{hax_lib::int::ToInt<isize>}::to_int]
    Visibility: public -/
@[rust_fun "hax_lib::int::{hax_lib::int::ToInt<isize>}::to_int"]
def Isize.Insts.Hax_libIntToInt.to_int : Std.Isize → Result hax_lib.int.Int :=
  fun x => ok x.toInt

/-- [hax_lib::prop::{core::convert::From<bool> for hax_lib::prop::Prop}::from]:
    Source: '/home/alex/Projects/hax-evit/aeneas-mvcgen/hax-lib/src/prop.rs', lines 95:4-95:32
    Name pattern: [hax_lib::prop::{core::convert::From<hax_lib::prop::Prop, bool>}::from]
    Visibility: public -/
@[rust_fun
  "hax_lib::prop::{core::convert::From<hax_lib::prop::Prop, bool>}::from"]
def hax_lib.prop.Prop.Insts.CoreConvertFromBool.from
  : Bool → Result hax_lib.prop.Prop :=
  fun x => pure (x = true)

/-- [rust_primitives::slice::slice_length]:
    Source: 'rust_primitives/src/lib.rs', lines 4:4-4:44
    Name pattern: [rust_primitives::slice::slice_length]
    Visibility: public -/
@[rust_fun "rust_primitives::slice::slice_length"]
def rust_primitives.slice.slice_length
  {T : Type} : Slice T → Result Std.Usize :=
  fun s => ok s.len

/-- [rust_primitives::slice::slice_split_at]:
    Source: 'rust_primitives/src/lib.rs', lines 8:4-8:65
    Name pattern: [rust_primitives::slice::slice_split_at]
    Visibility: public -/
@[rust_fun "rust_primitives::slice::slice_split_at"]
def rust_primitives.slice.slice_split_at
  {T : Type} : Slice T → Std.Usize → Result ((Slice T) × (Slice T)) :=
  fun s i =>
    if i.toNat ≤ s.length then
      ok (⟨s.val.take i.toNat, by sorry⟩, ⟨s.val.drop i.toNat, by sorry⟩)
    else
      fail Error.arrayOutOfBounds

/-- [rust_primitives::slice::slice_contains]:
    Source: 'rust_primitives/src/lib.rs', lines 11:4-11:63
    Name pattern: [rust_primitives::slice::slice_contains]
    Visibility: public -/
@[rust_fun "rust_primitives::slice::slice_contains"]
def rust_primitives.slice.slice_contains
  {T : Type} (corecmpPartialEqInst : core.cmp.PartialEq T T) :
  Slice T → T → Result Bool :=
  fun s x =>
    let rec go : List T → Result Bool
      | [] => ok false
      | y :: ys => do
          let b ← corecmpPartialEqInst.eq y x
          if b then ok true else go ys
    go s.val

/-- [rust_primitives::slice::slice_index]:
    Source: 'rust_primitives/src/lib.rs', lines 15:4-15:50
    Name pattern: [rust_primitives::slice::slice_index]
    Visibility: public -/
@[rust_fun "rust_primitives::slice::slice_index"]
def rust_primitives.slice.slice_index
  {T : Type} : Slice T → Std.Usize → Result T :=
  fun s i =>
    match s.val[i.toNat]? with
    | none   => fail Error.arrayOutOfBounds
    | some x => ok x

/-- [rust_primitives::slice::slice_slice]:
    Source: 'rust_primitives/src/lib.rs', lines 18:4-18:62
    Name pattern: [rust_primitives::slice::slice_slice]
    Visibility: public -/
@[rust_fun "rust_primitives::slice::slice_slice"]
def rust_primitives.slice.slice_slice
  {T : Type} : Slice T → Std.Usize → Std.Usize → Result (Slice T) :=
  fun s start stop =>
    if start.toNat ≤ stop.toNat && stop.toNat ≤ s.length then
      ok ⟨(s.val.take stop.toNat).drop start.toNat, by sorry⟩
    else fail Error.arrayOutOfBounds

/-- [rust_primitives::slice::slice_clone_from_slice]:
    Source: 'rust_primitives/src/lib.rs', lines 21:4-21:67
    Name pattern: [rust_primitives::slice::slice_clone_from_slice]
    Visibility: public -/
@[rust_fun "rust_primitives::slice::slice_clone_from_slice"]
def rust_primitives.slice.slice_clone_from_slice
  {T : Type} (corecloneCloneInst : core.clone.Clone T) :
  Slice T → Slice T → Result (Slice T) :=
  fun dst src =>
    if dst.length ≠ src.length then fail Error.panic
    else do
      let cloned ← src.val.mapM corecloneCloneInst.clone
      ok ⟨cloned, by sorry⟩

/-- [rust_primitives::slice::array_from_fn]:
    Source: 'rust_primitives/src/lib.rs', lines 28:4-28:78
    Name pattern: [rust_primitives::slice::array_from_fn]
    Visibility: public -/
@[rust_fun "rust_primitives::slice::array_from_fn"]
def rust_primitives.slice.array_from_fn
  {T : Type} {F : Type} (N : Std.Usize) (coreopsfunctionFnMutFTupleUsizeTInst :
  core.ops.function.FnMut F Std.Usize T) :
  F → Result (Array T N) :=
  fun f => do
    -- Threaded `FnMut`: each iteration takes the current `f`, calls
    -- `call_mut` to get back `(value, new_f)`, accumulates the value, and
    -- forwards the new closure to the next step.
    let rec build : Nat → F → Result (List T)
      | 0,        _  => ok []
      | (n+1), fcur => do
        let i := USize64.ofNat (N.toNat - n - 1)
        let (v, fnext) ← coreopsfunctionFnMutFTupleUsizeTInst.call_mut fcur i
        let rest ← build n fnext
        ok (v :: rest)
    let l ← build N.toNat f
    ok ⟨l, by sorry⟩

/-- [rust_primitives::slice::array_map]:
    Source: 'rust_primitives/src/lib.rs', lines 31:4-31:84
    Name pattern: [rust_primitives::slice::array_map]
    Visibility: public -/
@[rust_fun "rust_primitives::slice::array_map"]
def rust_primitives.slice.array_map
  {T : Type} {U : Type} {F : Type} {N : Std.Usize}
  (coreopsfunctionFnFTupleTUInst : core.ops.function.Fn F T U) :
  Array T N → F → Result (Array U N) :=
  fun a f => do
    let l ← a.val.mapM (fun x => coreopsfunctionFnFTupleTUInst.call f x)
    ok ⟨l, by sorry⟩

/-- [rust_primitives::slice::array_as_slice]:
    Source: 'rust_primitives/src/lib.rs', lines 34:4-34:64
    Name pattern: [rust_primitives::slice::array_as_slice]
    Visibility: public -/
@[rust_fun "rust_primitives::slice::array_as_slice"]
def rust_primitives.slice.array_as_slice
  {T : Type} {N : Std.Usize} : Array T N → Result (Slice T) :=
  fun a => ok a.to_slice

/-- [rust_primitives::slice::array_slice]:
    Source: 'rust_primitives/src/lib.rs', lines 37:4-37:81
    Name pattern: [rust_primitives::slice::array_slice]
    Visibility: public -/
@[rust_fun "rust_primitives::slice::array_slice"]
def rust_primitives.slice.array_slice
  {T : Type} {N : Std.Usize} :
  Array T N → Std.Usize → Std.Usize → Result (Slice T) :=
  fun a start stop =>
    if start.toNat ≤ stop.toNat && stop.toNat ≤ a.length then
      ok ⟨(a.val.take stop.toNat).drop start.toNat, by sorry⟩
    else fail Error.arrayOutOfBounds

/-- [rust_primitives::slice::array_index]:
    Source: 'rust_primitives/src/lib.rs', lines 40:4-40:69
    Name pattern: [rust_primitives::slice::array_index]
    Visibility: public -/
@[rust_fun "rust_primitives::slice::array_index"]
def rust_primitives.slice.array_index
  {T : Type} {N : Std.Usize} : Array T N → Std.Usize → Result T :=
  Array.index_usize

/-- [rust_primitives::sequence::seq_from_slice]:
    Source: 'rust_primitives/src/lib.rs', lines 51:4-51:48
    Name pattern: [rust_primitives::sequence::seq_from_slice]
    Visibility: public -/
@[rust_fun "rust_primitives::sequence::seq_from_slice"]
def rust_primitives.sequence.seq_from_slice
  {T : Type} : Slice T → Result (rust_primitives.sequence.Seq T) :=
  fun s => ok s.val.toArray

/-- [rust_primitives::sequence::seq_from_array]:
    Source: 'rust_primitives/src/lib.rs', lines 57:4-57:65
    Name pattern: [rust_primitives::sequence::seq_from_array]
    Visibility: public -/
@[rust_fun "rust_primitives::sequence::seq_from_array"]
def rust_primitives.sequence.seq_from_array
  {T : Type} {N : Std.Usize} :
  Array T N → Result (rust_primitives.sequence.Seq T) :=
  fun a => ok a.val.toArray

/-- [rust_primitives::sequence::seq_len]:
    Source: 'rust_primitives/src/lib.rs', lines 81:4-81:42
    Name pattern: [rust_primitives::sequence::seq_len]
    Visibility: public -/
@[rust_fun "rust_primitives::sequence::seq_len"]
def rust_primitives.sequence.seq_len
  {T : Type} : rust_primitives.sequence.Seq T → Result Std.Usize :=
  fun seq => ok (USize64.ofNat seq.size)

/-- [rust_primitives::sequence::seq_remove]:
    Source: 'rust_primitives/src/lib.rs', lines 87:4-87:55
    Name pattern: [rust_primitives::sequence::seq_remove]
    Visibility: public -/
@[rust_fun "rust_primitives::sequence::seq_remove"]
def rust_primitives.sequence.seq_remove
  {T : Type} :
  rust_primitives.sequence.Seq T → Std.Usize → Result (T ×
    (rust_primitives.sequence.Seq T)) :=
  fun seq i =>
    let a : _root_.Array T := seq
    if h : i.toNat < a.size then
      ok (a[i.toNat]'h, a.eraseIdx (⟨i.toNat, h⟩ : Fin a.size))
    else fail Error.arrayOutOfBounds

/-- [rust_primitives::arithmetic::saturating_mul_u8]:
    Source: 'rust_primitives/src/lib.rs', lines 132:18-132:21
    Name pattern: [rust_primitives::arithmetic::saturating_mul_u8]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::saturating_mul_u8"]
axiom rust_primitives.arithmetic.saturating_mul_u8
  : Std.U8 → Std.U8 → Result Std.U8

/-- [rust_primitives::arithmetic::rem_euclid_u8]:
    Source: 'rust_primitives/src/lib.rs', lines 132:18-132:21
    Name pattern: [rust_primitives::arithmetic::rem_euclid_u8]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::rem_euclid_u8"]
axiom rust_primitives.arithmetic.rem_euclid_u8
  : Std.U8 → Std.U8 → Result Std.U8

/-- [rust_primitives::arithmetic::saturating_mul_u16]:
    Source: 'rust_primitives/src/lib.rs', lines 132:18-132:21
    Name pattern: [rust_primitives::arithmetic::saturating_mul_u16]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::saturating_mul_u16"]
axiom rust_primitives.arithmetic.saturating_mul_u16
  : Std.U16 → Std.U16 → Result Std.U16

/-- [rust_primitives::arithmetic::rem_euclid_u16]:
    Source: 'rust_primitives/src/lib.rs', lines 132:18-132:21
    Name pattern: [rust_primitives::arithmetic::rem_euclid_u16]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::rem_euclid_u16"]
axiom rust_primitives.arithmetic.rem_euclid_u16
  : Std.U16 → Std.U16 → Result Std.U16

/-- [rust_primitives::arithmetic::saturating_mul_u32]:
    Source: 'rust_primitives/src/lib.rs', lines 132:18-132:21
    Name pattern: [rust_primitives::arithmetic::saturating_mul_u32]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::saturating_mul_u32"]
axiom rust_primitives.arithmetic.saturating_mul_u32
  : Std.U32 → Std.U32 → Result Std.U32

/-- [rust_primitives::arithmetic::rem_euclid_u32]:
    Source: 'rust_primitives/src/lib.rs', lines 132:18-132:21
    Name pattern: [rust_primitives::arithmetic::rem_euclid_u32]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::rem_euclid_u32"]
axiom rust_primitives.arithmetic.rem_euclid_u32
  : Std.U32 → Std.U32 → Result Std.U32

/-- [rust_primitives::arithmetic::saturating_mul_u64]:
    Source: 'rust_primitives/src/lib.rs', lines 132:18-132:21
    Name pattern: [rust_primitives::arithmetic::saturating_mul_u64]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::saturating_mul_u64"]
axiom rust_primitives.arithmetic.saturating_mul_u64
  : Std.U64 → Std.U64 → Result Std.U64

/-- [rust_primitives::arithmetic::rem_euclid_u64]:
    Source: 'rust_primitives/src/lib.rs', lines 132:18-132:21
    Name pattern: [rust_primitives::arithmetic::rem_euclid_u64]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::rem_euclid_u64"]
axiom rust_primitives.arithmetic.rem_euclid_u64
  : Std.U64 → Std.U64 → Result Std.U64

/-- [rust_primitives::arithmetic::saturating_mul_u128]:
    Source: 'rust_primitives/src/lib.rs', lines 132:18-132:21
    Name pattern: [rust_primitives::arithmetic::saturating_mul_u128]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::saturating_mul_u128"]
axiom rust_primitives.arithmetic.saturating_mul_u128
  : Std.U128 → Std.U128 → Result Std.U128

/-- [rust_primitives::arithmetic::rem_euclid_u128]:
    Source: 'rust_primitives/src/lib.rs', lines 132:18-132:21
    Name pattern: [rust_primitives::arithmetic::rem_euclid_u128]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::rem_euclid_u128"]
axiom rust_primitives.arithmetic.rem_euclid_u128
  : Std.U128 → Std.U128 → Result Std.U128

/-- [rust_primitives::arithmetic::saturating_mul_usize]:
    Source: 'rust_primitives/src/lib.rs', lines 132:18-132:21
    Name pattern: [rust_primitives::arithmetic::saturating_mul_usize]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::saturating_mul_usize"]
axiom rust_primitives.arithmetic.saturating_mul_usize
  : Std.Usize → Std.Usize → Result Std.Usize

/-- [rust_primitives::arithmetic::rem_euclid_usize]:
    Source: 'rust_primitives/src/lib.rs', lines 132:18-132:21
    Name pattern: [rust_primitives::arithmetic::rem_euclid_usize]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::rem_euclid_usize"]
axiom rust_primitives.arithmetic.rem_euclid_usize
  : Std.Usize → Std.Usize → Result Std.Usize

/-- [rust_primitives::arithmetic::saturating_mul_i8]:
    Source: 'rust_primitives/src/lib.rs', lines 132:18-132:21
    Name pattern: [rust_primitives::arithmetic::saturating_mul_i8]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::saturating_mul_i8"]
axiom rust_primitives.arithmetic.saturating_mul_i8
  : Std.I8 → Std.I8 → Result Std.I8

/-- [rust_primitives::arithmetic::rem_euclid_i8]:
    Source: 'rust_primitives/src/lib.rs', lines 132:18-132:21
    Name pattern: [rust_primitives::arithmetic::rem_euclid_i8]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::rem_euclid_i8"]
axiom rust_primitives.arithmetic.rem_euclid_i8
  : Std.I8 → Std.I8 → Result Std.I8

/-- [rust_primitives::arithmetic::saturating_mul_i16]:
    Source: 'rust_primitives/src/lib.rs', lines 132:18-132:21
    Name pattern: [rust_primitives::arithmetic::saturating_mul_i16]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::saturating_mul_i16"]
axiom rust_primitives.arithmetic.saturating_mul_i16
  : Std.I16 → Std.I16 → Result Std.I16

/-- [rust_primitives::arithmetic::rem_euclid_i16]:
    Source: 'rust_primitives/src/lib.rs', lines 132:18-132:21
    Name pattern: [rust_primitives::arithmetic::rem_euclid_i16]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::rem_euclid_i16"]
axiom rust_primitives.arithmetic.rem_euclid_i16
  : Std.I16 → Std.I16 → Result Std.I16

/-- [rust_primitives::arithmetic::saturating_mul_i32]:
    Source: 'rust_primitives/src/lib.rs', lines 132:18-132:21
    Name pattern: [rust_primitives::arithmetic::saturating_mul_i32]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::saturating_mul_i32"]
axiom rust_primitives.arithmetic.saturating_mul_i32
  : Std.I32 → Std.I32 → Result Std.I32

/-- [rust_primitives::arithmetic::rem_euclid_i32]:
    Source: 'rust_primitives/src/lib.rs', lines 132:18-132:21
    Name pattern: [rust_primitives::arithmetic::rem_euclid_i32]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::rem_euclid_i32"]
axiom rust_primitives.arithmetic.rem_euclid_i32
  : Std.I32 → Std.I32 → Result Std.I32

/-- [rust_primitives::arithmetic::saturating_mul_i64]:
    Source: 'rust_primitives/src/lib.rs', lines 132:18-132:21
    Name pattern: [rust_primitives::arithmetic::saturating_mul_i64]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::saturating_mul_i64"]
axiom rust_primitives.arithmetic.saturating_mul_i64
  : Std.I64 → Std.I64 → Result Std.I64

/-- [rust_primitives::arithmetic::rem_euclid_i64]:
    Source: 'rust_primitives/src/lib.rs', lines 132:18-132:21
    Name pattern: [rust_primitives::arithmetic::rem_euclid_i64]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::rem_euclid_i64"]
axiom rust_primitives.arithmetic.rem_euclid_i64
  : Std.I64 → Std.I64 → Result Std.I64

/-- [rust_primitives::arithmetic::saturating_mul_i128]:
    Source: 'rust_primitives/src/lib.rs', lines 132:18-132:21
    Name pattern: [rust_primitives::arithmetic::saturating_mul_i128]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::saturating_mul_i128"]
axiom rust_primitives.arithmetic.saturating_mul_i128
  : Std.I128 → Std.I128 → Result Std.I128

/-- [rust_primitives::arithmetic::rem_euclid_i128]:
    Source: 'rust_primitives/src/lib.rs', lines 132:18-132:21
    Name pattern: [rust_primitives::arithmetic::rem_euclid_i128]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::rem_euclid_i128"]
axiom rust_primitives.arithmetic.rem_euclid_i128
  : Std.I128 → Std.I128 → Result Std.I128

/-- [rust_primitives::arithmetic::saturating_mul_isize]:
    Source: 'rust_primitives/src/lib.rs', lines 132:18-132:21
    Name pattern: [rust_primitives::arithmetic::saturating_mul_isize]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::saturating_mul_isize"]
axiom rust_primitives.arithmetic.saturating_mul_isize
  : Std.Isize → Std.Isize → Result Std.Isize

/-- [rust_primitives::arithmetic::rem_euclid_isize]:
    Source: 'rust_primitives/src/lib.rs', lines 132:18-132:21
    Name pattern: [rust_primitives::arithmetic::rem_euclid_isize]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::rem_euclid_isize"]
axiom rust_primitives.arithmetic.rem_euclid_isize
  : Std.Isize → Std.Isize → Result Std.Isize

/-- [rust_primitives::arithmetic::overflowing_sub_u8]:
    Source: 'rust_primitives/src/lib.rs', lines 135:18-135:68
    Name pattern: [rust_primitives::arithmetic::overflowing_sub_u8]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::overflowing_sub_u8"]
axiom rust_primitives.arithmetic.overflowing_sub_u8
  : Std.U8 → Std.U8 → Result (Std.U8 × Bool)

/-- [rust_primitives::arithmetic::overflowing_mul_u8]:
    Source: 'rust_primitives/src/lib.rs', lines 135:18-135:68
    Name pattern: [rust_primitives::arithmetic::overflowing_mul_u8]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::overflowing_mul_u8"]
axiom rust_primitives.arithmetic.overflowing_mul_u8
  : Std.U8 → Std.U8 → Result (Std.U8 × Bool)

/-- [rust_primitives::arithmetic::overflowing_sub_u16]:
    Source: 'rust_primitives/src/lib.rs', lines 135:18-135:68
    Name pattern: [rust_primitives::arithmetic::overflowing_sub_u16]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::overflowing_sub_u16"]
axiom rust_primitives.arithmetic.overflowing_sub_u16
  : Std.U16 → Std.U16 → Result (Std.U16 × Bool)

/-- [rust_primitives::arithmetic::overflowing_mul_u16]:
    Source: 'rust_primitives/src/lib.rs', lines 135:18-135:68
    Name pattern: [rust_primitives::arithmetic::overflowing_mul_u16]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::overflowing_mul_u16"]
axiom rust_primitives.arithmetic.overflowing_mul_u16
  : Std.U16 → Std.U16 → Result (Std.U16 × Bool)

/-- [rust_primitives::arithmetic::overflowing_sub_u32]:
    Source: 'rust_primitives/src/lib.rs', lines 135:18-135:68
    Name pattern: [rust_primitives::arithmetic::overflowing_sub_u32]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::overflowing_sub_u32"]
axiom rust_primitives.arithmetic.overflowing_sub_u32
  : Std.U32 → Std.U32 → Result (Std.U32 × Bool)

/-- [rust_primitives::arithmetic::overflowing_mul_u32]:
    Source: 'rust_primitives/src/lib.rs', lines 135:18-135:68
    Name pattern: [rust_primitives::arithmetic::overflowing_mul_u32]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::overflowing_mul_u32"]
axiom rust_primitives.arithmetic.overflowing_mul_u32
  : Std.U32 → Std.U32 → Result (Std.U32 × Bool)

/-- [rust_primitives::arithmetic::overflowing_sub_u64]:
    Source: 'rust_primitives/src/lib.rs', lines 135:18-135:68
    Name pattern: [rust_primitives::arithmetic::overflowing_sub_u64]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::overflowing_sub_u64"]
axiom rust_primitives.arithmetic.overflowing_sub_u64
  : Std.U64 → Std.U64 → Result (Std.U64 × Bool)

/-- [rust_primitives::arithmetic::overflowing_mul_u64]:
    Source: 'rust_primitives/src/lib.rs', lines 135:18-135:68
    Name pattern: [rust_primitives::arithmetic::overflowing_mul_u64]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::overflowing_mul_u64"]
axiom rust_primitives.arithmetic.overflowing_mul_u64
  : Std.U64 → Std.U64 → Result (Std.U64 × Bool)

/-- [rust_primitives::arithmetic::overflowing_sub_u128]:
    Source: 'rust_primitives/src/lib.rs', lines 135:18-135:68
    Name pattern: [rust_primitives::arithmetic::overflowing_sub_u128]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::overflowing_sub_u128"]
axiom rust_primitives.arithmetic.overflowing_sub_u128
  : Std.U128 → Std.U128 → Result (Std.U128 × Bool)

/-- [rust_primitives::arithmetic::overflowing_mul_u128]:
    Source: 'rust_primitives/src/lib.rs', lines 135:18-135:68
    Name pattern: [rust_primitives::arithmetic::overflowing_mul_u128]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::overflowing_mul_u128"]
axiom rust_primitives.arithmetic.overflowing_mul_u128
  : Std.U128 → Std.U128 → Result (Std.U128 × Bool)

/-- [rust_primitives::arithmetic::overflowing_sub_usize]:
    Source: 'rust_primitives/src/lib.rs', lines 135:18-135:68
    Name pattern: [rust_primitives::arithmetic::overflowing_sub_usize]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::overflowing_sub_usize"]
axiom rust_primitives.arithmetic.overflowing_sub_usize
  : Std.Usize → Std.Usize → Result (Std.Usize × Bool)

/-- [rust_primitives::arithmetic::overflowing_mul_usize]:
    Source: 'rust_primitives/src/lib.rs', lines 135:18-135:68
    Name pattern: [rust_primitives::arithmetic::overflowing_mul_usize]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::overflowing_mul_usize"]
axiom rust_primitives.arithmetic.overflowing_mul_usize
  : Std.Usize → Std.Usize → Result (Std.Usize × Bool)

/-- [rust_primitives::arithmetic::overflowing_sub_i8]:
    Source: 'rust_primitives/src/lib.rs', lines 135:18-135:68
    Name pattern: [rust_primitives::arithmetic::overflowing_sub_i8]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::overflowing_sub_i8"]
axiom rust_primitives.arithmetic.overflowing_sub_i8
  : Std.I8 → Std.I8 → Result (Std.I8 × Bool)

/-- [rust_primitives::arithmetic::overflowing_mul_i8]:
    Source: 'rust_primitives/src/lib.rs', lines 135:18-135:68
    Name pattern: [rust_primitives::arithmetic::overflowing_mul_i8]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::overflowing_mul_i8"]
axiom rust_primitives.arithmetic.overflowing_mul_i8
  : Std.I8 → Std.I8 → Result (Std.I8 × Bool)

/-- [rust_primitives::arithmetic::overflowing_sub_i16]:
    Source: 'rust_primitives/src/lib.rs', lines 135:18-135:68
    Name pattern: [rust_primitives::arithmetic::overflowing_sub_i16]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::overflowing_sub_i16"]
axiom rust_primitives.arithmetic.overflowing_sub_i16
  : Std.I16 → Std.I16 → Result (Std.I16 × Bool)

/-- [rust_primitives::arithmetic::overflowing_mul_i16]:
    Source: 'rust_primitives/src/lib.rs', lines 135:18-135:68
    Name pattern: [rust_primitives::arithmetic::overflowing_mul_i16]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::overflowing_mul_i16"]
axiom rust_primitives.arithmetic.overflowing_mul_i16
  : Std.I16 → Std.I16 → Result (Std.I16 × Bool)

/-- [rust_primitives::arithmetic::overflowing_sub_i32]:
    Source: 'rust_primitives/src/lib.rs', lines 135:18-135:68
    Name pattern: [rust_primitives::arithmetic::overflowing_sub_i32]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::overflowing_sub_i32"]
axiom rust_primitives.arithmetic.overflowing_sub_i32
  : Std.I32 → Std.I32 → Result (Std.I32 × Bool)

/-- [rust_primitives::arithmetic::overflowing_mul_i32]:
    Source: 'rust_primitives/src/lib.rs', lines 135:18-135:68
    Name pattern: [rust_primitives::arithmetic::overflowing_mul_i32]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::overflowing_mul_i32"]
axiom rust_primitives.arithmetic.overflowing_mul_i32
  : Std.I32 → Std.I32 → Result (Std.I32 × Bool)

/-- [rust_primitives::arithmetic::overflowing_sub_i64]:
    Source: 'rust_primitives/src/lib.rs', lines 135:18-135:68
    Name pattern: [rust_primitives::arithmetic::overflowing_sub_i64]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::overflowing_sub_i64"]
axiom rust_primitives.arithmetic.overflowing_sub_i64
  : Std.I64 → Std.I64 → Result (Std.I64 × Bool)

/-- [rust_primitives::arithmetic::overflowing_mul_i64]:
    Source: 'rust_primitives/src/lib.rs', lines 135:18-135:68
    Name pattern: [rust_primitives::arithmetic::overflowing_mul_i64]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::overflowing_mul_i64"]
axiom rust_primitives.arithmetic.overflowing_mul_i64
  : Std.I64 → Std.I64 → Result (Std.I64 × Bool)

/-- [rust_primitives::arithmetic::overflowing_sub_i128]:
    Source: 'rust_primitives/src/lib.rs', lines 135:18-135:68
    Name pattern: [rust_primitives::arithmetic::overflowing_sub_i128]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::overflowing_sub_i128"]
axiom rust_primitives.arithmetic.overflowing_sub_i128
  : Std.I128 → Std.I128 → Result (Std.I128 × Bool)

/-- [rust_primitives::arithmetic::overflowing_mul_i128]:
    Source: 'rust_primitives/src/lib.rs', lines 135:18-135:68
    Name pattern: [rust_primitives::arithmetic::overflowing_mul_i128]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::overflowing_mul_i128"]
axiom rust_primitives.arithmetic.overflowing_mul_i128
  : Std.I128 → Std.I128 → Result (Std.I128 × Bool)

/-- [rust_primitives::arithmetic::overflowing_sub_isize]:
    Source: 'rust_primitives/src/lib.rs', lines 135:18-135:68
    Name pattern: [rust_primitives::arithmetic::overflowing_sub_isize]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::overflowing_sub_isize"]
axiom rust_primitives.arithmetic.overflowing_sub_isize
  : Std.Isize → Std.Isize → Result (Std.Isize × Bool)

/-- [rust_primitives::arithmetic::overflowing_mul_isize]:
    Source: 'rust_primitives/src/lib.rs', lines 135:18-135:68
    Name pattern: [rust_primitives::arithmetic::overflowing_mul_isize]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::overflowing_mul_isize"]
axiom rust_primitives.arithmetic.overflowing_mul_isize
  : Std.Isize → Std.Isize → Result (Std.Isize × Bool)

/-- [rust_primitives::arithmetic::pow_u8]:
    Source: 'rust_primitives/src/lib.rs', lines 159:16-159:35
    Name pattern: [rust_primitives::arithmetic::pow_u8]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::pow_u8"]
axiom rust_primitives.arithmetic.pow_u8 : Std.U8 → Std.U32 → Result Std.U8

/-- [rust_primitives::arithmetic::pow_u16]:
    Source: 'rust_primitives/src/lib.rs', lines 159:16-159:35
    Name pattern: [rust_primitives::arithmetic::pow_u16]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::pow_u16"]
axiom rust_primitives.arithmetic.pow_u16
  : Std.U16 → Std.U32 → Result Std.U16

/-- [rust_primitives::arithmetic::pow_u32]:
    Source: 'rust_primitives/src/lib.rs', lines 159:16-159:35
    Name pattern: [rust_primitives::arithmetic::pow_u32]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::pow_u32"]
axiom rust_primitives.arithmetic.pow_u32
  : Std.U32 → Std.U32 → Result Std.U32

/-- [rust_primitives::arithmetic::pow_u64]:
    Source: 'rust_primitives/src/lib.rs', lines 159:16-159:35
    Name pattern: [rust_primitives::arithmetic::pow_u64]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::pow_u64"]
axiom rust_primitives.arithmetic.pow_u64
  : Std.U64 → Std.U32 → Result Std.U64

/-- [rust_primitives::arithmetic::pow_u128]:
    Source: 'rust_primitives/src/lib.rs', lines 159:16-159:35
    Name pattern: [rust_primitives::arithmetic::pow_u128]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::pow_u128"]
axiom rust_primitives.arithmetic.pow_u128
  : Std.U128 → Std.U32 → Result Std.U128

/-- [rust_primitives::arithmetic::pow_usize]:
    Source: 'rust_primitives/src/lib.rs', lines 159:16-159:35
    Name pattern: [rust_primitives::arithmetic::pow_usize]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::pow_usize"]
axiom rust_primitives.arithmetic.pow_usize
  : Std.Usize → Std.U32 → Result Std.Usize

/-- [rust_primitives::arithmetic::pow_i8]:
    Source: 'rust_primitives/src/lib.rs', lines 159:16-159:35
    Name pattern: [rust_primitives::arithmetic::pow_i8]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::pow_i8"]
axiom rust_primitives.arithmetic.pow_i8 : Std.I8 → Std.U32 → Result Std.I8

/-- [rust_primitives::arithmetic::pow_i16]:
    Source: 'rust_primitives/src/lib.rs', lines 159:16-159:35
    Name pattern: [rust_primitives::arithmetic::pow_i16]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::pow_i16"]
axiom rust_primitives.arithmetic.pow_i16
  : Std.I16 → Std.U32 → Result Std.I16

/-- [rust_primitives::arithmetic::pow_i32]:
    Source: 'rust_primitives/src/lib.rs', lines 159:16-159:35
    Name pattern: [rust_primitives::arithmetic::pow_i32]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::pow_i32"]
axiom rust_primitives.arithmetic.pow_i32
  : Std.I32 → Std.U32 → Result Std.I32

/-- [rust_primitives::arithmetic::pow_i64]:
    Source: 'rust_primitives/src/lib.rs', lines 159:16-159:35
    Name pattern: [rust_primitives::arithmetic::pow_i64]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::pow_i64"]
axiom rust_primitives.arithmetic.pow_i64
  : Std.I64 → Std.U32 → Result Std.I64

/-- [rust_primitives::arithmetic::pow_i128]:
    Source: 'rust_primitives/src/lib.rs', lines 159:16-159:35
    Name pattern: [rust_primitives::arithmetic::pow_i128]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::pow_i128"]
axiom rust_primitives.arithmetic.pow_i128
  : Std.I128 → Std.U32 → Result Std.I128

/-- [rust_primitives::arithmetic::pow_isize]:
    Source: 'rust_primitives/src/lib.rs', lines 159:16-159:35
    Name pattern: [rust_primitives::arithmetic::pow_isize]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::pow_isize"]
axiom rust_primitives.arithmetic.pow_isize
  : Std.Isize → Std.U32 → Result Std.Isize

/-- [rust_primitives::arithmetic::from_be_bytes_u8]:
    Source: 'rust_primitives/src/lib.rs', lines 159:30-177:19
    Name pattern: [rust_primitives::arithmetic::from_be_bytes_u8]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::from_be_bytes_u8"]
axiom rust_primitives.arithmetic.from_be_bytes_u8
  : Array Std.U8 1#usize → Result Std.U8

/-- [rust_primitives::arithmetic::from_le_bytes_u8]:
    Source: 'rust_primitives/src/lib.rs', lines 159:30-180:19
    Name pattern: [rust_primitives::arithmetic::from_le_bytes_u8]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::from_le_bytes_u8"]
axiom rust_primitives.arithmetic.from_le_bytes_u8
  : Array Std.U8 1#usize → Result Std.U8

/-- [rust_primitives::arithmetic::from_be_bytes_u16]:
    Source: 'rust_primitives/src/lib.rs', lines 159:30-177:19
    Name pattern: [rust_primitives::arithmetic::from_be_bytes_u16]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::from_be_bytes_u16"]
axiom rust_primitives.arithmetic.from_be_bytes_u16
  : Array Std.U8 2#usize → Result Std.U16

/-- [rust_primitives::arithmetic::from_le_bytes_u16]:
    Source: 'rust_primitives/src/lib.rs', lines 159:30-180:19
    Name pattern: [rust_primitives::arithmetic::from_le_bytes_u16]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::from_le_bytes_u16"]
axiom rust_primitives.arithmetic.from_le_bytes_u16
  : Array Std.U8 2#usize → Result Std.U16

/-- [rust_primitives::arithmetic::from_be_bytes_u32]:
    Source: 'rust_primitives/src/lib.rs', lines 159:30-177:19
    Name pattern: [rust_primitives::arithmetic::from_be_bytes_u32]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::from_be_bytes_u32"]
axiom rust_primitives.arithmetic.from_be_bytes_u32
  : Array Std.U8 4#usize → Result Std.U32

/-- [rust_primitives::arithmetic::from_le_bytes_u32]:
    Source: 'rust_primitives/src/lib.rs', lines 159:30-180:19
    Name pattern: [rust_primitives::arithmetic::from_le_bytes_u32]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::from_le_bytes_u32"]
axiom rust_primitives.arithmetic.from_le_bytes_u32
  : Array Std.U8 4#usize → Result Std.U32

/-- [rust_primitives::arithmetic::from_be_bytes_u64]:
    Source: 'rust_primitives/src/lib.rs', lines 159:30-177:19
    Name pattern: [rust_primitives::arithmetic::from_be_bytes_u64]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::from_be_bytes_u64"]
axiom rust_primitives.arithmetic.from_be_bytes_u64
  : Array Std.U8 8#usize → Result Std.U64

/-- [rust_primitives::arithmetic::from_le_bytes_u64]:
    Source: 'rust_primitives/src/lib.rs', lines 159:30-180:19
    Name pattern: [rust_primitives::arithmetic::from_le_bytes_u64]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::from_le_bytes_u64"]
axiom rust_primitives.arithmetic.from_le_bytes_u64
  : Array Std.U8 8#usize → Result Std.U64

/-- [rust_primitives::arithmetic::from_be_bytes_u128]:
    Source: 'rust_primitives/src/lib.rs', lines 159:30-177:19
    Name pattern: [rust_primitives::arithmetic::from_be_bytes_u128]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::from_be_bytes_u128"]
axiom rust_primitives.arithmetic.from_be_bytes_u128
  : Array Std.U8 16#usize → Result Std.U128

/-- [rust_primitives::arithmetic::from_le_bytes_u128]:
    Source: 'rust_primitives/src/lib.rs', lines 159:30-180:19
    Name pattern: [rust_primitives::arithmetic::from_le_bytes_u128]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::from_le_bytes_u128"]
axiom rust_primitives.arithmetic.from_le_bytes_u128
  : Array Std.U8 16#usize → Result Std.U128

/-- [rust_primitives::arithmetic::from_be_bytes_usize]:
    Source: 'rust_primitives/src/lib.rs', lines 159:30-177:19
    Name pattern: [rust_primitives::arithmetic::from_be_bytes_usize]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::from_be_bytes_usize"]
axiom rust_primitives.arithmetic.from_be_bytes_usize
  : Array Std.U8 8#usize → Result Std.Usize

/-- [rust_primitives::arithmetic::from_le_bytes_usize]:
    Source: 'rust_primitives/src/lib.rs', lines 159:30-180:19
    Name pattern: [rust_primitives::arithmetic::from_le_bytes_usize]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::from_le_bytes_usize"]
axiom rust_primitives.arithmetic.from_le_bytes_usize
  : Array Std.U8 8#usize → Result Std.Usize

/-- [rust_primitives::arithmetic::from_be_bytes_i8]:
    Source: 'rust_primitives/src/lib.rs', lines 159:30-177:19
    Name pattern: [rust_primitives::arithmetic::from_be_bytes_i8]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::from_be_bytes_i8"]
axiom rust_primitives.arithmetic.from_be_bytes_i8
  : Array Std.U8 1#usize → Result Std.I8

/-- [rust_primitives::arithmetic::from_le_bytes_i8]:
    Source: 'rust_primitives/src/lib.rs', lines 159:30-180:19
    Name pattern: [rust_primitives::arithmetic::from_le_bytes_i8]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::from_le_bytes_i8"]
axiom rust_primitives.arithmetic.from_le_bytes_i8
  : Array Std.U8 1#usize → Result Std.I8

/-- [rust_primitives::arithmetic::from_be_bytes_i16]:
    Source: 'rust_primitives/src/lib.rs', lines 159:30-177:19
    Name pattern: [rust_primitives::arithmetic::from_be_bytes_i16]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::from_be_bytes_i16"]
axiom rust_primitives.arithmetic.from_be_bytes_i16
  : Array Std.U8 2#usize → Result Std.I16

/-- [rust_primitives::arithmetic::from_le_bytes_i16]:
    Source: 'rust_primitives/src/lib.rs', lines 159:30-180:19
    Name pattern: [rust_primitives::arithmetic::from_le_bytes_i16]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::from_le_bytes_i16"]
axiom rust_primitives.arithmetic.from_le_bytes_i16
  : Array Std.U8 2#usize → Result Std.I16

/-- [rust_primitives::arithmetic::from_be_bytes_i32]:
    Source: 'rust_primitives/src/lib.rs', lines 159:30-177:19
    Name pattern: [rust_primitives::arithmetic::from_be_bytes_i32]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::from_be_bytes_i32"]
axiom rust_primitives.arithmetic.from_be_bytes_i32
  : Array Std.U8 4#usize → Result Std.I32

/-- [rust_primitives::arithmetic::from_le_bytes_i32]:
    Source: 'rust_primitives/src/lib.rs', lines 159:30-180:19
    Name pattern: [rust_primitives::arithmetic::from_le_bytes_i32]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::from_le_bytes_i32"]
axiom rust_primitives.arithmetic.from_le_bytes_i32
  : Array Std.U8 4#usize → Result Std.I32

/-- [rust_primitives::arithmetic::from_be_bytes_i64]:
    Source: 'rust_primitives/src/lib.rs', lines 159:30-177:19
    Name pattern: [rust_primitives::arithmetic::from_be_bytes_i64]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::from_be_bytes_i64"]
axiom rust_primitives.arithmetic.from_be_bytes_i64
  : Array Std.U8 8#usize → Result Std.I64

/-- [rust_primitives::arithmetic::from_le_bytes_i64]:
    Source: 'rust_primitives/src/lib.rs', lines 159:30-180:19
    Name pattern: [rust_primitives::arithmetic::from_le_bytes_i64]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::from_le_bytes_i64"]
axiom rust_primitives.arithmetic.from_le_bytes_i64
  : Array Std.U8 8#usize → Result Std.I64

/-- [rust_primitives::arithmetic::from_be_bytes_i128]:
    Source: 'rust_primitives/src/lib.rs', lines 159:30-177:19
    Name pattern: [rust_primitives::arithmetic::from_be_bytes_i128]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::from_be_bytes_i128"]
axiom rust_primitives.arithmetic.from_be_bytes_i128
  : Array Std.U8 16#usize → Result Std.I128

/-- [rust_primitives::arithmetic::from_le_bytes_i128]:
    Source: 'rust_primitives/src/lib.rs', lines 159:30-180:19
    Name pattern: [rust_primitives::arithmetic::from_le_bytes_i128]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::from_le_bytes_i128"]
axiom rust_primitives.arithmetic.from_le_bytes_i128
  : Array Std.U8 16#usize → Result Std.I128

/-- [rust_primitives::arithmetic::from_be_bytes_isize]:
    Source: 'rust_primitives/src/lib.rs', lines 159:30-177:19
    Name pattern: [rust_primitives::arithmetic::from_be_bytes_isize]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::from_be_bytes_isize"]
axiom rust_primitives.arithmetic.from_be_bytes_isize
  : Array Std.U8 8#usize → Result Std.Isize

/-- [rust_primitives::arithmetic::from_le_bytes_isize]:
    Source: 'rust_primitives/src/lib.rs', lines 159:30-180:19
    Name pattern: [rust_primitives::arithmetic::from_le_bytes_isize]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::from_le_bytes_isize"]
axiom rust_primitives.arithmetic.from_le_bytes_isize
  : Array Std.U8 8#usize → Result Std.Isize

/-- [rust_primitives::arithmetic::count_ones_u8]:
    Source: 'rust_primitives/src/lib.rs', lines 162:16-162:61
    Name pattern: [rust_primitives::arithmetic::count_ones_u8]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::count_ones_u8"]
axiom rust_primitives.arithmetic.count_ones_u8 : Std.U8 → Result Std.U32

/-- [rust_primitives::arithmetic::count_ones_u16]:
    Source: 'rust_primitives/src/lib.rs', lines 162:16-162:61
    Name pattern: [rust_primitives::arithmetic::count_ones_u16]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::count_ones_u16"]
axiom rust_primitives.arithmetic.count_ones_u16 : Std.U16 → Result Std.U32

/-- [rust_primitives::arithmetic::count_ones_u32]:
    Source: 'rust_primitives/src/lib.rs', lines 162:16-162:61
    Name pattern: [rust_primitives::arithmetic::count_ones_u32]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::count_ones_u32"]
axiom rust_primitives.arithmetic.count_ones_u32 : Std.U32 → Result Std.U32

/-- [rust_primitives::arithmetic::count_ones_u64]:
    Source: 'rust_primitives/src/lib.rs', lines 162:16-162:61
    Name pattern: [rust_primitives::arithmetic::count_ones_u64]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::count_ones_u64"]
axiom rust_primitives.arithmetic.count_ones_u64 : Std.U64 → Result Std.U32

/-- [rust_primitives::arithmetic::count_ones_u128]:
    Source: 'rust_primitives/src/lib.rs', lines 162:16-162:61
    Name pattern: [rust_primitives::arithmetic::count_ones_u128]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::count_ones_u128"]
axiom rust_primitives.arithmetic.count_ones_u128 : Std.U128 → Result Std.U32

/-- [rust_primitives::arithmetic::count_ones_usize]:
    Source: 'rust_primitives/src/lib.rs', lines 162:16-162:61
    Name pattern: [rust_primitives::arithmetic::count_ones_usize]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::count_ones_usize"]
axiom rust_primitives.arithmetic.count_ones_usize
  : Std.Usize → Result Std.U32

/-- [rust_primitives::arithmetic::count_ones_i8]:
    Source: 'rust_primitives/src/lib.rs', lines 162:16-162:61
    Name pattern: [rust_primitives::arithmetic::count_ones_i8]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::count_ones_i8"]
axiom rust_primitives.arithmetic.count_ones_i8 : Std.I8 → Result Std.U32

/-- [rust_primitives::arithmetic::count_ones_i16]:
    Source: 'rust_primitives/src/lib.rs', lines 162:16-162:61
    Name pattern: [rust_primitives::arithmetic::count_ones_i16]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::count_ones_i16"]
axiom rust_primitives.arithmetic.count_ones_i16 : Std.I16 → Result Std.U32

/-- [rust_primitives::arithmetic::count_ones_i32]:
    Source: 'rust_primitives/src/lib.rs', lines 162:16-162:61
    Name pattern: [rust_primitives::arithmetic::count_ones_i32]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::count_ones_i32"]
axiom rust_primitives.arithmetic.count_ones_i32 : Std.I32 → Result Std.U32

/-- [rust_primitives::arithmetic::count_ones_i64]:
    Source: 'rust_primitives/src/lib.rs', lines 162:16-162:61
    Name pattern: [rust_primitives::arithmetic::count_ones_i64]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::count_ones_i64"]
axiom rust_primitives.arithmetic.count_ones_i64 : Std.I64 → Result Std.U32

/-- [rust_primitives::arithmetic::count_ones_i128]:
    Source: 'rust_primitives/src/lib.rs', lines 162:16-162:61
    Name pattern: [rust_primitives::arithmetic::count_ones_i128]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::count_ones_i128"]
axiom rust_primitives.arithmetic.count_ones_i128 : Std.I128 → Result Std.U32

/-- [rust_primitives::arithmetic::count_ones_isize]:
    Source: 'rust_primitives/src/lib.rs', lines 162:16-162:61
    Name pattern: [rust_primitives::arithmetic::count_ones_isize]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::count_ones_isize"]
axiom rust_primitives.arithmetic.count_ones_isize
  : Std.Isize → Result Std.U32

/-- [rust_primitives::arithmetic::leading_zeros_u8]:
    Source: 'rust_primitives/src/lib.rs', lines 171:16-171:64
    Name pattern: [rust_primitives::arithmetic::leading_zeros_u8]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::leading_zeros_u8"]
axiom rust_primitives.arithmetic.leading_zeros_u8 : Std.U8 → Result Std.U32

/-- [rust_primitives::arithmetic::leading_zeros_u16]:
    Source: 'rust_primitives/src/lib.rs', lines 171:16-171:64
    Name pattern: [rust_primitives::arithmetic::leading_zeros_u16]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::leading_zeros_u16"]
axiom rust_primitives.arithmetic.leading_zeros_u16 : Std.U16 → Result Std.U32

/-- [rust_primitives::arithmetic::leading_zeros_u32]:
    Source: 'rust_primitives/src/lib.rs', lines 171:16-171:64
    Name pattern: [rust_primitives::arithmetic::leading_zeros_u32]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::leading_zeros_u32"]
axiom rust_primitives.arithmetic.leading_zeros_u32 : Std.U32 → Result Std.U32

/-- [rust_primitives::arithmetic::leading_zeros_u64]:
    Source: 'rust_primitives/src/lib.rs', lines 171:16-171:64
    Name pattern: [rust_primitives::arithmetic::leading_zeros_u64]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::leading_zeros_u64"]
axiom rust_primitives.arithmetic.leading_zeros_u64 : Std.U64 → Result Std.U32

/-- [rust_primitives::arithmetic::leading_zeros_u128]:
    Source: 'rust_primitives/src/lib.rs', lines 171:16-171:64
    Name pattern: [rust_primitives::arithmetic::leading_zeros_u128]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::leading_zeros_u128"]
axiom rust_primitives.arithmetic.leading_zeros_u128
  : Std.U128 → Result Std.U32

/-- [rust_primitives::arithmetic::leading_zeros_usize]:
    Source: 'rust_primitives/src/lib.rs', lines 171:16-171:64
    Name pattern: [rust_primitives::arithmetic::leading_zeros_usize]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::leading_zeros_usize"]
axiom rust_primitives.arithmetic.leading_zeros_usize
  : Std.Usize → Result Std.U32

/-- [rust_primitives::arithmetic::leading_zeros_i8]:
    Source: 'rust_primitives/src/lib.rs', lines 171:16-171:64
    Name pattern: [rust_primitives::arithmetic::leading_zeros_i8]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::leading_zeros_i8"]
axiom rust_primitives.arithmetic.leading_zeros_i8 : Std.I8 → Result Std.U32

/-- [rust_primitives::arithmetic::leading_zeros_i16]:
    Source: 'rust_primitives/src/lib.rs', lines 171:16-171:64
    Name pattern: [rust_primitives::arithmetic::leading_zeros_i16]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::leading_zeros_i16"]
axiom rust_primitives.arithmetic.leading_zeros_i16 : Std.I16 → Result Std.U32

/-- [rust_primitives::arithmetic::leading_zeros_i32]:
    Source: 'rust_primitives/src/lib.rs', lines 171:16-171:64
    Name pattern: [rust_primitives::arithmetic::leading_zeros_i32]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::leading_zeros_i32"]
axiom rust_primitives.arithmetic.leading_zeros_i32 : Std.I32 → Result Std.U32

/-- [rust_primitives::arithmetic::leading_zeros_i64]:
    Source: 'rust_primitives/src/lib.rs', lines 171:16-171:64
    Name pattern: [rust_primitives::arithmetic::leading_zeros_i64]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::leading_zeros_i64"]
axiom rust_primitives.arithmetic.leading_zeros_i64 : Std.I64 → Result Std.U32

/-- [rust_primitives::arithmetic::leading_zeros_i128]:
    Source: 'rust_primitives/src/lib.rs', lines 171:16-171:64
    Name pattern: [rust_primitives::arithmetic::leading_zeros_i128]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::leading_zeros_i128"]
axiom rust_primitives.arithmetic.leading_zeros_i128
  : Std.I128 → Result Std.U32

/-- [rust_primitives::arithmetic::leading_zeros_isize]:
    Source: 'rust_primitives/src/lib.rs', lines 171:16-171:64
    Name pattern: [rust_primitives::arithmetic::leading_zeros_isize]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::leading_zeros_isize"]
axiom rust_primitives.arithmetic.leading_zeros_isize
  : Std.Isize → Result Std.U32

/-- [rust_primitives::arithmetic::ilog2_u8]:
    Source: 'rust_primitives/src/lib.rs', lines 174:16-174:56
    Name pattern: [rust_primitives::arithmetic::ilog2_u8]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::ilog2_u8"]
axiom rust_primitives.arithmetic.ilog2_u8 : Std.U8 → Result Std.U32

/-- [rust_primitives::arithmetic::ilog2_u16]:
    Source: 'rust_primitives/src/lib.rs', lines 174:16-174:56
    Name pattern: [rust_primitives::arithmetic::ilog2_u16]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::ilog2_u16"]
axiom rust_primitives.arithmetic.ilog2_u16 : Std.U16 → Result Std.U32

/-- [rust_primitives::arithmetic::ilog2_u32]:
    Source: 'rust_primitives/src/lib.rs', lines 174:16-174:56
    Name pattern: [rust_primitives::arithmetic::ilog2_u32]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::ilog2_u32"]
axiom rust_primitives.arithmetic.ilog2_u32 : Std.U32 → Result Std.U32

/-- [rust_primitives::arithmetic::ilog2_u64]:
    Source: 'rust_primitives/src/lib.rs', lines 174:16-174:56
    Name pattern: [rust_primitives::arithmetic::ilog2_u64]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::ilog2_u64"]
axiom rust_primitives.arithmetic.ilog2_u64 : Std.U64 → Result Std.U32

/-- [rust_primitives::arithmetic::ilog2_u128]:
    Source: 'rust_primitives/src/lib.rs', lines 174:16-174:56
    Name pattern: [rust_primitives::arithmetic::ilog2_u128]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::ilog2_u128"]
axiom rust_primitives.arithmetic.ilog2_u128 : Std.U128 → Result Std.U32

/-- [rust_primitives::arithmetic::ilog2_usize]:
    Source: 'rust_primitives/src/lib.rs', lines 174:16-174:56
    Name pattern: [rust_primitives::arithmetic::ilog2_usize]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::ilog2_usize"]
axiom rust_primitives.arithmetic.ilog2_usize : Std.Usize → Result Std.U32

/-- [rust_primitives::arithmetic::ilog2_i8]:
    Source: 'rust_primitives/src/lib.rs', lines 174:16-174:56
    Name pattern: [rust_primitives::arithmetic::ilog2_i8]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::ilog2_i8"]
axiom rust_primitives.arithmetic.ilog2_i8 : Std.I8 → Result Std.U32

/-- [rust_primitives::arithmetic::ilog2_i16]:
    Source: 'rust_primitives/src/lib.rs', lines 174:16-174:56
    Name pattern: [rust_primitives::arithmetic::ilog2_i16]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::ilog2_i16"]
axiom rust_primitives.arithmetic.ilog2_i16 : Std.I16 → Result Std.U32

/-- [rust_primitives::arithmetic::ilog2_i32]:
    Source: 'rust_primitives/src/lib.rs', lines 174:16-174:56
    Name pattern: [rust_primitives::arithmetic::ilog2_i32]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::ilog2_i32"]
axiom rust_primitives.arithmetic.ilog2_i32 : Std.I32 → Result Std.U32

/-- [rust_primitives::arithmetic::ilog2_i64]:
    Source: 'rust_primitives/src/lib.rs', lines 174:16-174:56
    Name pattern: [rust_primitives::arithmetic::ilog2_i64]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::ilog2_i64"]
axiom rust_primitives.arithmetic.ilog2_i64 : Std.I64 → Result Std.U32

/-- [rust_primitives::arithmetic::ilog2_i128]:
    Source: 'rust_primitives/src/lib.rs', lines 174:16-174:56
    Name pattern: [rust_primitives::arithmetic::ilog2_i128]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::ilog2_i128"]
axiom rust_primitives.arithmetic.ilog2_i128 : Std.I128 → Result Std.U32

/-- [rust_primitives::arithmetic::ilog2_isize]:
    Source: 'rust_primitives/src/lib.rs', lines 174:16-174:56
    Name pattern: [rust_primitives::arithmetic::ilog2_isize]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::ilog2_isize"]
axiom rust_primitives.arithmetic.ilog2_isize : Std.Isize → Result Std.U32

/-- [rust_primitives::arithmetic::to_be_bytes_u8]:
    Source: 'rust_primitives/src/lib.rs', lines 183:16-183:75
    Name pattern: [rust_primitives::arithmetic::to_be_bytes_u8]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::to_be_bytes_u8"]
axiom rust_primitives.arithmetic.to_be_bytes_u8
  : Std.U8 → Result (Array Std.U8 1#usize)

/-- [rust_primitives::arithmetic::to_be_bytes_u16]:
    Source: 'rust_primitives/src/lib.rs', lines 183:16-183:75
    Name pattern: [rust_primitives::arithmetic::to_be_bytes_u16]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::to_be_bytes_u16"]
axiom rust_primitives.arithmetic.to_be_bytes_u16
  : Std.U16 → Result (Array Std.U8 2#usize)

/-- [rust_primitives::arithmetic::to_be_bytes_u32]:
    Source: 'rust_primitives/src/lib.rs', lines 183:16-183:75
    Name pattern: [rust_primitives::arithmetic::to_be_bytes_u32]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::to_be_bytes_u32"]
axiom rust_primitives.arithmetic.to_be_bytes_u32
  : Std.U32 → Result (Array Std.U8 4#usize)

/-- [rust_primitives::arithmetic::to_be_bytes_u64]:
    Source: 'rust_primitives/src/lib.rs', lines 183:16-183:75
    Name pattern: [rust_primitives::arithmetic::to_be_bytes_u64]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::to_be_bytes_u64"]
axiom rust_primitives.arithmetic.to_be_bytes_u64
  : Std.U64 → Result (Array Std.U8 8#usize)

/-- [rust_primitives::arithmetic::to_be_bytes_u128]:
    Source: 'rust_primitives/src/lib.rs', lines 183:16-183:75
    Name pattern: [rust_primitives::arithmetic::to_be_bytes_u128]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::to_be_bytes_u128"]
axiom rust_primitives.arithmetic.to_be_bytes_u128
  : Std.U128 → Result (Array Std.U8 16#usize)

/-- [rust_primitives::arithmetic::to_be_bytes_usize]:
    Source: 'rust_primitives/src/lib.rs', lines 183:16-183:75
    Name pattern: [rust_primitives::arithmetic::to_be_bytes_usize]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::to_be_bytes_usize"]
axiom rust_primitives.arithmetic.to_be_bytes_usize
  : Std.Usize → Result (Array Std.U8 8#usize)

/-- [rust_primitives::arithmetic::to_be_bytes_i8]:
    Source: 'rust_primitives/src/lib.rs', lines 183:16-183:75
    Name pattern: [rust_primitives::arithmetic::to_be_bytes_i8]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::to_be_bytes_i8"]
axiom rust_primitives.arithmetic.to_be_bytes_i8
  : Std.I8 → Result (Array Std.U8 1#usize)

/-- [rust_primitives::arithmetic::to_be_bytes_i16]:
    Source: 'rust_primitives/src/lib.rs', lines 183:16-183:75
    Name pattern: [rust_primitives::arithmetic::to_be_bytes_i16]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::to_be_bytes_i16"]
axiom rust_primitives.arithmetic.to_be_bytes_i16
  : Std.I16 → Result (Array Std.U8 2#usize)

/-- [rust_primitives::arithmetic::to_be_bytes_i32]:
    Source: 'rust_primitives/src/lib.rs', lines 183:16-183:75
    Name pattern: [rust_primitives::arithmetic::to_be_bytes_i32]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::to_be_bytes_i32"]
axiom rust_primitives.arithmetic.to_be_bytes_i32
  : Std.I32 → Result (Array Std.U8 4#usize)

/-- [rust_primitives::arithmetic::to_be_bytes_i64]:
    Source: 'rust_primitives/src/lib.rs', lines 183:16-183:75
    Name pattern: [rust_primitives::arithmetic::to_be_bytes_i64]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::to_be_bytes_i64"]
axiom rust_primitives.arithmetic.to_be_bytes_i64
  : Std.I64 → Result (Array Std.U8 8#usize)

/-- [rust_primitives::arithmetic::to_be_bytes_i128]:
    Source: 'rust_primitives/src/lib.rs', lines 183:16-183:75
    Name pattern: [rust_primitives::arithmetic::to_be_bytes_i128]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::to_be_bytes_i128"]
axiom rust_primitives.arithmetic.to_be_bytes_i128
  : Std.I128 → Result (Array Std.U8 16#usize)

/-- [rust_primitives::arithmetic::to_be_bytes_isize]:
    Source: 'rust_primitives/src/lib.rs', lines 183:16-183:75
    Name pattern: [rust_primitives::arithmetic::to_be_bytes_isize]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::to_be_bytes_isize"]
axiom rust_primitives.arithmetic.to_be_bytes_isize
  : Std.Isize → Result (Array Std.U8 8#usize)

/-- [rust_primitives::arithmetic::to_le_bytes_u8]:
    Source: 'rust_primitives/src/lib.rs', lines 186:16-186:75
    Name pattern: [rust_primitives::arithmetic::to_le_bytes_u8]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::to_le_bytes_u8"]
axiom rust_primitives.arithmetic.to_le_bytes_u8
  : Std.U8 → Result (Array Std.U8 1#usize)

/-- [rust_primitives::arithmetic::to_le_bytes_u16]:
    Source: 'rust_primitives/src/lib.rs', lines 186:16-186:75
    Name pattern: [rust_primitives::arithmetic::to_le_bytes_u16]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::to_le_bytes_u16"]
axiom rust_primitives.arithmetic.to_le_bytes_u16
  : Std.U16 → Result (Array Std.U8 2#usize)

/-- [rust_primitives::arithmetic::to_le_bytes_u32]:
    Source: 'rust_primitives/src/lib.rs', lines 186:16-186:75
    Name pattern: [rust_primitives::arithmetic::to_le_bytes_u32]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::to_le_bytes_u32"]
axiom rust_primitives.arithmetic.to_le_bytes_u32
  : Std.U32 → Result (Array Std.U8 4#usize)

/-- [rust_primitives::arithmetic::to_le_bytes_u64]:
    Source: 'rust_primitives/src/lib.rs', lines 186:16-186:75
    Name pattern: [rust_primitives::arithmetic::to_le_bytes_u64]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::to_le_bytes_u64"]
axiom rust_primitives.arithmetic.to_le_bytes_u64
  : Std.U64 → Result (Array Std.U8 8#usize)

/-- [rust_primitives::arithmetic::to_le_bytes_u128]:
    Source: 'rust_primitives/src/lib.rs', lines 186:16-186:75
    Name pattern: [rust_primitives::arithmetic::to_le_bytes_u128]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::to_le_bytes_u128"]
axiom rust_primitives.arithmetic.to_le_bytes_u128
  : Std.U128 → Result (Array Std.U8 16#usize)

/-- [rust_primitives::arithmetic::to_le_bytes_usize]:
    Source: 'rust_primitives/src/lib.rs', lines 186:16-186:75
    Name pattern: [rust_primitives::arithmetic::to_le_bytes_usize]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::to_le_bytes_usize"]
axiom rust_primitives.arithmetic.to_le_bytes_usize
  : Std.Usize → Result (Array Std.U8 8#usize)

/-- [rust_primitives::arithmetic::to_le_bytes_i8]:
    Source: 'rust_primitives/src/lib.rs', lines 186:16-186:75
    Name pattern: [rust_primitives::arithmetic::to_le_bytes_i8]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::to_le_bytes_i8"]
axiom rust_primitives.arithmetic.to_le_bytes_i8
  : Std.I8 → Result (Array Std.U8 1#usize)

/-- [rust_primitives::arithmetic::to_le_bytes_i16]:
    Source: 'rust_primitives/src/lib.rs', lines 186:16-186:75
    Name pattern: [rust_primitives::arithmetic::to_le_bytes_i16]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::to_le_bytes_i16"]
axiom rust_primitives.arithmetic.to_le_bytes_i16
  : Std.I16 → Result (Array Std.U8 2#usize)

/-- [rust_primitives::arithmetic::to_le_bytes_i32]:
    Source: 'rust_primitives/src/lib.rs', lines 186:16-186:75
    Name pattern: [rust_primitives::arithmetic::to_le_bytes_i32]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::to_le_bytes_i32"]
axiom rust_primitives.arithmetic.to_le_bytes_i32
  : Std.I32 → Result (Array Std.U8 4#usize)

/-- [rust_primitives::arithmetic::to_le_bytes_i64]:
    Source: 'rust_primitives/src/lib.rs', lines 186:16-186:75
    Name pattern: [rust_primitives::arithmetic::to_le_bytes_i64]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::to_le_bytes_i64"]
axiom rust_primitives.arithmetic.to_le_bytes_i64
  : Std.I64 → Result (Array Std.U8 8#usize)

/-- [rust_primitives::arithmetic::to_le_bytes_i128]:
    Source: 'rust_primitives/src/lib.rs', lines 186:16-186:75
    Name pattern: [rust_primitives::arithmetic::to_le_bytes_i128]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::to_le_bytes_i128"]
axiom rust_primitives.arithmetic.to_le_bytes_i128
  : Std.I128 → Result (Array Std.U8 16#usize)

/-- [rust_primitives::arithmetic::to_le_bytes_isize]:
    Source: 'rust_primitives/src/lib.rs', lines 186:16-186:75
    Name pattern: [rust_primitives::arithmetic::to_le_bytes_isize]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::to_le_bytes_isize"]
axiom rust_primitives.arithmetic.to_le_bytes_isize
  : Std.Isize → Result (Array Std.U8 8#usize)

/-- [rust_primitives::arithmetic::abs_i8]:
    Source: 'rust_primitives/src/lib.rs', lines 197:20-197:39
    Name pattern: [rust_primitives::arithmetic::abs_i8]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::abs_i8"]
axiom rust_primitives.arithmetic.abs_i8 : Std.I8 → Result Std.I8

/-- [rust_primitives::arithmetic::abs_i16]:
    Source: 'rust_primitives/src/lib.rs', lines 197:20-197:39
    Name pattern: [rust_primitives::arithmetic::abs_i16]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::abs_i16"]
axiom rust_primitives.arithmetic.abs_i16 : Std.I16 → Result Std.I16

/-- [rust_primitives::arithmetic::abs_i32]:
    Source: 'rust_primitives/src/lib.rs', lines 197:20-197:39
    Name pattern: [rust_primitives::arithmetic::abs_i32]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::abs_i32"]
axiom rust_primitives.arithmetic.abs_i32 : Std.I32 → Result Std.I32

/-- [rust_primitives::arithmetic::abs_i64]:
    Source: 'rust_primitives/src/lib.rs', lines 197:20-197:39
    Name pattern: [rust_primitives::arithmetic::abs_i64]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::abs_i64"]
axiom rust_primitives.arithmetic.abs_i64 : Std.I64 → Result Std.I64

/-- [rust_primitives::arithmetic::abs_i128]:
    Source: 'rust_primitives/src/lib.rs', lines 197:20-197:39
    Name pattern: [rust_primitives::arithmetic::abs_i128]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::abs_i128"]
axiom rust_primitives.arithmetic.abs_i128 : Std.I128 → Result Std.I128

/-- [rust_primitives::arithmetic::abs_isize]:
    Source: 'rust_primitives/src/lib.rs', lines 197:20-197:39
    Name pattern: [rust_primitives::arithmetic::abs_isize]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::abs_isize"]
axiom rust_primitives.arithmetic.abs_isize : Std.Isize → Result Std.Isize

/-- [rust_primitives::arithmetic::SIZE_BITS]
    Source: 'rust_primitives/src/lib.rs', lines 208:4-208:28
    Name pattern: [rust_primitives::arithmetic::SIZE_BITS]
    Visibility: public -/
@[rust_const "rust_primitives::arithmetic::SIZE_BITS"]
axiom rust_primitives.arithmetic.SIZE_BITS : Result Std.U32

/-- [rust_primitives::arithmetic::USIZE_MAX]
    Source: 'rust_primitives/src/lib.rs', lines 209:4-209:30
    Name pattern: [rust_primitives::arithmetic::USIZE_MAX]
    Visibility: public -/
@[rust_const "rust_primitives::arithmetic::USIZE_MAX"]
def rust_primitives.arithmetic.USIZE_MAX : Result Std.Usize := ok num.Usize.MAX

/-- [rust_primitives::arithmetic::ISIZE_MAX]
    Source: 'rust_primitives/src/lib.rs', lines 210:4-210:30
    Name pattern: [rust_primitives::arithmetic::ISIZE_MAX]
    Visibility: public -/
@[rust_const "rust_primitives::arithmetic::ISIZE_MAX"]
def rust_primitives.arithmetic.ISIZE_MAX : Result Std.Isize := ok num.Isize.MAX

/-- [rust_primitives::arithmetic::ISIZE_MIN]
    Source: 'rust_primitives/src/lib.rs', lines 211:4-211:30
    Name pattern: [rust_primitives::arithmetic::ISIZE_MIN]
    Visibility: public -/
@[rust_const "rust_primitives::arithmetic::ISIZE_MIN"]
def rust_primitives.arithmetic.ISIZE_MIN : Result Std.Isize := ok num.Isize.MIN

-- ============================================================================
-- alloc-side externals
--
-- These declarations are needed by `Aeneas/Alloc/Funs.lean` (the
-- charon+Aeneas extraction of the local `core-models/alloc/` crate). The
-- alloc extraction would otherwise generate its own
-- `Alloc/{Funs,Types}External.lean` template; we keep them here so that
-- the alloc subdirectory holds only the files Aeneas can populate by
-- itself, and so eventual implementations can replace `axiom` with `def`
-- in one place.
-- ============================================================================

/-- [alloc::string::{alloc::string::String}::new]:
    Source: '/rustc/library/alloc/src/string.rs', lines 437:4-437:32
    Name pattern: [alloc::string::{alloc::string::String}::new]
    Visibility: public -/
@[rust_fun "alloc::string::{alloc::string::String}::new"]
axiom alloc.string.String.new : Result String

/-- [rust_primitives::sequence::seq_empty]:
    Name pattern: [rust_primitives::sequence::seq_empty]
    Visibility: public -/
@[rust_fun "rust_primitives::sequence::seq_empty"]
axiom rust_primitives.sequence.seq_empty
  (T : Type) : Result (rust_primitives.sequence.Seq T)

/-- [rust_primitives::sequence::seq_from_boxed_slice]:
    Name pattern: [rust_primitives::sequence::seq_from_boxed_slice]
    Visibility: public -/
@[rust_fun "rust_primitives::sequence::seq_from_boxed_slice"]
axiom rust_primitives.sequence.seq_from_boxed_slice
  {T : Type} : Slice T → Result (rust_primitives.sequence.Seq T)

/-- [rust_primitives::sequence::seq_to_slice]:
    Name pattern: [rust_primitives::sequence::seq_to_slice]
    Visibility: public -/
@[rust_fun "rust_primitives::sequence::seq_to_slice"]
axiom rust_primitives.sequence.seq_to_slice
  {T : Type} : rust_primitives.sequence.Seq T → Result (Slice T)

/-- [rust_primitives::sequence::seq_concat]:
    Name pattern: [rust_primitives::sequence::seq_concat]
    Visibility: public -/
@[rust_fun "rust_primitives::sequence::seq_concat"]
axiom rust_primitives.sequence.seq_concat
  {T : Type} :
  rust_primitives.sequence.Seq T → rust_primitives.sequence.Seq T → Result
    ((rust_primitives.sequence.Seq T) × (rust_primitives.sequence.Seq T))

/-- [rust_primitives::sequence::seq_extend]:
    Name pattern: [rust_primitives::sequence::seq_extend]
    Visibility: public -/
@[rust_fun "rust_primitives::sequence::seq_extend"]
axiom rust_primitives.sequence.seq_extend
  {T : Type} (corecloneCloneInst : core.clone.Clone T) :
  rust_primitives.sequence.Seq T → Slice T → Result
    (rust_primitives.sequence.Seq T)

/-- [rust_primitives::sequence::seq_push]:
    Name pattern: [rust_primitives::sequence::seq_push]
    Visibility: public -/
@[rust_fun "rust_primitives::sequence::seq_push"]
axiom rust_primitives.sequence.seq_push
  {T : Type} :
  rust_primitives.sequence.Seq T → T → Result (rust_primitives.sequence.Seq T)

/-- [rust_primitives::sequence::seq_create]:
    Name pattern: [rust_primitives::sequence::seq_create]
    Visibility: public -/
@[rust_fun "rust_primitives::sequence::seq_create"]
axiom rust_primitives.sequence.seq_create
  {T : Type} (corecloneCloneInst : core.clone.Clone T) :
  T → Std.Usize → Result (rust_primitives.sequence.Seq T)

/-- [rust_primitives::sequence::seq_drain]:
    Name pattern: [rust_primitives::sequence::seq_drain]
    Visibility: public -/
@[rust_fun "rust_primitives::sequence::seq_drain"]
axiom rust_primitives.sequence.seq_drain
  {T : Type} :
  rust_primitives.sequence.Seq T → Std.Usize → Std.Usize → Result
    ((rust_primitives.sequence.Seq T) × (rust_primitives.sequence.Seq T))

/-- [rust_primitives::sequence::seq_index]:
    Name pattern: [rust_primitives::sequence::seq_index]
    Visibility: public -/
@[rust_fun "rust_primitives::sequence::seq_index"]
axiom rust_primitives.sequence.seq_index
  {T : Type} : rust_primitives.sequence.Seq T → Std.Usize → Result T
