-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [core_models]: external types.
-- This is a template file: rename it to "TypesExternal.lean" and fill the holes.
import Aeneas.Primitives
open core core.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/-- [hax_lib::prop::Prop]
    Source: '/home/alex/Projects/hax-evit/aeneas-mvcgen/hax-lib/src/prop.rs', lines 6:0-6:15
    Name pattern: [hax_lib::prop::Prop]
    Visibility: public -/
@[rust_type "hax_lib::prop::Prop"]
def hax_lib.prop.Prop : Type := Prop

/-- [hax_lib::int::Int]
    Source: '/home/alex/Projects/hax-evit/aeneas-mvcgen/hax-lib/src/int/mod.rs', lines 17:0-17:14
    Name pattern: [hax_lib::int::Int]
    Visibility: public -/
@[rust_type "hax_lib::int::Int"]
def hax_lib.int.Int : Type := _root_.Int

/-- [rust_primitives::sequence::Seq]
    Source: 'rust_primitives/src/lib.rs', lines 47:4-47:21
    Name pattern: [rust_primitives::sequence::Seq]
    Visibility: public -/
@[rust_type "rust_primitives::sequence::Seq"]
def rust_primitives.sequence.Seq (T : Type) : Type := Array T

