-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [aeneas_test]: function definitions
import Aeneas
import AeneasTest.Types
import AeneasTest.FunsExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace aeneas_test

/-- [aeneas_test::array_from_fn]:
    Source: 'src/lib.rs', lines 25:0-27:1
    Visibility: public -/
def array_from_fn
  {T : Type} {F : Type} (coreopsfunctionFnFTupleUsizeTInst :
  core.ops.function.Fn F Std.Usize T) (f : F) :
  Result (Array T 10#usize)
  := do
  core.array.from_fn 10#usize coreopsfunctionFnFTupleUsizeTInst.FnMutInst f

/-- [aeneas_test::array_from_fn_closure::{core::ops::function::FnMut<(usize), usize> for aeneas_test::array_from_fn_closure::closure}::call_mut]:
    Source: 'src/lib.rs', lines 33:24-33:36 -/
def
  array_from_fn_closure.closure.Insts.CoreOpsFunctionFnMutTupleUsizeUsize.call_mut
  (c : array_from_fn_closure.closure) (tupled_args : Std.Usize) :
  Result (Std.Usize × array_from_fn_closure.closure)
  := do
  ok (tupled_args, c)

/-- [aeneas_test::array_from_fn_closure::{core::ops::function::FnOnce<(usize), usize> for aeneas_test::array_from_fn_closure::closure}::call_once]:
    Source: 'src/lib.rs', lines 33:24-33:36 -/
def
  array_from_fn_closure.closure.Insts.CoreOpsFunctionFnOnceTupleUsizeUsize.call_once
  (c : array_from_fn_closure.closure) (i : Std.Usize) : Result Std.Usize := do
  let (i1, _) ←
    array_from_fn_closure.closure.Insts.CoreOpsFunctionFnMutTupleUsizeUsize.call_mut
      c i
  ok i1

/-- Trait implementation: [aeneas_test::array_from_fn_closure::{core::ops::function::FnOnce<(usize), usize> for aeneas_test::array_from_fn_closure::closure}]
    Source: 'src/lib.rs', lines 33:24-33:36 -/
@[reducible]
def array_from_fn_closure.closure.Insts.CoreOpsFunctionFnOnceTupleUsizeUsize :
  core.ops.function.FnOnce array_from_fn_closure.closure Std.Usize Std.Usize
  := {
  call_once :=
    array_from_fn_closure.closure.Insts.CoreOpsFunctionFnOnceTupleUsizeUsize.call_once
}

/-- Trait implementation: [aeneas_test::array_from_fn_closure::{core::ops::function::FnMut<(usize), usize> for aeneas_test::array_from_fn_closure::closure}]
    Source: 'src/lib.rs', lines 33:24-33:36 -/
@[reducible]
def array_from_fn_closure.closure.Insts.CoreOpsFunctionFnMutTupleUsizeUsize :
  core.ops.function.FnMut array_from_fn_closure.closure Std.Usize Std.Usize
  := {
  FnOnceInst :=
    array_from_fn_closure.closure.Insts.CoreOpsFunctionFnOnceTupleUsizeUsize
  call_mut :=
    array_from_fn_closure.closure.Insts.CoreOpsFunctionFnMutTupleUsizeUsize.call_mut
}

/-- [aeneas_test::array_from_fn_closure]:
    Source: 'src/lib.rs', lines 32:0-34:1
    Visibility: public -/
def array_from_fn_closure : Result (Array Std.Usize 10#usize) := do
  core.array.from_fn 10#usize
    array_from_fn_closure.closure.Insts.CoreOpsFunctionFnMutTupleUsizeUsize ()

/-- [aeneas_test::array_index_ref]:
    Source: 'src/lib.rs', lines 39:0-41:1
    Visibility: public -/
def array_index_ref
  (a : Array Std.U8 10#usize) (i : Std.Usize) : Result Std.U8 := do
  Array.index_usize a i

/-- [aeneas_test::array_index_val]:
    Source: 'src/lib.rs', lines 44:0-46:1
    Visibility: public -/
def array_index_val
  (a : Array Std.U32 4#usize) (i : Std.Usize) : Result Std.U32 := do
  Array.index_usize a i

/-- [aeneas_test::result_ok]:
    Source: 'src/lib.rs', lines 52:0-54:1
    Visibility: public -/
def result_ok
  (x : core.result.Result Std.U8 Std.U8) : Result (Option Std.U8) := do
  core.result.Result.ok x

/-- [aeneas_test::result_err]:
    Source: 'src/lib.rs', lines 57:0-59:1
    Visibility: public -/
def result_err
  (x : core.result.Result Std.U8 Std.U32) : Result (Option Std.U32) := do
  core.result.Result.err x

/-- [aeneas_test::result_is_ok]:
    Source: 'src/lib.rs', lines 63:0-65:1
    Visibility: public -/
def result_is_ok (x : core.result.Result Std.U8 Std.U8) : Result Bool := do
  core.result.Result.is_ok x

/-- [aeneas_test::result_is_err]:
    Source: 'src/lib.rs', lines 67:0-69:1
    Visibility: public -/
def result_is_err (x : core.result.Result Std.U8 Std.U8) : Result Bool := do
  core.result.Result.is_err x

/-- [aeneas_test::result_pattern]:
    Source: 'src/lib.rs', lines 73:0-78:1
    Visibility: public -/
def result_pattern (x : core.result.Result Std.U8 Std.U8) : Result Std.U8 := do
  match x with
  | core.result.Result.Ok v => ok v
  | core.result.Result.Err _ => ok 0#u8

/-- [aeneas_test::option_unwrap]:
    Source: 'src/lib.rs', lines 82:0-84:1
    Visibility: public -/
def option_unwrap (x : Option Std.U8) : Result Std.U8 := do
  core.option.Option.unwrap x

/-- [aeneas_test::option_unwrap_or]:
    Source: 'src/lib.rs', lines 86:0-88:1
    Visibility: public -/
def option_unwrap_or
  (x : Option Std.U8) (default : Std.U8) : Result Std.U8 := do
  ok (core.option.Option.unwrap_or x default)

/-- [aeneas_test::option_is_some]:
    Source: 'src/lib.rs', lines 90:0-92:1
    Visibility: public -/
def option_is_some (x : Option Std.U32) : Result Bool := do
  ok (core.option.Option.is_some x)

/-- [aeneas_test::option_is_none]:
    Source: 'src/lib.rs', lines 94:0-96:1
    Visibility: public -/
def option_is_none (x : Option Std.U32) : Result Bool := do
  ok (core.option.Option.is_none x)

/-- [aeneas_test::option_take]:
    Source: 'src/lib.rs', lines 98:0-100:1
    Visibility: public -/
def option_take
  (x : Option Std.U16) : Result ((Option Std.U16) × (Option Std.U16)) := do
  ok (core.option.Option.take x)

/-- [aeneas_test::option_pattern]:
    Source: 'src/lib.rs', lines 102:0-107:1
    Visibility: public -/
def option_pattern (x : Option Std.U8) : Result Std.U8 := do
  match x with
  | none => ok 0#u8
  | some v => ok v

/-- [aeneas_test::slice_len]:
    Source: 'src/lib.rs', lines 111:0-113:1
    Visibility: public -/
def slice_len (x : Slice Std.U8) : Result Std.Usize := do
  ok (Slice.len x)

/-- [aeneas_test::vec_new]:
    Source: 'src/lib.rs', lines 137:0-139:1
    Visibility: public -/
def vec_new : Result (alloc.vec.Vec Std.U32) := do
  ok (alloc.vec.Vec.new Std.U32)

/-- [aeneas_test::vec_with_capacity]:
    Source: 'src/lib.rs', lines 141:0-143:1
    Visibility: public -/
def vec_with_capacity (c : Std.Usize) : Result (alloc.vec.Vec Std.U8) := do
  ok (alloc.vec.Vec.with_capacity Std.U8 c)

/-- [aeneas_test::vec_push]:
    Source: 'src/lib.rs', lines 145:0-148:1
    Visibility: public -/
def vec_push
  (v : alloc.vec.Vec Std.U32) (x : Std.U32) :
  Result (alloc.vec.Vec Std.U32)
  := do
  alloc.vec.Vec.push v x

/-- [aeneas_test::vec_len]:
    Source: 'src/lib.rs', lines 150:0-152:1
    Visibility: public -/
def vec_len (v : alloc.vec.Vec Std.U32) : Result Std.Usize := do
  ok (alloc.vec.Vec.len v)

/-- [aeneas_test::vec_from_elem]:
    Source: 'src/lib.rs', lines 154:0-156:1
    Visibility: public -/
def vec_from_elem
  (x : Std.U32) (n : Std.Usize) : Result (alloc.vec.Vec Std.U32) := do
  alloc.vec.from_elem core.clone.CloneU32 x n

/-- [aeneas_test::call_fn]:
    Source: 'src/lib.rs', lines 162:0-164:1
    Visibility: public -/
def call_fn
  {F : Type} (coreopsfunctionFnFTupleU8U8Inst : core.ops.function.Fn F Std.U8
  Std.U8) (f : F) (x : Std.U8) :
  Result Std.U8
  := do
  coreopsfunctionFnFTupleU8U8Inst.call f x

/-- [aeneas_test::call_fn_mut]:
    Source: 'src/lib.rs', lines 166:0-168:1
    Visibility: public -/
def call_fn_mut
  {F : Type} (coreopsfunctionFnMutFTupleU8U8Inst : core.ops.function.FnMut F
  Std.U8 Std.U8) (f : F) (x : Std.U8) :
  Result Std.U8
  := do
  let (i, _) ← coreopsfunctionFnMutFTupleU8U8Inst.call_mut f x
  ok i

/-- [aeneas_test::range_sum]: loop body 0:
    Source: 'src/lib.rs', lines 174:4-176:5
    Visibility: public -/
@[rust_loop_body]
def range_sum_loop.body
  (iter : core.ops.range.Range Std.Usize) (acc : Std.Usize) :
  Result (ControlFlow ((core.ops.range.Range Std.Usize) × Std.Usize)
    Std.Usize)
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepUsize iter
  match o with
  | none => ok (done acc)
  | some i =>
    let acc1 ← lift (core.num.Usize.wrapping_add acc i)
    ok (cont (iter1, acc1))

/-- [aeneas_test::range_sum]: loop 0:
    Source: 'src/lib.rs', lines 174:4-176:5
    Visibility: public -/
@[rust_loop]
def range_sum_loop
  (iter : core.ops.range.Range Std.Usize) (acc : Std.Usize) :
  Result Std.Usize
  := do
  loop
    (fun (iter1, acc1) => range_sum_loop.body iter1 acc1)
    (iter, acc)

/-- [aeneas_test::range_sum]:
    Source: 'src/lib.rs', lines 172:0-178:1
    Visibility: public -/
@[reducible]
def range_sum (n : Std.Usize) : Result Std.Usize := do
  range_sum_loop { start := 0#usize, «end» := n } 0#usize

/-- [aeneas_test::add_u8]:
    Source: 'src/lib.rs', lines 182:0-184:1
    Visibility: public -/
def add_u8 (x : Std.U8) (y : Std.U8) : Result Std.U8 := do
  x + y

/-- [aeneas_test::sub_u32]:
    Source: 'src/lib.rs', lines 186:0-188:1
    Visibility: public -/
def sub_u32 (x : Std.U32) (y : Std.U32) : Result Std.U32 := do
  x - y

/-- [aeneas_test::lt_u8]:
    Source: 'src/lib.rs', lines 190:0-192:1
    Visibility: public -/
def lt_u8 (x : Std.U8) (y : Std.U8) : Result Bool := do
  ok (x < y)

/-- [aeneas_test::ge_usize]:
    Source: 'src/lib.rs', lines 194:0-196:1
    Visibility: public -/
def ge_usize (x : Std.Usize) (y : Std.Usize) : Result Bool := do
  ok (x >= y)

/-- [aeneas_test::xor_u64]:
    Source: 'src/lib.rs', lines 198:0-200:1
    Visibility: public -/
def xor_u64 (x : Std.U64) (y : Std.U64) : Result Std.U64 := do
  ok (x ^^^ y)

/-- [aeneas_test::mem_swap_u32]:
    Source: 'src/lib.rs', lines 204:0-206:1
    Visibility: public -/
def mem_swap_u32
  (a : Std.U32) (b : Std.U32) : Result (Std.U32 × Std.U32) := do
  ok (core.mem.swap a b)

/-- [aeneas_test::mem_replace_u8]:
    Source: 'src/lib.rs', lines 208:0-210:1
    Visibility: public -/
def mem_replace_u8
  (dst : Std.U8) (src : Std.U8) : Result (Std.U8 × Std.U8) := do
  ok (core.mem.replace dst src)

/-- [aeneas_test::clone_u64]:
    Source: 'src/lib.rs', lines 214:0-216:1
    Visibility: public -/
def clone_u64 (x : Std.U64) : Result Std.U64 := do
  ok (core.clone.impls.CloneU64.clone x)

/-- [aeneas_test::copy_u8]:
    Source: 'src/lib.rs', lines 218:0-220:1
    Visibility: public -/
def copy_u8 (x : Std.U8) : Result (Std.U8 × Std.U8) := do
  ok (x, x)

/-- [aeneas_test::box_new]:
    Source: 'src/lib.rs', lines 224:0-226:1
    Visibility: public -/
def box_new (x : Std.U32) : Result Std.U32 := do
  ok x

/-- [aeneas_test::box_deref]:
    Source: 'src/lib.rs', lines 228:0-230:1
    Visibility: public -/
def box_deref (b : Std.U8) : Result Std.U8 := do
  ok b

end aeneas_test
