-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [aeneas_test]: type definitions
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

noncomputable section

namespace aeneas_test

/-- [aeneas_test::array_from_fn_closure::closure]
    Source: 'src/lib.rs', lines 33:24-33:36 -/
@[reducible]
def array_from_fn_closure.closure := Unit

end aeneas_test
