-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [core_models_test_suite]: function definitions
import Aeneas
import TestSuite.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

noncomputable section

namespace core_models_test_suite

/-- [core_models_test_suite::opt_unwrap_or]:
    Source: 'src/lib.rs', lines 13:0-15:1
    Visibility: public -/
def opt_unwrap_or (x : Option Std.U8) (default : Std.U8) : Result Std.U8 := do
  ok (core.option.Option.unwrap_or x default)

/-- [core_models_test_suite::opt_is_some]:
    Source: 'src/lib.rs', lines 17:0-19:1
    Visibility: public -/
def opt_is_some (x : Option Std.U32) : Result Bool := do
  ok (core.option.Option.is_some x)

/-- [core_models_test_suite::opt_is_none]:
    Source: 'src/lib.rs', lines 21:0-23:1
    Visibility: public -/
def opt_is_none (x : Option Std.U32) : Result Bool := do
  ok (core.option.Option.is_none x)

/-- [core_models_test_suite::opt_take]:
    Source: 'src/lib.rs', lines 25:0-27:1
    Visibility: public -/
def opt_take
  (x : Option Std.U16) : Result ((Option Std.U16) × (Option Std.U16)) := do
  ok (core.option.Option.take x)

/-- [core_models_test_suite::mem_swap_u32]:
    Source: 'src/lib.rs', lines 31:0-33:1
    Visibility: public -/
def mem_swap_u32
  (a : Std.U32) (b : Std.U32) : Result (Std.U32 × Std.U32) := do
  ok (core.mem.swap a b)

/-- [core_models_test_suite::mem_replace_u8]:
    Source: 'src/lib.rs', lines 35:0-37:1
    Visibility: public -/
def mem_replace_u8
  (dst : Std.U8) (src : Std.U8) : Result (Std.U8 × Std.U8) := do
  ok (core.mem.replace dst src)

/-- [core_models_test_suite::add_u8]:
    Source: 'src/lib.rs', lines 41:0-43:1
    Visibility: public -/
def add_u8 (x : Std.U8) (y : Std.U8) : Result Std.U8 := do
  x + y

/-- [core_models_test_suite::sub_u32]:
    Source: 'src/lib.rs', lines 45:0-47:1
    Visibility: public -/
def sub_u32 (x : Std.U32) (y : Std.U32) : Result Std.U32 := do
  x - y

/-- [core_models_test_suite::mul_u16]:
    Source: 'src/lib.rs', lines 49:0-51:1
    Visibility: public -/
def mul_u16 (x : Std.U16) (y : Std.U16) : Result Std.U16 := do
  x * y

/-- [core_models_test_suite::lt_u8]:
    Source: 'src/lib.rs', lines 55:0-57:1
    Visibility: public -/
def lt_u8 (x : Std.U8) (y : Std.U8) : Result Bool := do
  ok (x < y)

/-- [core_models_test_suite::ge_usize]:
    Source: 'src/lib.rs', lines 59:0-61:1
    Visibility: public -/
def ge_usize (x : Std.Usize) (y : Std.Usize) : Result Bool := do
  ok (x >= y)

/-- [core_models_test_suite::opt_double]:
    Source: 'src/lib.rs', lines 65:0-70:1
    Visibility: public -/
def opt_double (x : Option Std.U8) : Result Std.U8 := do
  match x with
  | none => ok 0#u8
  | some v => ok (core.num.U8.wrapping_add v v)

/-- [core_models_test_suite::xor_u64]:
    Source: 'src/lib.rs', lines 74:0-76:1
    Visibility: public -/
def xor_u64 (x : Std.U64) (y : Std.U64) : Result Std.U64 := do
  ok (x ^^^ y)

/-- [core_models_test_suite::or_u32]:
    Source: 'src/lib.rs', lines 78:0-80:1
    Visibility: public -/
def or_u32 (x : Std.U32) (y : Std.U32) : Result Std.U32 := do
  ok (x ||| y)

/-- [core_models_test_suite::and_u8]:
    Source: 'src/lib.rs', lines 82:0-84:1
    Visibility: public -/
def and_u8 (x : Std.U8) (y : Std.U8) : Result Std.U8 := do
  ok (x &&& y)

/-- [core_models_test_suite::clone_u64]:
    Source: 'src/lib.rs', lines 88:0-90:1
    Visibility: public -/
def clone_u64 (x : Std.U64) : Result Std.U64 := do
  ok (core.clone.impls.CloneU64.clone x)

/-- [core_models_test_suite::copy_u8]:
    Source: 'src/lib.rs', lines 92:0-94:1
    Visibility: public -/
def copy_u8 (x : Std.U8) : Result (Std.U8 × Std.U8) := do
  ok (x, x)

/-- [core_models_test_suite::arr_index]:
    Source: 'src/lib.rs', lines 98:0-100:1
    Visibility: public -/
def arr_index
  (a : Array Std.U32 4#usize) (i : Std.Usize) : Result Std.U32 := do
  Array.index_usize a i

/-- [core_models_test_suite::arr_set]:
    Source: 'src/lib.rs', lines 102:0-105:1
    Visibility: public -/
def arr_set
  (a : Array Std.U32 4#usize) (i : Std.Usize) (x : Std.U32) :
  Result (Array Std.U32 4#usize)
  := do
  Array.update a i x

/-- [core_models_test_suite::arr_repeat]:
    Source: 'src/lib.rs', lines 107:0-109:1
    Visibility: public -/
def arr_repeat : Result (Array Std.U8 16#usize) := do
  ok (Array.repeat 16#usize 0#u8)

/-- [core_models_test_suite::range_sum]: loop body 0:
    Source: 'src/lib.rs', lines 117:4-119:5
    Visibility: public -/
@[rust_loop_body]
def range_sum_loop.body
  (iter : core.ops.range.Range Std.Usize) (acc : Std.Usize) :
  Result (ControlFlow ((core.ops.range.Range Std.Usize) × Std.Usize)
    Std.Usize)
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepUsize iter
  match o with
  | none => ok (done acc)
  | some i =>
    let acc1 ← lift (core.num.Usize.wrapping_add acc i)
    ok (cont (iter1, acc1))

/-- [core_models_test_suite::range_sum]: loop 0:
    Source: 'src/lib.rs', lines 117:4-119:5
    Visibility: public -/
@[rust_loop]
def range_sum_loop
  (iter : core.ops.range.Range Std.Usize) (acc : Std.Usize) :
  Result Std.Usize
  := do
  loop
    (fun (iter1, acc1) => range_sum_loop.body iter1 acc1)
    (iter, acc)

/-- [core_models_test_suite::range_sum]:
    Source: 'src/lib.rs', lines 115:0-121:1
    Visibility: public -/
@[reducible]
def range_sum (n : Std.Usize) : Result Std.Usize := do
  range_sum_loop { start := 0#usize, «end» := n } 0#usize

/-- [core_models_test_suite::ROUND_CONSTANTS]
    Source: 'src/lib.rs', lines 126:0-133:2
    Visibility: public -/
@[global_simps, irreducible]
def ROUND_CONSTANTS : Array Std.U64 24#usize :=
  Array.make 24#usize [
    1#u64, 32898#u64, 9223372036854808714#u64, 9223372039002292224#u64,
    32907#u64, 2147483649#u64, 9223372039002292353#u64,
    9223372036854808585#u64, 138#u64, 136#u64, 2147516425#u64, 2147483658#u64,
    2147516555#u64, 9223372036854775947#u64, 9223372036854808713#u64,
    9223372036854808579#u64, 9223372036854808578#u64, 9223372036854775936#u64,
    32778#u64, 9223372039002259466#u64, 9223372039002292353#u64,
    9223372036854808704#u64, 2147483649#u64, 9223372039002292232#u64
    ]

/-- [core_models_test_suite::arr_to_slice]:
    Source: 'src/lib.rs', lines 135:0-137:1
    Visibility: public -/
def arr_to_slice (a : Array Std.U32 4#usize) : Result (Slice Std.U32) := do
  ok (Array.to_slice a)

/-- [core_models_test_suite::vec_new_u32]:
    Source: 'src/lib.rs', lines 148:0-150:1
    Visibility: public -/
def vec_new_u32 : Result (alloc.vec.Vec Std.U32) := do
  ok (alloc.vec.Vec.new Std.U32)

/-- [core_models_test_suite::vec_with_capacity_u8]:
    Source: 'src/lib.rs', lines 152:0-154:1
    Visibility: public -/
def vec_with_capacity_u8 (c : Std.Usize) : Result (alloc.vec.Vec Std.U8) := do
  ok (alloc.vec.Vec.with_capacity Std.U8 c)

/-- [core_models_test_suite::vec_len_u32]:
    Source: 'src/lib.rs', lines 156:0-158:1
    Visibility: public -/
def vec_len_u32 (v : alloc.vec.Vec Std.U32) : Result Std.Usize := do
  ok (alloc.vec.Vec.len v)

/-- [core_models_test_suite::vec_push_one]:
    Source: 'src/lib.rs', lines 162:0-165:1
    Visibility: public -/
def vec_push_one
  (v : alloc.vec.Vec Std.U32) (x : Std.U32) :
  Result (alloc.vec.Vec Std.U32)
  := do
  alloc.vec.Vec.push v x

/-- [core_models_test_suite::vec_push_two]:
    Source: 'src/lib.rs', lines 167:0-171:1
    Visibility: public -/
def vec_push_two
  (v : alloc.vec.Vec Std.U8) (x : Std.U8) (y : Std.U8) :
  Result (alloc.vec.Vec Std.U8)
  := do
  let v1 ← alloc.vec.Vec.push v x
  alloc.vec.Vec.push v1 y

/-- [core_models_test_suite::vec_insert_u8]:
    Source: 'src/lib.rs', lines 173:0-176:1
    Visibility: public -/
def vec_insert_u8
  (v : alloc.vec.Vec Std.U8) (i : Std.Usize) (x : Std.U8) :
  Result (alloc.vec.Vec Std.U8)
  := do
  alloc.vec.Vec.insert v i x

/-- [core_models_test_suite::vec_extend_from_slice_u8]:
    Source: 'src/lib.rs', lines 178:0-181:1
    Visibility: public -/
def vec_extend_from_slice_u8
  (v : alloc.vec.Vec Std.U8) (s : Slice Std.U8) :
  Result (alloc.vec.Vec Std.U8)
  := do
  alloc.vec.Vec.extend_from_slice core.clone.CloneU8 v s

/-- [core_models_test_suite::vec_from_elem_u32]:
    Source: 'src/lib.rs', lines 187:0-189:1
    Visibility: public -/
def vec_from_elem_u32
  (x : Std.U32) (n : Std.Usize) : Result (alloc.vec.Vec Std.U32) := do
  alloc.vec.from_elem core.clone.CloneU32 x n

/-- [core_models_test_suite::slice_to_vec_u8]:
    Source: 'src/lib.rs', lines 195:0-197:1
    Visibility: public -/
def slice_to_vec_u8 (s : Slice Std.U8) : Result (alloc.vec.Vec Std.U8) := do
  alloc.slice.Dummy.to_vec core.clone.CloneU8 s

/-- [core_models_test_suite::box_new_u32]:
    Source: 'src/lib.rs', lines 204:0-206:1
    Visibility: public -/
def box_new_u32 (x : Std.U32) : Result Std.U32 := do
  ok x

/-- [core_models_test_suite::box_deref_u8]:
    Source: 'src/lib.rs', lines 208:0-210:1
    Visibility: public -/
def box_deref_u8 (b : Std.U8) : Result Std.U8 := do
  ok b

end core_models_test_suite
