-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [core_models_test_suite]: type definitions
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

noncomputable section

namespace core_models_test_suite

end core_models_test_suite
