-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [alloc]: function definitions
import Aeneas
import CoreModels.Core.TypesPrologue
import CoreModels.Core.Types
import CoreModels.RustPrimitives.Types
import CoreModels.Alloc.Types
import CoreModels.RustPrimitives.Funs
import CoreModels.Core.Funs
-- (alloc-side externals live in parent CoreModels.RustPrimitives)
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace CoreModels.alloc

/-- [alloc::alloc::{impl core::clone::Clone for alloc::alloc::Global}::clone]:
    Source: 'src/lib.rs', lines 15:13-15:18
    Visibility: public -/
def alloc.Global.Insts.CoreCloneClone.clone
  (self : alloc.Global) : Result alloc.Global := do
  ok ()

/-- Trait implementation: [alloc::alloc::{impl core::clone::Clone for alloc::alloc::Global}]
    Source: 'src/lib.rs', lines 15:13-15:18 -/
@[reducible]
def alloc.Global.Insts.CoreCloneClone : core.clone.Clone alloc.Global := {
  clone := alloc.Global.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [alloc::alloc::{impl alloc::alloc::Allocator for alloc::alloc::Global}]
    Source: 'src/lib.rs', lines 18:4-18:32 -/
@[reducible]
def alloc.Global.Insts.AllocAllocAllocator : alloc.Allocator
  alloc.Global := {
}

/-- [alloc::borrow::{impl alloc::borrow::ToOwned for T}::to_owned]:
    Source: 'src/lib.rs', lines 28:8-30:9
    Visibility: public -/
def borrow.ToOwned.Blanket.to_owned {T : Type} (self : T) : Result T := do
  ok self

/-- Trait implementation: [alloc::borrow::{impl alloc::borrow::ToOwned for T}]
    Source: 'src/lib.rs', lines 27:4-31:5 -/
@[reducible]
def borrow.ToOwned.Blanket (T : Type) : borrow.ToOwned T := {
  to_owned := borrow.ToOwned.Blanket.to_owned
}

/-- [alloc::boxed::{alloc::boxed::Box<T>}::new]:
    Source: 'src/lib.rs', lines 38:8-40:9 -/
def boxed.Box.new {T : Type} (v : T) : Result T := do
  ok v

/-- [alloc::collections::btree::set::{alloc::collections::btree::set::BTreeSet<T, U>}::new]:
    Source: 'src/lib.rs', lines 185:16-187:17 -/
def collections.btree.set.BTreeSet.new
  (T : Type) (U : Type) : Result (collections.btree.set.BTreeSet T U) := do
  ok (core.option.Option.None, core.option.Option.None)

/-- [alloc::collections::vec_deque::{alloc::collections::vec_deque::VecDeque<T, A>}::push_back]:
    Source: 'src/lib.rs', lines 203:12-203:44 -/
def collections.vec_deque.VecDeque.push_back
  {T : Type} {A : Type} (self : collections.vec_deque.VecDeque T A) (x : T) :
  Result (collections.vec_deque.VecDeque T A)
  := do
  ok self

/-- [alloc::collections::vec_deque::{alloc::collections::vec_deque::VecDeque<T, A>}::len]:
    Source: 'src/lib.rs', lines 204:12-206:13 -/
def collections.vec_deque.VecDeque.len
  {T : Type} {A : Type} (self : collections.vec_deque.VecDeque T A) :
  Result Std.Usize
  := do
  let (s, _) := self
  rust_primitives.sequence.seq_len s

/-- [alloc::collections::vec_deque::{alloc::collections::vec_deque::VecDeque<T, A>}::pop_front]:
    Source: 'src/lib.rs', lines 207:12-213:13 -/
def collections.vec_deque.VecDeque.pop_front
  {T : Type} {A : Type} (self : collections.vec_deque.VecDeque T A) :
  Result ((core.option.Option T) × (collections.vec_deque.VecDeque T A))
  := do
  let i ← collections.vec_deque.VecDeque.len self
  if i = 0#usize
  then ok (core.option.Option.None, self)
  else
    let (s, pd) := self
    let (t, s1) ← rust_primitives.sequence.seq_remove s 0#usize
    ok (core.option.Option.Some t, (s1, pd))

/-- [alloc::collections::vec_deque::{impl core::ops::index::Index<usize, T> for alloc::collections::vec_deque::VecDeque<T, A>}::index]:
    Source: 'src/lib.rs', lines 220:12-222:13
    Visibility: public -/
def collections.vec_deque.VecDeque.Insts.CoreOpsIndexIndexUsizeT.index
  {T : Type} {A : Type} (self : collections.vec_deque.VecDeque T A)
  (i : Std.Usize) :
  Result T
  := do
  let (s, _) := self
  rust_primitives.sequence.seq_index s i

/-- Trait implementation: [alloc::collections::vec_deque::{impl core::ops::index::Index<usize, T> for alloc::collections::vec_deque::VecDeque<T, A>}]
    Source: 'src/lib.rs', lines 217:8-223:9 -/
@[reducible]
def collections.vec_deque.VecDeque.Insts.CoreOpsIndexIndexUsizeT (T : Type) (A
  : Type) : core.ops.index.Index (collections.vec_deque.VecDeque T A) Std.Usize
  T := {
  index := collections.vec_deque.VecDeque.Insts.CoreOpsIndexIndexUsizeT.index
}

/-- [alloc::collections::vec_deque::into_iter::{impl core::iter::traits::iterator::Iterator<T> for alloc::collections::vec_deque::into_iter::IntoIter<T, A>}::next]:
    Source: 'src/lib.rs', lines 230:16-236:17
    Visibility: public -/
def
  collections.vec_deque.into_iter.IntoIter.Insts.CoreIterTraitsIteratorIterator.next
  {T : Type} {A : Type} (self : collections.vec_deque.into_iter.IntoIter T A) :
  Result ((core.option.Option T) × (collections.vec_deque.into_iter.IntoIter T
    A))
  := do
  let (s, pd) := self
  let i ← rust_primitives.sequence.seq_len s
  if i = 0#usize
  then ok (core.option.Option.None, self)
  else
    let (t, s1) ← rust_primitives.sequence.seq_remove s 0#usize
    ok (core.option.Option.Some t, (s1, pd))

/-- Trait implementation: [alloc::collections::vec_deque::into_iter::{impl core::iter::traits::iterator::Iterator<T> for alloc::collections::vec_deque::into_iter::IntoIter<T, A>}]
    Source: 'src/lib.rs', lines 228:12-237:13 -/
@[reducible]
def
  collections.vec_deque.into_iter.IntoIter.Insts.CoreIterTraitsIteratorIterator
  (T : Type) (A : Type) : core.iter.traits.iterator.Iterator
  (collections.vec_deque.into_iter.IntoIter T A) T := {
  next :=
    collections.vec_deque.into_iter.IntoIter.Insts.CoreIterTraitsIteratorIterator.next
}

/-- [alloc::collections::vec_deque::{impl core::iter::traits::collect::IntoIterator<T, alloc::collections::vec_deque::into_iter::IntoIter<T, A>> for alloc::collections::vec_deque::VecDeque<T, A>}::into_iter]:
    Source: 'src/lib.rs', lines 243:12-245:13
    Visibility: public -/
def
  collections.vec_deque.VecDeque.Insts.CoreIterTraitsCollectIntoIteratorTIntoIter.into_iter
  {T : Type} {A : Type} (self : collections.vec_deque.VecDeque T A) :
  Result (collections.vec_deque.into_iter.IntoIter T A)
  := do
  let (s, _) := self
  ok (s, core.marker.PhantomData.mk)

/-- Trait implementation: [alloc::collections::vec_deque::{impl core::iter::traits::collect::IntoIterator<T, alloc::collections::vec_deque::into_iter::IntoIter<T, A>> for alloc::collections::vec_deque::VecDeque<T, A>}]
    Source: 'src/lib.rs', lines 240:8-246:9 -/
@[reducible]
def
  collections.vec_deque.VecDeque.Insts.CoreIterTraitsCollectIntoIteratorTIntoIter
  (T : Type) (A : Type) : core.iter.traits.collect.IntoIterator
  (collections.vec_deque.VecDeque T A) T
  (collections.vec_deque.into_iter.IntoIter T A) := {
  into_iter :=
    collections.vec_deque.VecDeque.Insts.CoreIterTraitsCollectIntoIteratorTIntoIter.into_iter
}

/-- [alloc::fmt::format]:
    Source: 'src/lib.rs', lines 275:4-277:5 -/
def fmt.format (args : core.fmt.Arguments) : Result alloc.string.String := do
  alloc.string.String.new

/-- [alloc::slice::{alloc::slice::Dummy<T>}::to_vec]:
    Source: 'src/lib.rs', lines 288:8-295:9 -/
def slice.Dummy.to_vec
  {T : Type} (corecloneCloneInst : core.clone.Clone T) (s : Slice T) :
  Result (vec.Vec T)
  := do
  let seq ← rust_primitives.sequence.seq_empty T
  let seq1 ← rust_primitives.sequence.seq_extend corecloneCloneInst seq s
  ok seq1

/-- [alloc::slice::{alloc::slice::Dummy<T>}::into_vec]:
    Source: 'src/lib.rs', lines 296:8-298:9 -/
def slice.Dummy.into_vec {T : Type} (s : Slice T) : Result (vec.Vec T) := do
  let s1 ← rust_primitives.sequence.seq_from_boxed_slice s
  ok s1

/-- [alloc::vec::{alloc::vec::Vec<T>}::as_slice]:
    Source: 'src/lib.rs', lines 488:8-490:9
    Visibility: public -/
def vec.Vec.as_slice {T : Type} (self : vec.Vec T) : Result (Slice T) := do
  rust_primitives.sequence.seq_to_slice self

/-- [alloc::vec::{impl core::ops::deref::Deref<[T]> for alloc::vec::Vec<T>}::deref]:
    Source: 'src/lib.rs', lines 579:8-581:9
    Visibility: public -/
def vec.Vec.Insts.CoreOpsDerefDerefSlice.deref
  {T : Type} (self : vec.Vec T) : Result (Slice T) := do
  vec.Vec.as_slice self

/-- [alloc::vec::{impl core::clone::Clone for alloc::vec::Vec<T>}::clone]: loop body 0:
    Source: 'src/lib.rs', lines 394:12-396:13
    Visibility: public -/
@[rust_loop_body]
def vec.Vec.Insts.CoreCloneClone.clone_loop.body
  {T : Type} (corecloneCloneInst : core.clone.Clone T)
  (iter_ : core.slice.iter.Iter T) (new_vec : rust_primitives.sequence.Seq T) :
  Result (ControlFlow ((core.slice.iter.Iter T) ×
    (rust_primitives.sequence.Seq T)) (rust_primitives.sequence.Seq T))
  := do
  let (o, iter1) ←
    core.slice.iter.Iter.Insts.CoreIterTraitsIteratorIteratorSharedAT.next iter_
  match o with
  | core.option.Option.None => ok (done new_vec)
  | core.option.Option.Some it =>
    let t ← corecloneCloneInst.clone it
    let new_vec1 ← rust_primitives.sequence.seq_push new_vec t
    ok (cont (iter1, new_vec1))

/-- [alloc::vec::{impl core::clone::Clone for alloc::vec::Vec<T>}::clone]: loop 0:
    Source: 'src/lib.rs', lines 394:12-396:13
    Visibility: public -/
@[rust_loop]
def vec.Vec.Insts.CoreCloneClone.clone_loop
  {T : Type} (corecloneCloneInst : core.clone.Clone T)
  (iter_ : core.slice.iter.Iter T) (new_vec : rust_primitives.sequence.Seq T) :
  Result (rust_primitives.sequence.Seq T)
  := do
  loop
    (fun (iter1, new_vec1) => vec.Vec.Insts.CoreCloneClone.clone_loop.body
      corecloneCloneInst iter1 new_vec1)
    (iter_, new_vec)

/-- [alloc::vec::{impl core::clone::Clone for alloc::vec::Vec<T>}::clone]:
    Source: 'src/lib.rs', lines 392:8-398:9
    Visibility: public -/
def vec.Vec.Insts.CoreCloneClone.clone
  {T : Type} (corecloneCloneInst : core.clone.Clone T) (self : vec.Vec T) :
  Result (vec.Vec T)
  := do
  let new_vec ← rust_primitives.sequence.seq_empty T
  let s ← vec.Vec.Insts.CoreOpsDerefDerefSlice.deref self
  let iter ← core.slice.Slice.iter s
  let new_vec1 ←
    vec.Vec.Insts.CoreCloneClone.clone_loop corecloneCloneInst iter new_vec
  ok new_vec1

/-- Trait implementation: [alloc::vec::{impl core::clone::Clone for alloc::vec::Vec<T>}]
    Source: 'src/lib.rs', lines 391:4-399:5 -/
@[reducible]
def vec.Vec.Insts.CoreCloneClone {T : Type} (corecloneCloneInst :
  core.clone.Clone T) : core.clone.Clone (vec.Vec T) := {
  clone := vec.Vec.Insts.CoreCloneClone.clone corecloneCloneInst
}

/-- [alloc::vec::{impl core::ops::index::Index<I, Clause0_Output> for alloc::vec::Vec<T>}::index]:
    Source: 'src/lib.rs', lines 570:8-572:9
    Visibility: public -/
def vec.Vec.Insts.CoreOpsIndexIndex.index
  {T : Type} {I : Type} {Clause0_Output : Type}
  (coresliceindexSliceIndexISliceClause0_OutputInst :
  core.slice.index.SliceIndex I (Slice T) Clause0_Output) (self : vec.Vec T)
  (i : I) :
  Result Clause0_Output
  := do
  let s ← vec.Vec.Insts.CoreOpsDerefDerefSlice.deref self
  core.Slice.Insts.CoreOpsIndexIndex.index
    coresliceindexSliceIndexISliceClause0_OutputInst s i

/-- [alloc::vec::{alloc::vec::Vec<T>}::len]:
    Source: 'src/lib.rs', lines 462:8-464:9
    Visibility: public -/
def vec.Vec.len {T : Type} (self : vec.Vec T) : Result Std.Usize := do
  rust_primitives.sequence.seq_len self

/-- [alloc::vec::{impl core::cmp::PartialEq<alloc::vec::Vec<U>> for alloc::vec::Vec<T>}::eq]: loop body 0:
    Source: 'src/lib.rs', lines 409:16-413:17
    Visibility: public -/
@[rust_loop_body]
def vec.Vec.Insts.CoreCmpPartialEqVec.eq_loop.body
  {T : Type} {U : Type} (corecmpPartialEqInst : core.cmp.PartialEq T U)
  (self : vec.Vec T) (other : vec.Vec U)
  (iter_ : core.ops.range.Range Std.Usize) (res : Bool) :
  Result (ControlFlow ((core.ops.range.Range Std.Usize) × Bool) Bool)
  := do
  let (o, iter1) ←
    core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.next
      core.Usize.Insts.CoreIterRangeStep iter_
  match o with
  | core.option.Option.None => ok (done res)
  | core.option.Option.Some i =>
    let t ←
      vec.Vec.Insts.CoreOpsIndexIndex.index
        (core.Usize.Insts.CoreSliceIndexSliceIndexSliceT T) self i
    let t1 ←
      vec.Vec.Insts.CoreOpsIndexIndex.index
        (core.Usize.Insts.CoreSliceIndexSliceIndexSliceT U) other i
    let b ← corecmpPartialEqInst.eq t t1
    if b
    then ok (cont (iter1, res))
    else ok (cont (iter1, false))

/-- [alloc::vec::{impl core::cmp::PartialEq<alloc::vec::Vec<U>> for alloc::vec::Vec<T>}::eq]: loop 0:
    Source: 'src/lib.rs', lines 409:16-413:17
    Visibility: public -/
@[rust_loop]
def vec.Vec.Insts.CoreCmpPartialEqVec.eq_loop
  {T : Type} {U : Type} (corecmpPartialEqInst : core.cmp.PartialEq T U)
  (iter_ : core.ops.range.Range Std.Usize) (self : vec.Vec T)
  (other : vec.Vec U) (res : Bool) :
  Result Bool
  := do
  loop
    (fun (iter1, res1) => vec.Vec.Insts.CoreCmpPartialEqVec.eq_loop.body
      corecmpPartialEqInst self other iter1 res1)
    (iter_, res)

/-- [alloc::vec::{impl core::cmp::PartialEq<alloc::vec::Vec<U>> for alloc::vec::Vec<T>}::eq]:
    Source: 'src/lib.rs', lines 404:8-416:9
    Visibility: public -/
def vec.Vec.Insts.CoreCmpPartialEqVec.eq
  {T : Type} {U : Type} (corecmpPartialEqInst : core.cmp.PartialEq T U)
  (self : vec.Vec T) (other : vec.Vec U) :
  Result Bool
  := do
  let i ← vec.Vec.len self
  let i1 ← vec.Vec.len other
  if i = i1
  then
    vec.Vec.Insts.CoreCmpPartialEqVec.eq_loop corecmpPartialEqInst
      { start := 0#usize, «end» := i } self other true
  else ok false

/-- Trait implementation: [alloc::vec::{impl core::cmp::PartialEq<alloc::vec::Vec<U>> for alloc::vec::Vec<T>}]
    Source: 'src/lib.rs', lines 400:4-417:5 -/
@[reducible]
def vec.Vec.Insts.CoreCmpPartialEqVec {T : Type} {U : Type}
  (corecmpPartialEqInst : core.cmp.PartialEq T U) : core.cmp.PartialEq (vec.Vec
  T) (vec.Vec U) := {
  eq := vec.Vec.Insts.CoreCmpPartialEqVec.eq corecmpPartialEqInst
}

/-- [alloc::vec::into_iter::{impl core::iter::traits::iterator::Iterator<T> for alloc::vec::into_iter::IntoIter<T>}::next]:
    Source: 'src/lib.rs', lines 428:12-434:13
    Visibility: public -/
def vec.into_iter.IntoIter.Insts.CoreIterTraitsIteratorIterator.next
  {T : Type} (self : vec.into_iter.IntoIter T) :
  Result ((core.option.Option T) × (vec.into_iter.IntoIter T))
  := do
  let i ← rust_primitives.sequence.seq_len self
  if i = 0#usize
  then ok (core.option.Option.None, self)
  else
    let (t, s) ← rust_primitives.sequence.seq_remove self 0#usize
    ok (core.option.Option.Some t, s)

/-- Trait implementation: [alloc::vec::into_iter::{impl core::iter::traits::iterator::Iterator<T> for alloc::vec::into_iter::IntoIter<T>}]
    Source: 'src/lib.rs', lines 426:8-435:9 -/
@[reducible]
def vec.into_iter.IntoIter.Insts.CoreIterTraitsIteratorIterator (T : Type) :
  core.iter.traits.iterator.Iterator (vec.into_iter.IntoIter T) T := {
  next := vec.into_iter.IntoIter.Insts.CoreIterTraitsIteratorIterator.next
}

/-- [alloc::vec::{impl core::iter::traits::collect::IntoIterator<T, alloc::vec::into_iter::IntoIter<T>> for alloc::vec::Vec<T>}::into_iter]:
    Source: 'src/lib.rs', lines 441:8-443:9
    Visibility: public -/
def vec.Vec.Insts.CoreIterTraitsCollectIntoIteratorTIntoIter.into_iter
  {T : Type} (self : vec.Vec T) : Result (vec.into_iter.IntoIter T) := do
  ok self

/-- Trait implementation: [alloc::vec::{impl core::iter::traits::collect::IntoIterator<T, alloc::vec::into_iter::IntoIter<T>> for alloc::vec::Vec<T>}]
    Source: 'src/lib.rs', lines 438:4-444:5 -/
@[reducible]
def vec.Vec.Insts.CoreIterTraitsCollectIntoIteratorTIntoIter (T : Type) :
  core.iter.traits.collect.IntoIterator (vec.Vec T) T (vec.into_iter.IntoIter
  T) := {
  into_iter :=
    vec.Vec.Insts.CoreIterTraitsCollectIntoIteratorTIntoIter.into_iter
}

/-- [alloc::vec::from_elem]:
    Source: 'src/lib.rs', lines 446:4-448:5 -/
def vec.from_elem
  {T : Type} (corecloneCloneInst : core.clone.Clone T) (item : T)
  (len : Std.Usize) :
  Result (vec.Vec T)
  := do
  let s ← rust_primitives.sequence.seq_create corecloneCloneInst item len
  ok s

/-- [alloc::vec::{alloc::vec::Vec<T>}::new]:
    Source: 'src/lib.rs', lines 452:8-454:9
    Visibility: public -/
def vec.Vec.new (T : Type) : Result (vec.Vec T) := do
  let s ← rust_primitives.sequence.seq_empty T
  ok s

/-- [alloc::vec::{alloc::vec::Vec<T>}::with_capacity]:
    Source: 'src/lib.rs', lines 455:8-457:9
    Visibility: public -/
def vec.Vec.with_capacity
  (T : Type) (_c : Std.Usize) : Result (vec.Vec T) := do
  vec.Vec.new T

/-- [alloc::vec::{alloc::vec::Vec<T>}::push]:
    Source: 'src/lib.rs', lines 466:8-468:9
    Visibility: public -/
def vec.Vec.push
  {T : Type} (self : vec.Vec T) (x : T) : Result (vec.Vec T) := do
  let s ← rust_primitives.sequence.seq_push self x
  ok s

/-- [alloc::vec::{alloc::vec::Vec<T>}::pop]:
    Source: 'src/lib.rs', lines 469:8-477:9
    Visibility: public -/
def vec.Vec.pop
  {T : Type} (self : vec.Vec T) :
  Result ((core.option.Option T) × (vec.Vec T))
  := do
  let l ← rust_primitives.sequence.seq_len self
  if l > 0#usize
  then
    let i ← l - 1#usize
    let (last, s) ← rust_primitives.sequence.seq_remove self i
    ok (core.option.Option.Some last, s)
  else ok (core.option.Option.None, self)

/-- [alloc::vec::{alloc::vec::Vec<T>}::is_empty]:
    Source: 'src/lib.rs', lines 478:8-480:9
    Visibility: public -/
def vec.Vec.is_empty {T : Type} (self : vec.Vec T) : Result Bool := do
  let i ← rust_primitives.sequence.seq_len self
  ok (i = 0#usize)

/-- [alloc::vec::{alloc::vec::Vec<T>}::insert]:
    Source: 'src/lib.rs', lines 482:8-487:9
    Visibility: public -/
def vec.Vec.insert
  {T : Type} (self : vec.Vec T) (index : Std.Usize) (element : T) :
  Result (vec.Vec T)
  := do
  let l ← rust_primitives.sequence.seq_len self
  let (right, s) ← rust_primitives.sequence.seq_drain self index l
  let s1 ← rust_primitives.sequence.seq_push s element
  let (s2, _) ← rust_primitives.sequence.seq_concat s1 right
  ok s2

/-- [alloc::vec::{alloc::vec::Vec<T>}::truncate]:
    Source: 'src/lib.rs', lines 492:8-492:47
    Visibility: public -/
def vec.Vec.truncate
  {T : Type} (self : vec.Vec T) (n : Std.Usize) : Result (vec.Vec T) := do
  ok self

/-- [alloc::vec::{alloc::vec::Vec<T>}::swap_remove]:
    Source: 'src/lib.rs', lines 494:8-496:9
    Visibility: public -/
def vec.Vec.swap_remove
  {T : Type} (self : vec.Vec T) (n : Std.Usize) :
  Result (T × (vec.Vec T))
  := do
  let (t, s) ← rust_primitives.sequence.seq_remove self n
  ok (t, s)

/-- [alloc::vec::{alloc::vec::Vec<T>}::resize]:
    Source: 'src/lib.rs', lines 499:8-503:9
    Visibility: public -/
def vec.Vec.resize
  {T : Type} (corecloneCloneInst : core.clone.Clone T) (self : vec.Vec T)
  (new_size : Std.Usize) (value : T) :
  Result (vec.Vec T)
  := do
  ok self

/-- [alloc::vec::{alloc::vec::Vec<T>}::remove]:
    Source: 'src/lib.rs', lines 505:8-507:9
    Visibility: public -/
def vec.Vec.remove
  {T : Type} (self : vec.Vec T) (index : Std.Usize) :
  Result (T × (vec.Vec T))
  := do
  let (t, s) ← rust_primitives.sequence.seq_remove self index
  ok (t, s)

/-- [alloc::vec::{alloc::vec::Vec<T>}::clear]:
    Source: 'src/lib.rs', lines 509:8-509:34
    Visibility: public -/
def vec.Vec.clear {T : Type} (self : vec.Vec T) : Result (vec.Vec T) := do
  ok self

/-- [alloc::vec::{alloc::vec::Vec<T>}::append]:
    Source: 'src/lib.rs', lines 511:8-514:9
    Visibility: public -/
def vec.Vec.append
  {T : Type} (self : vec.Vec T) (other : vec.Vec T) :
  Result ((vec.Vec T) × (vec.Vec T))
  := do
  let (s, _) ← rust_primitives.sequence.seq_concat self other
  let s1 ← rust_primitives.sequence.seq_empty T
  ok (s, s1)

/-- [alloc::vec::{alloc::vec::Vec<T>}::drain]:
    Source: 'src/lib.rs', lines 516:8-525:9
    Visibility: public -/
def vec.Vec.drain
  {T : Type} {R : Type} (self : vec.Vec T) (_range : R) :
  Result ((vec.drain.Drain T alloc.Global) × (vec.Vec T))
  := do
  let l ← rust_primitives.sequence.seq_len self
  let (s, s1) ← rust_primitives.sequence.seq_drain self 0#usize l
  ok ((s, core.marker.PhantomData.mk), s1)

/-- [alloc::vec::drain::{impl core::iter::traits::iterator::Iterator<T> for alloc::vec::drain::Drain<T, A>}::next]:
    Source: 'src/lib.rs', lines 532:12-539:13
    Visibility: public -/
def vec.drain.Drain.Insts.CoreIterTraitsIteratorIterator.next
  {T : Type} {A : Type} (self : vec.drain.Drain T A) :
  Result ((core.option.Option T) × (vec.drain.Drain T A))
  := do
  let (s, pd) := self
  let i ← rust_primitives.sequence.seq_len s
  if i = 0#usize
  then ok (core.option.Option.None, self)
  else
    let (res, s1) ← rust_primitives.sequence.seq_remove s 0#usize
    ok (core.option.Option.Some res, (s1, pd))

/-- Trait implementation: [alloc::vec::drain::{impl core::iter::traits::iterator::Iterator<T> for alloc::vec::drain::Drain<T, A>}]
    Source: 'src/lib.rs', lines 530:8-540:9 -/
@[reducible]
def vec.drain.Drain.Insts.CoreIterTraitsIteratorIterator (T : Type) (A : Type)
  : core.iter.traits.iterator.Iterator (vec.drain.Drain T A) T := {
  next := vec.drain.Drain.Insts.CoreIterTraitsIteratorIterator.next
}

/-- [alloc::vec::{alloc::vec::Vec<T>}::extend_from_slice]:
    Source: 'src/lib.rs', lines 546:8-548:9 -/
def vec.Vec.extend_from_slice
  {T : Type} (corecloneCloneInst : core.clone.Clone T) (self : vec.Vec T)
  (other : Slice T) :
  Result (vec.Vec T)
  := do
  let s ← rust_primitives.sequence.seq_extend corecloneCloneInst self other
  ok s

/-- Trait implementation: [alloc::vec::{impl core::ops::index::Index<I, Clause0_Output> for alloc::vec::Vec<T>}]
    Source: 'src/lib.rs', lines 564:4-573:5 -/
@[reducible]
def vec.Vec.Insts.CoreOpsIndexIndex {T : Type} {I : Type} {Clause0_Output :
  Type} (coresliceindexSliceIndexISliceClause0_OutputInst :
  core.slice.index.SliceIndex I (Slice T) Clause0_Output) :
  core.ops.index.Index (vec.Vec T) I Clause0_Output := {
  index := vec.Vec.Insts.CoreOpsIndexIndex.index
    coresliceindexSliceIndexISliceClause0_OutputInst
}

/-- Trait implementation: [alloc::vec::{impl core::ops::deref::Deref<[T]> for alloc::vec::Vec<T>}]
    Source: 'src/lib.rs', lines 576:4-582:5 -/
@[reducible]
def vec.Vec.Insts.CoreOpsDerefDerefSlice (T : Type) : core.ops.deref.Deref
  (vec.Vec T) (Slice T) := {
  deref := vec.Vec.Insts.CoreOpsDerefDerefSlice.deref
}

end CoreModels.alloc
