-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [alloc]: function definitions
import CoreModels.TypesPrologue
import CoreModels.Types
import CoreModels.TypesExternal
import CoreModels.Alloc.Types
import CoreModels.FunsExternal
import CoreModels.Funs
-- (alloc-side externals live in parent Aeneas.FunsExternal)
open Aeneas
open Aeneas.Std hiding namespace core alloc
open Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace CoreModels.alloc

/-- [alloc::borrow::{alloc::borrow::ToOwned for T}::to_owned]:
    Source: 'src/lib.rs', lines 23:8-25:9
    Visibility: public -/
def borrow.ToOwned.Blanket.to_owned {T : Type} (self : T) : Result T := do
  ok self

/-- Trait implementation: [alloc::borrow::{alloc::borrow::ToOwned for T}]
    Source: 'src/lib.rs', lines 22:4-26:5 -/
@[reducible]
def borrow.ToOwned.Blanket (T : Type) : borrow.ToOwned T := {
  to_owned := borrow.ToOwned.Blanket.to_owned
}

/-- [alloc::boxed::{alloc::boxed::Box<T>}::new]:
    Source: 'src/lib.rs', lines 33:8-35:9 -/
def boxed.Box.new {T : Type} (v : T) : Result T := do
  ok v

/-- [alloc::collections::btree::set::{alloc::collections::btree::set::BTreeSet<T, U>}::new]:
    Source: 'src/lib.rs', lines 180:16-182:17 -/
def collections.btree.set.BTreeSet.new
  (T : Type) (U : Type) : Result (collections.btree.set.BTreeSet T U) := do
  ok (none, none)

/-- [alloc::collections::vec_deque::{alloc::collections::vec_deque::VecDeque<T, A>}::push_back]:
    Source: 'src/lib.rs', lines 198:12-198:44 -/
def collections.vec_deque.VecDeque.push_back
  {T : Type} (self : collections.vec_deque.VecDeque T A) (x : T) :
  Result (collections.vec_deque.VecDeque T A)
  := do
  ok self

/-- [alloc::collections::vec_deque::{alloc::collections::vec_deque::VecDeque<T, A>}::len]:
    Source: 'src/lib.rs', lines 199:12-201:13 -/
def collections.vec_deque.VecDeque.len
  {T : Type} (self : collections.vec_deque.VecDeque T A) :
  Result Std.Usize
  := do
  let (s, _) := self
  rust_primitives.sequence.seq_len s

/-- [alloc::collections::vec_deque::{alloc::collections::vec_deque::VecDeque<T, A>}::pop_front]:
    Source: 'src/lib.rs', lines 202:12-208:13 -/
def collections.vec_deque.VecDeque.pop_front
  {T : Type} (self : collections.vec_deque.VecDeque T A) :
  Result ((Option T) × (collections.vec_deque.VecDeque T A))
  := do
  let i ← collections.vec_deque.VecDeque.len self
  if i = 0#usize
  then ok (none, self)
  else
    let (s, pd) := self
    let (t, s1) ← rust_primitives.sequence.seq_remove s 0#usize
    ok (some t, (s1, pd))

/-- [alloc::collections::vec_deque::{core::ops::index::Index<usize, T> for alloc::collections::vec_deque::VecDeque<T, A>}::index]:
    Source: 'src/lib.rs', lines 215:12-217:13
    Visibility: public -/
def collections.vec_deque.VecDeque.Insts.CoreOpsIndexIndexUsizeT.index
  {T : Type} (self : collections.vec_deque.VecDeque T A)
  (i : Std.Usize) :
  Result T
  := do
  let (s, _) := self
  rust_primitives.sequence.seq_index s i

/-- Trait implementation: [alloc::collections::vec_deque::{core::ops::index::Index<usize, T> for alloc::collections::vec_deque::VecDeque<T, A>}]
    Source: 'src/lib.rs', lines 212:8-218:9 -/
@[reducible]
def collections.vec_deque.VecDeque.Insts.CoreOpsIndexIndexUsizeT (T : Type) (A
  : Type) : core.ops.index.Index (collections.vec_deque.VecDeque T A) Std.Usize
  T := {
  index := collections.vec_deque.VecDeque.Insts.CoreOpsIndexIndexUsizeT.index
}

/-- [alloc::fmt::format]:
    Source: 'src/lib.rs', lines 224:4-226:5 -/
def fmt.format (args : core.fmt.Arguments) : Result String := do
  alloc.string.String.new

/-- [alloc::slice::{alloc::slice::Dummy<T>}::to_vec]:
    Source: 'src/lib.rs', lines 237:8-244:9 -/
def slice.Dummy.to_vec
  {T : Type} (corecloneCloneInst : core.clone.Clone T) (s : Slice T) :
  Result (vec.Vec T)
  := do
  let seq ← rust_primitives.sequence.seq_empty T
  let seq1 ← rust_primitives.sequence.seq_extend corecloneCloneInst seq s
  ok (seq1, core.Phantom.mk)

/-- [alloc::slice::{alloc::slice::Dummy<T>}::into_vec]:
    Source: 'src/lib.rs', lines 245:8-247:9 -/
def slice.Dummy.into_vec
  {T : Type} (A : Type) (s : Slice T) : Result (vec.Vec T) := do
  let s1 ← rust_primitives.sequence.seq_from_boxed_slice s
  ok (s1, core.Phantom.mk)

/-- [alloc::vec::from_elem]:
    Source: 'src/lib.rs', lines 349:4-354:5 -/
def vec.from_elem
  {T : Type} (corecloneCloneInst : core.clone.Clone T) (item : T)
  (len : Std.Usize) :
  Result (vec.Vec T)
  := do
  let s ← rust_primitives.sequence.seq_create corecloneCloneInst item len
  ok (s, core.Phantom.mk)

/-- [alloc::vec::{alloc::vec::Vec<T, alloc::alloc::Global>}::new]:
    Source: 'src/lib.rs', lines 358:8-363:9
    Visibility: public -/
def vec.Vec.new (T : Type) : vec.Vec T :=
  (.new T, core.Phantom.mk)

/-- [alloc::vec::{alloc::vec::Vec<T, alloc::alloc::Global>}::with_capacity]:
    Source: 'src/lib.rs', lines 364:8-366:9
    Visibility: public -/
def vec.Vec.with_capacity (T : Type) (_c : Std.Usize) : vec.Vec T :=
  vec.Vec.new T

/-- [alloc::vec::{alloc::vec::Vec<T, A>}::len]:
    Source: 'src/lib.rs', lines 371:8-373:9
    Visibility: public -/
def vec.Vec.len {T : Type} (self : vec.Vec T) : Std.Usize :=
  let (s, _) := self
  .mk (Std.Slice.len s)

/-- [alloc::vec::{alloc::vec::Vec<T, A>}::push]:
    Source: 'src/lib.rs', lines 375:8-377:9
    Visibility: public -/
def vec.Vec.push
  {T : Type} (self : vec.Vec T) (x : T) :
  Result (vec.Vec T)
  := do
  let (s, pd) := self
  let s1 ← rust_primitives.sequence.seq_push s x
  ok (s1, pd)

/-- [alloc::vec::{alloc::vec::Vec<T, A>}::pop]:
    Source: 'src/lib.rs', lines 378:8-386:9
    Visibility: public -/
def vec.Vec.pop
  {T : Type} (self : vec.Vec T) :
  Result ((Option T) × (vec.Vec T))
  := do
  let (s, pd) := self
  let l ← rust_primitives.sequence.seq_len s
  if l > 0#usize
  then
    let i ← l - 1#usize
    let (last, s1) ← rust_primitives.sequence.seq_remove s i
    ok (some last, (s1, pd))
  else ok (none, self)

/-- [alloc::vec::{alloc::vec::Vec<T, A>}::is_empty]:
    Source: 'src/lib.rs', lines 387:8-389:9
    Visibility: public -/
def vec.Vec.is_empty
  {T : Type} (self : vec.Vec T) : Result Bool := do
  let (s, _) := self
  let i ← rust_primitives.sequence.seq_len s
  ok (i = 0#usize)

/-- [alloc::vec::{alloc::vec::Vec<T, A>}::insert]:
    Source: 'src/lib.rs', lines 391:8-396:9
    Visibility: public -/
def vec.Vec.insert
  {T : Type} (self : vec.Vec T) (index : Std.Usize) (element : T)
  :
  Result (vec.Vec T)
  := do
  let (s, pd) := self
  let l ← rust_primitives.sequence.seq_len s
  let (right, s1) ← rust_primitives.sequence.seq_drain s index l
  let s2 ← rust_primitives.sequence.seq_push s1 element
  let (s3, _) ← rust_primitives.sequence.seq_concat s2 right
  ok (s3, pd)

/-- [alloc::vec::{alloc::vec::Vec<T, A>}::as_slice]:
    Source: 'src/lib.rs', lines 397:8-399:9
    Visibility: public -/
def vec.Vec.as_slice
  {T : Type} (self : vec.Vec T) : Result (Slice T) := do
  let (s, _) := self
  rust_primitives.sequence.seq_to_slice s

/-- [alloc::vec::{alloc::vec::Vec<T, A>}::truncate]:
    Source: 'src/lib.rs', lines 401:8-401:47
    Visibility: public -/
def vec.Vec.truncate
  {T : Type} (self : vec.Vec T) (n : Std.Usize) :
  Result (vec.Vec T)
  := do
  ok self

/-- [alloc::vec::{alloc::vec::Vec<T, A>}::swap_remove]:
    Source: 'src/lib.rs', lines 403:8-405:9
    Visibility: public -/
def vec.Vec.swap_remove
  {T : Type} (self : vec.Vec T) (n : Std.Usize) :
  Result (T × (vec.Vec T))
  := do
  let (s, pd) := self
  let (t, s1) ← rust_primitives.sequence.seq_remove s n
  ok (t, (s1, pd))

/-- [alloc::vec::{alloc::vec::Vec<T, A>}::resize]:
    Source: 'src/lib.rs', lines 408:8-408:63
    Visibility: public -/
def vec.Vec.resize
  {T : Type} (self : vec.Vec T) (new_size : Std.Usize) (value : T)
  :
  Result (vec.Vec T)
  := do
  ok self

/-- [alloc::vec::{alloc::vec::Vec<T, A>}::remove]:
    Source: 'src/lib.rs', lines 410:8-412:9
    Visibility: public -/
def vec.Vec.remove
  {T : Type} (self : vec.Vec T) (index : Std.Usize) :
  Result (T × (vec.Vec T))
  := do
  let (s, pd) := self
  let (t, s1) ← rust_primitives.sequence.seq_remove s index
  ok (t, (s1, pd))

/-- [alloc::vec::{alloc::vec::Vec<T, A>}::clear]:
    Source: 'src/lib.rs', lines 414:8-414:34
    Visibility: public -/
def vec.Vec.clear
  {T : Type} (self : vec.Vec T) : Result (vec.Vec T) := do
  ok self

/-- [alloc::vec::{alloc::vec::Vec<T, A>}::append]:
    Source: 'src/lib.rs', lines 416:8-419:9
    Visibility: public -/
def vec.Vec.append
  {T : Type} (self : vec.Vec T) (other : vec.Vec T) :
  Result ((vec.Vec T) × (vec.Vec T))
  := do
  let (s, pd) := self
  let (s1, pd1) := other
  let (s2, _) ← rust_primitives.sequence.seq_concat s s1
  let s3 ← rust_primitives.sequence.seq_empty T
  ok ((s2, pd), (s3, pd1))

/-- [alloc::vec::{alloc::vec::Vec<T, A>}::drain]:
    Source: 'src/lib.rs', lines 421:8-424:9
    Visibility: public -/
def vec.Vec.drain
  {T : Type} {R : Type} (self : vec.Vec T) (_range : R) :
  Result ((vec.drain.Drain T) × (vec.Vec T))
  := do
  let (s, pd) := self
  let l ← rust_primitives.sequence.seq_len s
  let (s1, s2) ← rust_primitives.sequence.seq_drain s 0#usize l
  ok ((s1, core.Phantom.mk), (s2, pd))

/-- [alloc::vec::drain::{core::iter::traits::iterator::Iterator<T> for alloc::vec::drain::Drain<T, A>}::next]:
    Source: 'src/lib.rs', lines 431:12-438:13
    Visibility: public -/
def vec.drain.Drain.Insts.CoreIterTraitsIteratorIterator.next
  {T : Type} (self : vec.drain.Drain T) :
  Result ((Option T) × (vec.drain.Drain T))
  := do
  let (s, pd) := self
  let i ← rust_primitives.sequence.seq_len s
  if i = 0#usize
  then ok (none, self)
  else
    let (res, s1) ← rust_primitives.sequence.seq_remove s 0#usize
    ok (some res, (s1, pd))

/-- Trait implementation: [alloc::vec::drain::{core::iter::traits::iterator::Iterator<T> for alloc::vec::drain::Drain<T, A>}]
    Source: 'src/lib.rs', lines 429:8-439:9 -/
@[reducible]
def vec.drain.Drain.Insts.CoreIterTraitsIteratorIterator (T : Type) (A : Type)
  : core.iter.traits.iterator.Iterator (vec.drain.Drain T) T := {
  next := vec.drain.Drain.Insts.CoreIterTraitsIteratorIterator.next
}

/-- [alloc::vec::{alloc::vec::Vec<T, A>}::extend_from_slice]:
    Source: 'src/lib.rs', lines 445:8-447:9 -/
def vec.Vec.extend_from_slice
  {T : Type} (corecloneCloneInst : core.clone.Clone T)
  (self : vec.Vec T) (other : Slice T) :
  Result (vec.Vec T)
  := do
  let (s, pd) := self
  let s1 ← rust_primitives.sequence.seq_extend corecloneCloneInst s other
  ok (s1, pd)

/-- [alloc::vec::{core::ops::deref::Deref<[T]> for alloc::vec::Vec<T, A>}::deref]:
    Source: 'src/lib.rs', lines 478:8-480:9
    Visibility: public -/
def vec.Vec.Insts.CoreOpsDerefDerefSlice.deref
  {T : Type} (self : vec.Vec T) : Result (Slice T) := do
  vec.Vec.as_slice self

/-- Trait implementation: [alloc::vec::{core::ops::deref::Deref<[T]> for alloc::vec::Vec<T, A>}]
    Source: 'src/lib.rs', lines 475:4-481:5 -/
@[reducible]
def vec.Vec.Insts.CoreOpsDerefDerefSlice (T : Type) (A : Type) :
  core.ops.deref.Deref (vec.Vec T) (Slice T) := {
  deref := vec.Vec.Insts.CoreOpsDerefDerefSlice.deref
}

end CoreModels.alloc
