-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [alloc]: type definitions
import CoreModels.TypesPrologue
import CoreModels.Types
import CoreModels.TypesExternal
-- (alloc-side externals live in parent Aeneas.FunsExternal)
open Aeneas
open Aeneas.Std hiding namespace core alloc
open Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

namespace alloc

/-- [alloc::alloc::Global]
    Source: 'src/lib.rs', lines 13:4-13:22
    Visibility: public -/
@[reducible]
def alloc.Global := Unit

/-- [alloc::borrow::Cow]
    Source: 'src/lib.rs', lines 17:4-17:21 -/
@[reducible]
def borrow.Cow (T : Type) := T

/-- Trait declaration: [alloc::borrow::ToOwned]
    Source: 'src/lib.rs', lines 19:4-21:5
    Visibility: public -/
structure borrow.ToOwned (Self : Type) where
  to_owned : Self → Result Self

/-- [alloc::boxed::Box]
    Source: 'src/lib.rs', lines 30:4-30:29
    Visibility: public -/
@[reducible]
def boxed.Box (T : Type) := T

/-- [alloc::collections::btree::set::BTreeSet]
    Source: 'src/lib.rs', lines 164:12-164:56 -/
def collections.btree.set.BTreeSet (T : Type) (U : Type) :=
  core_models.option.Option T × core_models.option.Option U

/-- [alloc::collections::vec_deque::VecDeque]
    Source: 'src/lib.rs', lines 188:8-188:75
    Visibility: public -/
def collections.vec_deque.VecDeque (T : Type) (A : Type) :=
  rust_primitives.sequence.Seq T × core_models.Phantom A

/-- [alloc::slice::Dummy]
    Source: 'src/lib.rs', lines 231:4-231:23 -/
@[reducible]
def slice.Dummy (T : Type) := T

/-- [alloc::vec::Vec]
    Source: 'src/lib.rs', lines 338:4-338:70
    Visibility: public -/
def vec.Vec (T : Type) (A : Type := alloc.Global) :=
  rust_primitives.sequence.Seq T × core_models.Phantom A

/-- [alloc::vec::into_iter::IntoIter]
    Source: 'src/lib.rs', lines 346:8-346:79
    Visibility: public -/
def vec.into_iter.IntoIter (T : Type) (A : Type := alloc.Global) :=
  rust_primitives.sequence.Seq T × core_models.Phantom A

/-- [alloc::vec::drain::Drain]
    Source: 'src/lib.rs', lines 428:8-428:76
    Visibility: public -/
def vec.drain.Drain (T : Type) (A : Type := alloc.Global) :=
  rust_primitives.sequence.Seq T × core_models.Phantom A

end alloc
