-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [alloc]: type definitions
import Aeneas
import CoreModels.Core.TypesPrologue
import CoreModels.Core.Types
import CoreModels.RustPrimitives.Types
-- (alloc-side externals live in parent CoreModels.RustPrimitives)
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace CoreModels.alloc

/-- Trait declaration: [alloc::alloc::Allocator]
    Source: 'src/lib.rs', lines 12:4-12:26
    Visibility: public -/
structure alloc.Allocator (Self : Type) where

/-- [alloc::alloc::Global]
    Source: 'src/lib.rs', lines 16:4-16:22
    Visibility: public -/
@[reducible]
def alloc.Global := Unit

/-- [alloc::borrow::Cow]
    Source: 'src/lib.rs', lines 22:4-22:21 -/
@[reducible]
def borrow.Cow (T : Type) := T

/-- Trait declaration: [alloc::borrow::ToOwned]
    Source: 'src/lib.rs', lines 24:4-26:5
    Visibility: public -/
structure borrow.ToOwned (Self : Type) where
  to_owned : Self → Result Self

/-- [alloc::boxed::Box]
    Source: 'src/lib.rs', lines 35:4-35:29
    Visibility: public -/
@[reducible]
def boxed.Box (T : Type) := T

/-- [alloc::collections::btree::set::BTreeSet]
    Source: 'src/lib.rs', lines 169:12-169:56 -/
def collections.btree.set.BTreeSet (T : Type) (U : Type) :=
  core.option.Option T × core.option.Option U

/-- [alloc::collections::vec_deque::VecDeque]
    Source: 'src/lib.rs', lines 193:8-193:75
    Visibility: public -/
def collections.vec_deque.VecDeque (T : Type) (A : Type) :=
  rust_primitives.sequence.Seq T × core.marker.PhantomData A

/-- [alloc::collections::vec_deque::into_iter::IntoIter]
    Source: 'src/lib.rs', lines 227:12-227:83
    Visibility: public -/
def collections.vec_deque.into_iter.IntoIter (T : Type) (A : Type) :=
  rust_primitives.sequence.Seq T × core.marker.PhantomData A

/-- [alloc::slice::Dummy]
    Source: 'src/lib.rs', lines 282:4-282:23 -/
@[reducible]
def slice.Dummy (T : Type) := T

/-- [alloc::vec::Vec]
    Source: 'src/lib.rs', lines 389:4-389:34
    Visibility: public -/
@[reducible]
def vec.Vec (T : Type) := rust_primitives.sequence.Seq T

/-- [alloc::vec::into_iter::IntoIter]
    Source: 'src/lib.rs', lines 425:8-425:43
    Visibility: public -/
@[reducible]
def vec.into_iter.IntoIter (T : Type) := rust_primitives.sequence.Seq T

/-- [alloc::vec::drain::Drain]
    Source: 'src/lib.rs', lines 529:8-529:76
    Visibility: public -/
def vec.drain.Drain (T : Type) (A : Type) :=
  rust_primitives.sequence.Seq T × core.marker.PhantomData A

end CoreModels.alloc
