name = "CoreModels"
version = "0.1.0"
defaultTargets = ["CoreModels"]

[[lean_lib]]
name = "CoreModels"

[[require]]
name = "aeneas"
git = { url = "https://github.com/cryspen/aeneas", subDir = "backends/lean" }
rev = "8d2077ce4946b52d2d199fe9d2f2d520a4bf8184"
