name = "CoreModels"
version = "0.1.0"
defaultTargets = ["CoreModels"]

[[lean_lib]]
name = "CoreModels"

[[require]]
name = "aeneas"
git = { url = "https://github.com/AeneasVerif/aeneas", subDir = "backends/lean" }
rev = "a2fcf19"
