name = "CoreModels"
version = "0.1.0"
defaultTargets = ["CoreModels"]

[[lean_lib]]
name = "CoreModels"

[[require]]
name = "aeneas"
git = { url = "https://github.com/abentkamp/aeneas", subDir = "backends/lean" }
rev = "4e02d6d8e1421562e6ab4a9737fae159ba602d8b"
