-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [core_models]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes.
import Aeneas
import CoreModels.Command
import CoreModels.TypesPrologue
import CoreModels.Types
open Aeneas
open Aeneas.Std hiding namespace core
open Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

namespace CoreModels

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000
-- open core_models removed

/-- [core::cmp::impls::{core::cmp::PartialOrd<&0 (B)> for &1 (A)}::lt]:
    Source: '/rustc/library/core/src/cmp.rs', lines 2133:8-2133:40
    Name pattern: [core::cmp::impls::{core::cmp::PartialOrd<&'1 @A, &'0 @B>}::lt]
    Visibility: public -/
@[rust_fun "core::cmp::impls::{core::cmp::PartialOrd<&'1 @A, &'0 @B>}::lt"]
axiom Shared1A.Insts.CoreCmpPartialOrdShared0B.lt
  {A : Type} {B : Type} (PartialOrdInst : core.cmp.PartialOrd A B) :
  A → B → Result Bool

/-- [core::cmp::impls::{core::cmp::PartialOrd<&0 (B)> for &1 (A)}::gt]:
    Source: '/rustc/library/core/src/cmp.rs', lines 2141:8-2141:40
    Name pattern: [core::cmp::impls::{core::cmp::PartialOrd<&'1 @A, &'0 @B>}::gt]
    Visibility: public -/
@[rust_fun "core::cmp::impls::{core::cmp::PartialOrd<&'1 @A, &'0 @B>}::gt"]
axiom Shared1A.Insts.CoreCmpPartialOrdShared0B.gt
  {A : Type} {B : Type} (PartialOrdInst : core.cmp.PartialOrd A B) :
  A → B → Result Bool

/-- [core::slice::cmp::{core::cmp::PartialEq<[U]> for [T]}::eq]:
    Source: '/rustc/library/core/src/slice/cmp.rs', lines 18:4-18:37
    Name pattern: [core::slice::cmp::{core::cmp::PartialEq<[@T], [@U]>}::eq]
    Visibility: public -/
@[rust_fun "core::slice::cmp::{core::cmp::PartialEq<[@T], [@U]>}::eq"]
axiom Slice.Insts.CoreCmpPartialEqSlice.eq
  {T : Type} {U : Type} (cmpPartialEqInst : core.cmp.PartialEq T U) :
  Slice T → Slice U → Result Bool

/-- [hax_lib::int::{core::cmp::PartialOrd<hax_lib::int::Int> for hax_lib::int::Int}::le]:
    Source: '/cargo/git/checkouts/hax-580ebeee043cdea1/492a34e/hax-lib/src/dummy.rs', lines 77:46-77:56
    Name pattern: [hax_lib::int::{core::cmp::PartialOrd<hax_lib::int::Int, hax_lib::int::Int>}::le]
    Visibility: public -/
@[rust_fun
  "hax_lib::int::{core::cmp::PartialOrd<hax_lib::int::Int, hax_lib::int::Int>}::le"]
axiom hax_lib.int.Int.Insts.CoreCmpPartialOrdInt.le
  : hax_lib.int.Int → hax_lib.int.Int → Result Bool

/-- [hax_lib::int::{core::ops::arith::Add<hax_lib::int::Int, hax_lib::int::Int> for hax_lib::int::Int}::add]:
    Source: '/cargo/git/checkouts/hax-580ebeee043cdea1/492a34e/hax-lib/src/dummy.rs', lines 92:8-92:49
    Name pattern: [hax_lib::int::{core::ops::arith::Add<hax_lib::int::Int, hax_lib::int::Int, hax_lib::int::Int>}::add]
    Visibility: public -/
@[rust_fun
  "hax_lib::int::{core::ops::arith::Add<hax_lib::int::Int, hax_lib::int::Int, hax_lib::int::Int>}::add"]
axiom hax_lib.int.Int.Insts.CoreOpsArithAddIntInt.add
  : hax_lib.int.Int → hax_lib.int.Int → Result hax_lib.int.Int

/-- [hax_lib::int::{core::ops::arith::Sub<hax_lib::int::Int, hax_lib::int::Int> for hax_lib::int::Int}::sub]:
    Source: '/cargo/git/checkouts/hax-580ebeee043cdea1/492a34e/hax-lib/src/dummy.rs', lines 100:8-100:49
    Name pattern: [hax_lib::int::{core::ops::arith::Sub<hax_lib::int::Int, hax_lib::int::Int, hax_lib::int::Int>}::sub]
    Visibility: public -/
@[rust_fun
  "hax_lib::int::{core::ops::arith::Sub<hax_lib::int::Int, hax_lib::int::Int, hax_lib::int::Int>}::sub"]
axiom hax_lib.int.Int.Insts.CoreOpsArithSubIntInt.sub
  : hax_lib.int.Int → hax_lib.int.Int → Result hax_lib.int.Int

/-- [hax_lib::int::{core::ops::arith::Mul<hax_lib::int::Int, hax_lib::int::Int> for hax_lib::int::Int}::mul]:
    Source: '/cargo/git/checkouts/hax-580ebeee043cdea1/492a34e/hax-lib/src/dummy.rs', lines 108:8-108:49
    Name pattern: [hax_lib::int::{core::ops::arith::Mul<hax_lib::int::Int, hax_lib::int::Int, hax_lib::int::Int>}::mul]
    Visibility: public -/
@[rust_fun
  "hax_lib::int::{core::ops::arith::Mul<hax_lib::int::Int, hax_lib::int::Int, hax_lib::int::Int>}::mul"]
axiom hax_lib.int.Int.Insts.CoreOpsArithMulIntInt.mul
  : hax_lib.int.Int → hax_lib.int.Int → Result hax_lib.int.Int

/-- [hax_lib::int::{hax_lib::int::ToInt for u8}::to_int]:
    Source: '/cargo/git/checkouts/hax-580ebeee043cdea1/492a34e/hax-lib/src/dummy.rs', lines 155:16-155:38
    Name pattern: [hax_lib::int::{hax_lib::int::ToInt<u8>}::to_int]
    Visibility: public -/
@[rust_fun "hax_lib::int::{hax_lib::int::ToInt<u8>}::to_int"]
axiom U8.Insts.Hax_libIntToInt.to_int : Std.U8 → Result hax_lib.int.Int

/-- [hax_lib::int::{hax_lib::int::ToInt for u16}::to_int]:
    Source: '/cargo/git/checkouts/hax-580ebeee043cdea1/492a34e/hax-lib/src/dummy.rs', lines 155:16-155:38
    Name pattern: [hax_lib::int::{hax_lib::int::ToInt<u16>}::to_int]
    Visibility: public -/
@[rust_fun "hax_lib::int::{hax_lib::int::ToInt<u16>}::to_int"]
axiom U16.Insts.Hax_libIntToInt.to_int : Std.U16 → Result hax_lib.int.Int

/-- [hax_lib::int::{hax_lib::int::ToInt for u32}::to_int]:
    Source: '/cargo/git/checkouts/hax-580ebeee043cdea1/492a34e/hax-lib/src/dummy.rs', lines 155:16-155:38
    Name pattern: [hax_lib::int::{hax_lib::int::ToInt<u32>}::to_int]
    Visibility: public -/
@[rust_fun "hax_lib::int::{hax_lib::int::ToInt<u32>}::to_int"]
axiom U32.Insts.Hax_libIntToInt.to_int : Std.U32 → Result hax_lib.int.Int

/-- [hax_lib::int::{hax_lib::int::ToInt for u64}::to_int]:
    Source: '/cargo/git/checkouts/hax-580ebeee043cdea1/492a34e/hax-lib/src/dummy.rs', lines 155:16-155:38
    Name pattern: [hax_lib::int::{hax_lib::int::ToInt<u64>}::to_int]
    Visibility: public -/
@[rust_fun "hax_lib::int::{hax_lib::int::ToInt<u64>}::to_int"]
axiom U64.Insts.Hax_libIntToInt.to_int : Std.U64 → Result hax_lib.int.Int

/-- [hax_lib::int::{hax_lib::int::ToInt for u128}::to_int]:
    Source: '/cargo/git/checkouts/hax-580ebeee043cdea1/492a34e/hax-lib/src/dummy.rs', lines 155:16-155:38
    Name pattern: [hax_lib::int::{hax_lib::int::ToInt<u128>}::to_int]
    Visibility: public -/
@[rust_fun "hax_lib::int::{hax_lib::int::ToInt<u128>}::to_int"]
axiom U128.Insts.Hax_libIntToInt.to_int : Std.U128 → Result hax_lib.int.Int

/-- [hax_lib::int::{hax_lib::int::ToInt for usize}::to_int]:
    Source: '/cargo/git/checkouts/hax-580ebeee043cdea1/492a34e/hax-lib/src/dummy.rs', lines 155:16-155:38
    Name pattern: [hax_lib::int::{hax_lib::int::ToInt<usize>}::to_int]
    Visibility: public -/
@[rust_fun "hax_lib::int::{hax_lib::int::ToInt<usize>}::to_int"]
axiom Usize.Insts.Hax_libIntToInt.to_int : Std.Usize → Result hax_lib.int.Int

/-- [hax_lib::int::{hax_lib::int::ToInt for i8}::to_int]:
    Source: '/cargo/git/checkouts/hax-580ebeee043cdea1/492a34e/hax-lib/src/dummy.rs', lines 155:16-155:38
    Name pattern: [hax_lib::int::{hax_lib::int::ToInt<i8>}::to_int]
    Visibility: public -/
@[rust_fun "hax_lib::int::{hax_lib::int::ToInt<i8>}::to_int"]
axiom I8.Insts.Hax_libIntToInt.to_int : Std.I8 → Result hax_lib.int.Int

/-- [hax_lib::int::{hax_lib::int::ToInt for i16}::to_int]:
    Source: '/cargo/git/checkouts/hax-580ebeee043cdea1/492a34e/hax-lib/src/dummy.rs', lines 155:16-155:38
    Name pattern: [hax_lib::int::{hax_lib::int::ToInt<i16>}::to_int]
    Visibility: public -/
@[rust_fun "hax_lib::int::{hax_lib::int::ToInt<i16>}::to_int"]
axiom I16.Insts.Hax_libIntToInt.to_int : Std.I16 → Result hax_lib.int.Int

/-- [hax_lib::int::{hax_lib::int::ToInt for i32}::to_int]:
    Source: '/cargo/git/checkouts/hax-580ebeee043cdea1/492a34e/hax-lib/src/dummy.rs', lines 155:16-155:38
    Name pattern: [hax_lib::int::{hax_lib::int::ToInt<i32>}::to_int]
    Visibility: public -/
@[rust_fun "hax_lib::int::{hax_lib::int::ToInt<i32>}::to_int"]
axiom I32.Insts.Hax_libIntToInt.to_int : Std.I32 → Result hax_lib.int.Int

/-- [hax_lib::int::{hax_lib::int::ToInt for i64}::to_int]:
    Source: '/cargo/git/checkouts/hax-580ebeee043cdea1/492a34e/hax-lib/src/dummy.rs', lines 155:16-155:38
    Name pattern: [hax_lib::int::{hax_lib::int::ToInt<i64>}::to_int]
    Visibility: public -/
@[rust_fun "hax_lib::int::{hax_lib::int::ToInt<i64>}::to_int"]
axiom I64.Insts.Hax_libIntToInt.to_int : Std.I64 → Result hax_lib.int.Int

/-- [hax_lib::int::{hax_lib::int::ToInt for i128}::to_int]:
    Source: '/cargo/git/checkouts/hax-580ebeee043cdea1/492a34e/hax-lib/src/dummy.rs', lines 155:16-155:38
    Name pattern: [hax_lib::int::{hax_lib::int::ToInt<i128>}::to_int]
    Visibility: public -/
@[rust_fun "hax_lib::int::{hax_lib::int::ToInt<i128>}::to_int"]
axiom I128.Insts.Hax_libIntToInt.to_int : Std.I128 → Result hax_lib.int.Int

/-- [hax_lib::int::{hax_lib::int::ToInt for isize}::to_int]:
    Source: '/cargo/git/checkouts/hax-580ebeee043cdea1/492a34e/hax-lib/src/dummy.rs', lines 155:16-155:38
    Name pattern: [hax_lib::int::{hax_lib::int::ToInt<isize>}::to_int]
    Visibility: public -/
@[rust_fun "hax_lib::int::{hax_lib::int::ToInt<isize>}::to_int"]
axiom Isize.Insts.Hax_libIntToInt.to_int : Std.Isize → Result hax_lib.int.Int

/-- [rust_primitives::slice::slice_length]:
    Source: 'rust_primitives/src/lib.rs', lines 4:4-4:44
    Name pattern: [rust_primitives::slice::slice_length]
    Visibility: public -/
@[rust_fun "rust_primitives::slice::slice_length"]
axiom rust_primitives.slice.slice_length
  {T : Type} : Slice T → Result Std.Usize

/-- [rust_primitives::slice::slice_split_at]:
    Source: 'rust_primitives/src/lib.rs', lines 8:4-8:65
    Name pattern: [rust_primitives::slice::slice_split_at]
    Visibility: public -/
@[rust_fun "rust_primitives::slice::slice_split_at"]
axiom rust_primitives.slice.slice_split_at
  {T : Type} : Slice T → Std.Usize → Result ((Slice T) × (Slice T))

/-- [rust_primitives::slice::slice_contains]:
    Source: 'rust_primitives/src/lib.rs', lines 11:4-11:63
    Name pattern: [rust_primitives::slice::slice_contains]
    Visibility: public -/
@[rust_fun "rust_primitives::slice::slice_contains"]
axiom rust_primitives.slice.slice_contains
  {T : Type} (corecmpPartialEqInst : core.cmp.PartialEq T T) :
  Slice T → T → Result Bool

/-- [rust_primitives::slice::slice_index]:
    Source: 'rust_primitives/src/lib.rs', lines 15:4-15:50
    Name pattern: [rust_primitives::slice::slice_index]
    Visibility: public -/
@[rust_fun "rust_primitives::slice::slice_index"]
axiom rust_primitives.slice.slice_index
  {T : Type} : Slice T → Std.Usize → Result T

/-- [rust_primitives::slice::slice_slice]:
    Source: 'rust_primitives/src/lib.rs', lines 18:4-18:62
    Name pattern: [rust_primitives::slice::slice_slice]
    Visibility: public -/
@[rust_fun "rust_primitives::slice::slice_slice"]
axiom rust_primitives.slice.slice_slice
  {T : Type} : Slice T → Std.Usize → Std.Usize → Result (Slice T)

/-- [rust_primitives::slice::slice_clone_from_slice]:
    Source: 'rust_primitives/src/lib.rs', lines 21:4-21:67
    Name pattern: [rust_primitives::slice::slice_clone_from_slice]
    Visibility: public -/
@[rust_fun "rust_primitives::slice::slice_clone_from_slice"]
axiom rust_primitives.slice.slice_clone_from_slice
  {T : Type} (corecloneCloneInst : core.clone.Clone T) :
  Slice T → Slice T → Result (Slice T)

/-- [rust_primitives::slice::array_from_fn]:
    Source: 'rust_primitives/src/lib.rs', lines 28:4-28:81
    Name pattern: [rust_primitives::slice::array_from_fn]
    Visibility: public -/
@[rust_fun "rust_primitives::slice::array_from_fn"]
axiom rust_primitives.slice.array_from_fn
  {T : Type} {F : Type} (N : Std.Usize) (coreopsfunctionFnMutFTupleUsizeTInst :
  core.ops.function.FnMut F Std.Usize T) :
  F → Result (Array T N)

/-- [rust_primitives::slice::array_map]:
    Source: 'rust_primitives/src/lib.rs', lines 31:4-31:84
    Name pattern: [rust_primitives::slice::array_map]
    Visibility: public -/
@[rust_fun "rust_primitives::slice::array_map"]
axiom rust_primitives.slice.array_map
  {T : Type} {U : Type} {F : Type} {N : Std.Usize}
  (coreopsfunctionFnFTupleTUInst : core.ops.function.Fn F T U) :
  Array T N → F → Result (Array U N)

/-- [rust_primitives::slice::array_as_slice]:
    Source: 'rust_primitives/src/lib.rs', lines 34:4-34:64
    Name pattern: [rust_primitives::slice::array_as_slice]
    Visibility: public -/
@[rust_fun "rust_primitives::slice::array_as_slice"]
axiom rust_primitives.slice.array_as_slice
  {T : Type} {N : Std.Usize} : Array T N → Result (Slice T)

/-- [rust_primitives::slice::array_slice]:
    Source: 'rust_primitives/src/lib.rs', lines 37:4-37:81
    Name pattern: [rust_primitives::slice::array_slice]
    Visibility: public -/
@[rust_fun "rust_primitives::slice::array_slice"]
axiom rust_primitives.slice.array_slice
  {T : Type} {N : Std.Usize} :
  Array T N → Std.Usize → Std.Usize → Result (Slice T)

/-- [rust_primitives::slice::array_index]:
    Source: 'rust_primitives/src/lib.rs', lines 40:4-40:69
    Name pattern: [rust_primitives::slice::array_index]
    Visibility: public -/
@[rust_fun "rust_primitives::slice::array_index"]
axiom rust_primitives.slice.array_index
  {T : Type} {N : Std.Usize} : Array T N → Std.Usize → Result T

/-- [rust_primitives::sequence::seq_from_slice]:
    Source: 'rust_primitives/src/lib.rs', lines 51:4-51:48
    Name pattern: [rust_primitives::sequence::seq_from_slice]
    Visibility: public -/
@[rust_fun "rust_primitives::sequence::seq_from_slice"]
axiom rust_primitives.sequence.seq_from_slice
  {T : Type} : Slice T → Result (rust_primitives.sequence.Seq T)

/-- [rust_primitives::sequence::seq_from_array]:
    Source: 'rust_primitives/src/lib.rs', lines 57:4-57:65
    Name pattern: [rust_primitives::sequence::seq_from_array]
    Visibility: public -/
@[rust_fun "rust_primitives::sequence::seq_from_array"]
axiom rust_primitives.sequence.seq_from_array
  {T : Type} {N : Std.Usize} :
  Array T N → Result (rust_primitives.sequence.Seq T)

/-- [rust_primitives::sequence::seq_len]:
    Source: 'rust_primitives/src/lib.rs', lines 81:4-81:42
    Name pattern: [rust_primitives::sequence::seq_len]
    Visibility: public -/
@[rust_fun "rust_primitives::sequence::seq_len"]
axiom rust_primitives.sequence.seq_len
  {T : Type} : rust_primitives.sequence.Seq T → Result Std.Usize

/-- [rust_primitives::sequence::seq_remove]:
    Source: 'rust_primitives/src/lib.rs', lines 87:4-87:55
    Name pattern: [rust_primitives::sequence::seq_remove]
    Visibility: public -/
@[rust_fun "rust_primitives::sequence::seq_remove"]
axiom rust_primitives.sequence.seq_remove
  {T : Type} :
  rust_primitives.sequence.Seq T → Std.Usize → Result (T ×
    (rust_primitives.sequence.Seq T))

/-- [rust_primitives::arithmetic::saturating_mul_u8]:
    Source: 'rust_primitives/src/lib.rs', lines 132:18-132:21
    Name pattern: [rust_primitives::arithmetic::saturating_mul_u8]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::saturating_mul_u8"]
axiom rust_primitives.arithmetic.saturating_mul_u8
  : Std.U8 → Std.U8 → Result Std.U8

/-- [rust_primitives::arithmetic::rem_euclid_u8]:
    Source: 'rust_primitives/src/lib.rs', lines 132:18-132:21
    Name pattern: [rust_primitives::arithmetic::rem_euclid_u8]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::rem_euclid_u8"]
axiom rust_primitives.arithmetic.rem_euclid_u8
  : Std.U8 → Std.U8 → Result Std.U8

/-- [rust_primitives::arithmetic::saturating_mul_u16]:
    Source: 'rust_primitives/src/lib.rs', lines 132:18-132:21
    Name pattern: [rust_primitives::arithmetic::saturating_mul_u16]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::saturating_mul_u16"]
axiom rust_primitives.arithmetic.saturating_mul_u16
  : Std.U16 → Std.U16 → Result Std.U16

/-- [rust_primitives::arithmetic::rem_euclid_u16]:
    Source: 'rust_primitives/src/lib.rs', lines 132:18-132:21
    Name pattern: [rust_primitives::arithmetic::rem_euclid_u16]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::rem_euclid_u16"]
axiom rust_primitives.arithmetic.rem_euclid_u16
  : Std.U16 → Std.U16 → Result Std.U16

/-- [rust_primitives::arithmetic::saturating_mul_u32]:
    Source: 'rust_primitives/src/lib.rs', lines 132:18-132:21
    Name pattern: [rust_primitives::arithmetic::saturating_mul_u32]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::saturating_mul_u32"]
axiom rust_primitives.arithmetic.saturating_mul_u32
  : Std.U32 → Std.U32 → Result Std.U32

/-- [rust_primitives::arithmetic::rem_euclid_u32]:
    Source: 'rust_primitives/src/lib.rs', lines 132:18-132:21
    Name pattern: [rust_primitives::arithmetic::rem_euclid_u32]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::rem_euclid_u32"]
axiom rust_primitives.arithmetic.rem_euclid_u32
  : Std.U32 → Std.U32 → Result Std.U32

/-- [rust_primitives::arithmetic::saturating_mul_u64]:
    Source: 'rust_primitives/src/lib.rs', lines 132:18-132:21
    Name pattern: [rust_primitives::arithmetic::saturating_mul_u64]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::saturating_mul_u64"]
axiom rust_primitives.arithmetic.saturating_mul_u64
  : Std.U64 → Std.U64 → Result Std.U64

/-- [rust_primitives::arithmetic::rem_euclid_u64]:
    Source: 'rust_primitives/src/lib.rs', lines 132:18-132:21
    Name pattern: [rust_primitives::arithmetic::rem_euclid_u64]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::rem_euclid_u64"]
axiom rust_primitives.arithmetic.rem_euclid_u64
  : Std.U64 → Std.U64 → Result Std.U64

/-- [rust_primitives::arithmetic::saturating_mul_u128]:
    Source: 'rust_primitives/src/lib.rs', lines 132:18-132:21
    Name pattern: [rust_primitives::arithmetic::saturating_mul_u128]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::saturating_mul_u128"]
axiom rust_primitives.arithmetic.saturating_mul_u128
  : Std.U128 → Std.U128 → Result Std.U128

/-- [rust_primitives::arithmetic::rem_euclid_u128]:
    Source: 'rust_primitives/src/lib.rs', lines 132:18-132:21
    Name pattern: [rust_primitives::arithmetic::rem_euclid_u128]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::rem_euclid_u128"]
axiom rust_primitives.arithmetic.rem_euclid_u128
  : Std.U128 → Std.U128 → Result Std.U128

/-- [rust_primitives::arithmetic::saturating_mul_usize]:
    Source: 'rust_primitives/src/lib.rs', lines 132:18-132:21
    Name pattern: [rust_primitives::arithmetic::saturating_mul_usize]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::saturating_mul_usize"]
axiom rust_primitives.arithmetic.saturating_mul_usize
  : Std.Usize → Std.Usize → Result Std.Usize

/-- [rust_primitives::arithmetic::rem_euclid_usize]:
    Source: 'rust_primitives/src/lib.rs', lines 132:18-132:21
    Name pattern: [rust_primitives::arithmetic::rem_euclid_usize]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::rem_euclid_usize"]
axiom rust_primitives.arithmetic.rem_euclid_usize
  : Std.Usize → Std.Usize → Result Std.Usize

/-- [rust_primitives::arithmetic::saturating_mul_i8]:
    Source: 'rust_primitives/src/lib.rs', lines 132:18-132:21
    Name pattern: [rust_primitives::arithmetic::saturating_mul_i8]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::saturating_mul_i8"]
axiom rust_primitives.arithmetic.saturating_mul_i8
  : Std.I8 → Std.I8 → Result Std.I8

/-- [rust_primitives::arithmetic::rem_euclid_i8]:
    Source: 'rust_primitives/src/lib.rs', lines 132:18-132:21
    Name pattern: [rust_primitives::arithmetic::rem_euclid_i8]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::rem_euclid_i8"]
axiom rust_primitives.arithmetic.rem_euclid_i8
  : Std.I8 → Std.I8 → Result Std.I8

/-- [rust_primitives::arithmetic::saturating_mul_i16]:
    Source: 'rust_primitives/src/lib.rs', lines 132:18-132:21
    Name pattern: [rust_primitives::arithmetic::saturating_mul_i16]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::saturating_mul_i16"]
axiom rust_primitives.arithmetic.saturating_mul_i16
  : Std.I16 → Std.I16 → Result Std.I16

/-- [rust_primitives::arithmetic::rem_euclid_i16]:
    Source: 'rust_primitives/src/lib.rs', lines 132:18-132:21
    Name pattern: [rust_primitives::arithmetic::rem_euclid_i16]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::rem_euclid_i16"]
axiom rust_primitives.arithmetic.rem_euclid_i16
  : Std.I16 → Std.I16 → Result Std.I16

/-- [rust_primitives::arithmetic::saturating_mul_i32]:
    Source: 'rust_primitives/src/lib.rs', lines 132:18-132:21
    Name pattern: [rust_primitives::arithmetic::saturating_mul_i32]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::saturating_mul_i32"]
axiom rust_primitives.arithmetic.saturating_mul_i32
  : Std.I32 → Std.I32 → Result Std.I32

/-- [rust_primitives::arithmetic::rem_euclid_i32]:
    Source: 'rust_primitives/src/lib.rs', lines 132:18-132:21
    Name pattern: [rust_primitives::arithmetic::rem_euclid_i32]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::rem_euclid_i32"]
axiom rust_primitives.arithmetic.rem_euclid_i32
  : Std.I32 → Std.I32 → Result Std.I32

/-- [rust_primitives::arithmetic::saturating_mul_i64]:
    Source: 'rust_primitives/src/lib.rs', lines 132:18-132:21
    Name pattern: [rust_primitives::arithmetic::saturating_mul_i64]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::saturating_mul_i64"]
axiom rust_primitives.arithmetic.saturating_mul_i64
  : Std.I64 → Std.I64 → Result Std.I64

/-- [rust_primitives::arithmetic::rem_euclid_i64]:
    Source: 'rust_primitives/src/lib.rs', lines 132:18-132:21
    Name pattern: [rust_primitives::arithmetic::rem_euclid_i64]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::rem_euclid_i64"]
axiom rust_primitives.arithmetic.rem_euclid_i64
  : Std.I64 → Std.I64 → Result Std.I64

/-- [rust_primitives::arithmetic::saturating_mul_i128]:
    Source: 'rust_primitives/src/lib.rs', lines 132:18-132:21
    Name pattern: [rust_primitives::arithmetic::saturating_mul_i128]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::saturating_mul_i128"]
axiom rust_primitives.arithmetic.saturating_mul_i128
  : Std.I128 → Std.I128 → Result Std.I128

/-- [rust_primitives::arithmetic::rem_euclid_i128]:
    Source: 'rust_primitives/src/lib.rs', lines 132:18-132:21
    Name pattern: [rust_primitives::arithmetic::rem_euclid_i128]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::rem_euclid_i128"]
axiom rust_primitives.arithmetic.rem_euclid_i128
  : Std.I128 → Std.I128 → Result Std.I128

/-- [rust_primitives::arithmetic::saturating_mul_isize]:
    Source: 'rust_primitives/src/lib.rs', lines 132:18-132:21
    Name pattern: [rust_primitives::arithmetic::saturating_mul_isize]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::saturating_mul_isize"]
axiom rust_primitives.arithmetic.saturating_mul_isize
  : Std.Isize → Std.Isize → Result Std.Isize

/-- [rust_primitives::arithmetic::rem_euclid_isize]:
    Source: 'rust_primitives/src/lib.rs', lines 132:18-132:21
    Name pattern: [rust_primitives::arithmetic::rem_euclid_isize]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::rem_euclid_isize"]
axiom rust_primitives.arithmetic.rem_euclid_isize
  : Std.Isize → Std.Isize → Result Std.Isize

/-- [rust_primitives::arithmetic::overflowing_sub_u8]:
    Source: 'rust_primitives/src/lib.rs', lines 135:18-135:68
    Name pattern: [rust_primitives::arithmetic::overflowing_sub_u8]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::overflowing_sub_u8"]
axiom rust_primitives.arithmetic.overflowing_sub_u8
  : Std.U8 → Std.U8 → Result (Std.U8 × Bool)

/-- [rust_primitives::arithmetic::overflowing_mul_u8]:
    Source: 'rust_primitives/src/lib.rs', lines 135:18-135:68
    Name pattern: [rust_primitives::arithmetic::overflowing_mul_u8]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::overflowing_mul_u8"]
axiom rust_primitives.arithmetic.overflowing_mul_u8
  : Std.U8 → Std.U8 → Result (Std.U8 × Bool)

/-- [rust_primitives::arithmetic::overflowing_sub_u16]:
    Source: 'rust_primitives/src/lib.rs', lines 135:18-135:68
    Name pattern: [rust_primitives::arithmetic::overflowing_sub_u16]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::overflowing_sub_u16"]
axiom rust_primitives.arithmetic.overflowing_sub_u16
  : Std.U16 → Std.U16 → Result (Std.U16 × Bool)

/-- [rust_primitives::arithmetic::overflowing_mul_u16]:
    Source: 'rust_primitives/src/lib.rs', lines 135:18-135:68
    Name pattern: [rust_primitives::arithmetic::overflowing_mul_u16]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::overflowing_mul_u16"]
axiom rust_primitives.arithmetic.overflowing_mul_u16
  : Std.U16 → Std.U16 → Result (Std.U16 × Bool)

/-- [rust_primitives::arithmetic::overflowing_sub_u32]:
    Source: 'rust_primitives/src/lib.rs', lines 135:18-135:68
    Name pattern: [rust_primitives::arithmetic::overflowing_sub_u32]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::overflowing_sub_u32"]
axiom rust_primitives.arithmetic.overflowing_sub_u32
  : Std.U32 → Std.U32 → Result (Std.U32 × Bool)

/-- [rust_primitives::arithmetic::overflowing_mul_u32]:
    Source: 'rust_primitives/src/lib.rs', lines 135:18-135:68
    Name pattern: [rust_primitives::arithmetic::overflowing_mul_u32]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::overflowing_mul_u32"]
axiom rust_primitives.arithmetic.overflowing_mul_u32
  : Std.U32 → Std.U32 → Result (Std.U32 × Bool)

/-- [rust_primitives::arithmetic::overflowing_sub_u64]:
    Source: 'rust_primitives/src/lib.rs', lines 135:18-135:68
    Name pattern: [rust_primitives::arithmetic::overflowing_sub_u64]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::overflowing_sub_u64"]
axiom rust_primitives.arithmetic.overflowing_sub_u64
  : Std.U64 → Std.U64 → Result (Std.U64 × Bool)

/-- [rust_primitives::arithmetic::overflowing_mul_u64]:
    Source: 'rust_primitives/src/lib.rs', lines 135:18-135:68
    Name pattern: [rust_primitives::arithmetic::overflowing_mul_u64]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::overflowing_mul_u64"]
axiom rust_primitives.arithmetic.overflowing_mul_u64
  : Std.U64 → Std.U64 → Result (Std.U64 × Bool)

/-- [rust_primitives::arithmetic::overflowing_sub_u128]:
    Source: 'rust_primitives/src/lib.rs', lines 135:18-135:68
    Name pattern: [rust_primitives::arithmetic::overflowing_sub_u128]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::overflowing_sub_u128"]
axiom rust_primitives.arithmetic.overflowing_sub_u128
  : Std.U128 → Std.U128 → Result (Std.U128 × Bool)

/-- [rust_primitives::arithmetic::overflowing_mul_u128]:
    Source: 'rust_primitives/src/lib.rs', lines 135:18-135:68
    Name pattern: [rust_primitives::arithmetic::overflowing_mul_u128]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::overflowing_mul_u128"]
axiom rust_primitives.arithmetic.overflowing_mul_u128
  : Std.U128 → Std.U128 → Result (Std.U128 × Bool)

/-- [rust_primitives::arithmetic::overflowing_sub_usize]:
    Source: 'rust_primitives/src/lib.rs', lines 135:18-135:68
    Name pattern: [rust_primitives::arithmetic::overflowing_sub_usize]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::overflowing_sub_usize"]
axiom rust_primitives.arithmetic.overflowing_sub_usize
  : Std.Usize → Std.Usize → Result (Std.Usize × Bool)

/-- [rust_primitives::arithmetic::overflowing_mul_usize]:
    Source: 'rust_primitives/src/lib.rs', lines 135:18-135:68
    Name pattern: [rust_primitives::arithmetic::overflowing_mul_usize]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::overflowing_mul_usize"]
axiom rust_primitives.arithmetic.overflowing_mul_usize
  : Std.Usize → Std.Usize → Result (Std.Usize × Bool)

/-- [rust_primitives::arithmetic::overflowing_sub_i8]:
    Source: 'rust_primitives/src/lib.rs', lines 135:18-135:68
    Name pattern: [rust_primitives::arithmetic::overflowing_sub_i8]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::overflowing_sub_i8"]
axiom rust_primitives.arithmetic.overflowing_sub_i8
  : Std.I8 → Std.I8 → Result (Std.I8 × Bool)

/-- [rust_primitives::arithmetic::overflowing_mul_i8]:
    Source: 'rust_primitives/src/lib.rs', lines 135:18-135:68
    Name pattern: [rust_primitives::arithmetic::overflowing_mul_i8]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::overflowing_mul_i8"]
axiom rust_primitives.arithmetic.overflowing_mul_i8
  : Std.I8 → Std.I8 → Result (Std.I8 × Bool)

/-- [rust_primitives::arithmetic::overflowing_sub_i16]:
    Source: 'rust_primitives/src/lib.rs', lines 135:18-135:68
    Name pattern: [rust_primitives::arithmetic::overflowing_sub_i16]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::overflowing_sub_i16"]
axiom rust_primitives.arithmetic.overflowing_sub_i16
  : Std.I16 → Std.I16 → Result (Std.I16 × Bool)

/-- [rust_primitives::arithmetic::overflowing_mul_i16]:
    Source: 'rust_primitives/src/lib.rs', lines 135:18-135:68
    Name pattern: [rust_primitives::arithmetic::overflowing_mul_i16]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::overflowing_mul_i16"]
axiom rust_primitives.arithmetic.overflowing_mul_i16
  : Std.I16 → Std.I16 → Result (Std.I16 × Bool)

/-- [rust_primitives::arithmetic::overflowing_sub_i32]:
    Source: 'rust_primitives/src/lib.rs', lines 135:18-135:68
    Name pattern: [rust_primitives::arithmetic::overflowing_sub_i32]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::overflowing_sub_i32"]
axiom rust_primitives.arithmetic.overflowing_sub_i32
  : Std.I32 → Std.I32 → Result (Std.I32 × Bool)

/-- [rust_primitives::arithmetic::overflowing_mul_i32]:
    Source: 'rust_primitives/src/lib.rs', lines 135:18-135:68
    Name pattern: [rust_primitives::arithmetic::overflowing_mul_i32]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::overflowing_mul_i32"]
axiom rust_primitives.arithmetic.overflowing_mul_i32
  : Std.I32 → Std.I32 → Result (Std.I32 × Bool)

/-- [rust_primitives::arithmetic::overflowing_sub_i64]:
    Source: 'rust_primitives/src/lib.rs', lines 135:18-135:68
    Name pattern: [rust_primitives::arithmetic::overflowing_sub_i64]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::overflowing_sub_i64"]
axiom rust_primitives.arithmetic.overflowing_sub_i64
  : Std.I64 → Std.I64 → Result (Std.I64 × Bool)

/-- [rust_primitives::arithmetic::overflowing_mul_i64]:
    Source: 'rust_primitives/src/lib.rs', lines 135:18-135:68
    Name pattern: [rust_primitives::arithmetic::overflowing_mul_i64]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::overflowing_mul_i64"]
axiom rust_primitives.arithmetic.overflowing_mul_i64
  : Std.I64 → Std.I64 → Result (Std.I64 × Bool)

/-- [rust_primitives::arithmetic::overflowing_sub_i128]:
    Source: 'rust_primitives/src/lib.rs', lines 135:18-135:68
    Name pattern: [rust_primitives::arithmetic::overflowing_sub_i128]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::overflowing_sub_i128"]
axiom rust_primitives.arithmetic.overflowing_sub_i128
  : Std.I128 → Std.I128 → Result (Std.I128 × Bool)

/-- [rust_primitives::arithmetic::overflowing_mul_i128]:
    Source: 'rust_primitives/src/lib.rs', lines 135:18-135:68
    Name pattern: [rust_primitives::arithmetic::overflowing_mul_i128]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::overflowing_mul_i128"]
axiom rust_primitives.arithmetic.overflowing_mul_i128
  : Std.I128 → Std.I128 → Result (Std.I128 × Bool)

/-- [rust_primitives::arithmetic::overflowing_sub_isize]:
    Source: 'rust_primitives/src/lib.rs', lines 135:18-135:68
    Name pattern: [rust_primitives::arithmetic::overflowing_sub_isize]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::overflowing_sub_isize"]
axiom rust_primitives.arithmetic.overflowing_sub_isize
  : Std.Isize → Std.Isize → Result (Std.Isize × Bool)

/-- [rust_primitives::arithmetic::overflowing_mul_isize]:
    Source: 'rust_primitives/src/lib.rs', lines 135:18-135:68
    Name pattern: [rust_primitives::arithmetic::overflowing_mul_isize]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::overflowing_mul_isize"]
axiom rust_primitives.arithmetic.overflowing_mul_isize
  : Std.Isize → Std.Isize → Result (Std.Isize × Bool)

/-- [rust_primitives::arithmetic::pow_u8]:
    Source: 'rust_primitives/src/lib.rs', lines 159:16-159:35
    Name pattern: [rust_primitives::arithmetic::pow_u8]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::pow_u8"]
axiom rust_primitives.arithmetic.pow_u8 : Std.U8 → Std.U32 → Result Std.U8

/-- [rust_primitives::arithmetic::pow_u16]:
    Source: 'rust_primitives/src/lib.rs', lines 159:16-159:35
    Name pattern: [rust_primitives::arithmetic::pow_u16]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::pow_u16"]
axiom rust_primitives.arithmetic.pow_u16
  : Std.U16 → Std.U32 → Result Std.U16

/-- [rust_primitives::arithmetic::pow_u32]:
    Source: 'rust_primitives/src/lib.rs', lines 159:16-159:35
    Name pattern: [rust_primitives::arithmetic::pow_u32]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::pow_u32"]
axiom rust_primitives.arithmetic.pow_u32
  : Std.U32 → Std.U32 → Result Std.U32

/-- [rust_primitives::arithmetic::pow_u64]:
    Source: 'rust_primitives/src/lib.rs', lines 159:16-159:35
    Name pattern: [rust_primitives::arithmetic::pow_u64]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::pow_u64"]
axiom rust_primitives.arithmetic.pow_u64
  : Std.U64 → Std.U32 → Result Std.U64

/-- [rust_primitives::arithmetic::pow_u128]:
    Source: 'rust_primitives/src/lib.rs', lines 159:16-159:35
    Name pattern: [rust_primitives::arithmetic::pow_u128]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::pow_u128"]
axiom rust_primitives.arithmetic.pow_u128
  : Std.U128 → Std.U32 → Result Std.U128

/-- [rust_primitives::arithmetic::pow_usize]:
    Source: 'rust_primitives/src/lib.rs', lines 159:16-159:35
    Name pattern: [rust_primitives::arithmetic::pow_usize]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::pow_usize"]
axiom rust_primitives.arithmetic.pow_usize
  : Std.Usize → Std.U32 → Result Std.Usize

/-- [rust_primitives::arithmetic::pow_i8]:
    Source: 'rust_primitives/src/lib.rs', lines 159:16-159:35
    Name pattern: [rust_primitives::arithmetic::pow_i8]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::pow_i8"]
axiom rust_primitives.arithmetic.pow_i8 : Std.I8 → Std.U32 → Result Std.I8

/-- [rust_primitives::arithmetic::pow_i16]:
    Source: 'rust_primitives/src/lib.rs', lines 159:16-159:35
    Name pattern: [rust_primitives::arithmetic::pow_i16]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::pow_i16"]
axiom rust_primitives.arithmetic.pow_i16
  : Std.I16 → Std.U32 → Result Std.I16

/-- [rust_primitives::arithmetic::pow_i32]:
    Source: 'rust_primitives/src/lib.rs', lines 159:16-159:35
    Name pattern: [rust_primitives::arithmetic::pow_i32]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::pow_i32"]
axiom rust_primitives.arithmetic.pow_i32
  : Std.I32 → Std.U32 → Result Std.I32

/-- [rust_primitives::arithmetic::pow_i64]:
    Source: 'rust_primitives/src/lib.rs', lines 159:16-159:35
    Name pattern: [rust_primitives::arithmetic::pow_i64]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::pow_i64"]
axiom rust_primitives.arithmetic.pow_i64
  : Std.I64 → Std.U32 → Result Std.I64

/-- [rust_primitives::arithmetic::pow_i128]:
    Source: 'rust_primitives/src/lib.rs', lines 159:16-159:35
    Name pattern: [rust_primitives::arithmetic::pow_i128]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::pow_i128"]
axiom rust_primitives.arithmetic.pow_i128
  : Std.I128 → Std.U32 → Result Std.I128

/-- [rust_primitives::arithmetic::pow_isize]:
    Source: 'rust_primitives/src/lib.rs', lines 159:16-159:35
    Name pattern: [rust_primitives::arithmetic::pow_isize]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::pow_isize"]
axiom rust_primitives.arithmetic.pow_isize
  : Std.Isize → Std.U32 → Result Std.Isize

/-- [rust_primitives::arithmetic::from_be_bytes_u8]:
    Source: 'rust_primitives/src/lib.rs', lines 159:30-177:19
    Name pattern: [rust_primitives::arithmetic::from_be_bytes_u8]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::from_be_bytes_u8"]
axiom rust_primitives.arithmetic.from_be_bytes_u8
  : Array Std.U8 1#usize → Result Std.U8

/-- [rust_primitives::arithmetic::from_le_bytes_u8]:
    Source: 'rust_primitives/src/lib.rs', lines 159:30-180:19
    Name pattern: [rust_primitives::arithmetic::from_le_bytes_u8]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::from_le_bytes_u8"]
axiom rust_primitives.arithmetic.from_le_bytes_u8
  : Array Std.U8 1#usize → Result Std.U8

/-- [rust_primitives::arithmetic::from_be_bytes_u16]:
    Source: 'rust_primitives/src/lib.rs', lines 159:30-177:19
    Name pattern: [rust_primitives::arithmetic::from_be_bytes_u16]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::from_be_bytes_u16"]
axiom rust_primitives.arithmetic.from_be_bytes_u16
  : Array Std.U8 2#usize → Result Std.U16

/-- [rust_primitives::arithmetic::from_le_bytes_u16]:
    Source: 'rust_primitives/src/lib.rs', lines 159:30-180:19
    Name pattern: [rust_primitives::arithmetic::from_le_bytes_u16]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::from_le_bytes_u16"]
axiom rust_primitives.arithmetic.from_le_bytes_u16
  : Array Std.U8 2#usize → Result Std.U16

/-- [rust_primitives::arithmetic::from_be_bytes_u32]:
    Source: 'rust_primitives/src/lib.rs', lines 159:30-177:19
    Name pattern: [rust_primitives::arithmetic::from_be_bytes_u32]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::from_be_bytes_u32"]
axiom rust_primitives.arithmetic.from_be_bytes_u32
  : Array Std.U8 4#usize → Result Std.U32

/-- [rust_primitives::arithmetic::from_le_bytes_u32]:
    Source: 'rust_primitives/src/lib.rs', lines 159:30-180:19
    Name pattern: [rust_primitives::arithmetic::from_le_bytes_u32]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::from_le_bytes_u32"]
axiom rust_primitives.arithmetic.from_le_bytes_u32
  : Array Std.U8 4#usize → Result Std.U32

/-- [rust_primitives::arithmetic::from_be_bytes_u64]:
    Source: 'rust_primitives/src/lib.rs', lines 159:30-177:19
    Name pattern: [rust_primitives::arithmetic::from_be_bytes_u64]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::from_be_bytes_u64"]
axiom rust_primitives.arithmetic.from_be_bytes_u64
  : Array Std.U8 8#usize → Result Std.U64

/-- [rust_primitives::arithmetic::from_le_bytes_u64]:
    Source: 'rust_primitives/src/lib.rs', lines 159:30-180:19
    Name pattern: [rust_primitives::arithmetic::from_le_bytes_u64]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::from_le_bytes_u64"]
axiom rust_primitives.arithmetic.from_le_bytes_u64
  : Array Std.U8 8#usize → Result Std.U64

/-- [rust_primitives::arithmetic::from_be_bytes_u128]:
    Source: 'rust_primitives/src/lib.rs', lines 159:30-177:19
    Name pattern: [rust_primitives::arithmetic::from_be_bytes_u128]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::from_be_bytes_u128"]
axiom rust_primitives.arithmetic.from_be_bytes_u128
  : Array Std.U8 16#usize → Result Std.U128

/-- [rust_primitives::arithmetic::from_le_bytes_u128]:
    Source: 'rust_primitives/src/lib.rs', lines 159:30-180:19
    Name pattern: [rust_primitives::arithmetic::from_le_bytes_u128]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::from_le_bytes_u128"]
axiom rust_primitives.arithmetic.from_le_bytes_u128
  : Array Std.U8 16#usize → Result Std.U128

/-- [rust_primitives::arithmetic::from_be_bytes_usize]:
    Source: 'rust_primitives/src/lib.rs', lines 159:30-177:19
    Name pattern: [rust_primitives::arithmetic::from_be_bytes_usize]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::from_be_bytes_usize"]
axiom rust_primitives.arithmetic.from_be_bytes_usize
  : Array Std.U8 8#usize → Result Std.Usize

/-- [rust_primitives::arithmetic::from_le_bytes_usize]:
    Source: 'rust_primitives/src/lib.rs', lines 159:30-180:19
    Name pattern: [rust_primitives::arithmetic::from_le_bytes_usize]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::from_le_bytes_usize"]
axiom rust_primitives.arithmetic.from_le_bytes_usize
  : Array Std.U8 8#usize → Result Std.Usize

/-- [rust_primitives::arithmetic::from_be_bytes_i8]:
    Source: 'rust_primitives/src/lib.rs', lines 159:30-177:19
    Name pattern: [rust_primitives::arithmetic::from_be_bytes_i8]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::from_be_bytes_i8"]
axiom rust_primitives.arithmetic.from_be_bytes_i8
  : Array Std.U8 1#usize → Result Std.I8

/-- [rust_primitives::arithmetic::from_le_bytes_i8]:
    Source: 'rust_primitives/src/lib.rs', lines 159:30-180:19
    Name pattern: [rust_primitives::arithmetic::from_le_bytes_i8]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::from_le_bytes_i8"]
axiom rust_primitives.arithmetic.from_le_bytes_i8
  : Array Std.U8 1#usize → Result Std.I8

/-- [rust_primitives::arithmetic::from_be_bytes_i16]:
    Source: 'rust_primitives/src/lib.rs', lines 159:30-177:19
    Name pattern: [rust_primitives::arithmetic::from_be_bytes_i16]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::from_be_bytes_i16"]
axiom rust_primitives.arithmetic.from_be_bytes_i16
  : Array Std.U8 2#usize → Result Std.I16

/-- [rust_primitives::arithmetic::from_le_bytes_i16]:
    Source: 'rust_primitives/src/lib.rs', lines 159:30-180:19
    Name pattern: [rust_primitives::arithmetic::from_le_bytes_i16]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::from_le_bytes_i16"]
axiom rust_primitives.arithmetic.from_le_bytes_i16
  : Array Std.U8 2#usize → Result Std.I16

/-- [rust_primitives::arithmetic::from_be_bytes_i32]:
    Source: 'rust_primitives/src/lib.rs', lines 159:30-177:19
    Name pattern: [rust_primitives::arithmetic::from_be_bytes_i32]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::from_be_bytes_i32"]
axiom rust_primitives.arithmetic.from_be_bytes_i32
  : Array Std.U8 4#usize → Result Std.I32

/-- [rust_primitives::arithmetic::from_le_bytes_i32]:
    Source: 'rust_primitives/src/lib.rs', lines 159:30-180:19
    Name pattern: [rust_primitives::arithmetic::from_le_bytes_i32]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::from_le_bytes_i32"]
axiom rust_primitives.arithmetic.from_le_bytes_i32
  : Array Std.U8 4#usize → Result Std.I32

/-- [rust_primitives::arithmetic::from_be_bytes_i64]:
    Source: 'rust_primitives/src/lib.rs', lines 159:30-177:19
    Name pattern: [rust_primitives::arithmetic::from_be_bytes_i64]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::from_be_bytes_i64"]
axiom rust_primitives.arithmetic.from_be_bytes_i64
  : Array Std.U8 8#usize → Result Std.I64

/-- [rust_primitives::arithmetic::from_le_bytes_i64]:
    Source: 'rust_primitives/src/lib.rs', lines 159:30-180:19
    Name pattern: [rust_primitives::arithmetic::from_le_bytes_i64]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::from_le_bytes_i64"]
axiom rust_primitives.arithmetic.from_le_bytes_i64
  : Array Std.U8 8#usize → Result Std.I64

/-- [rust_primitives::arithmetic::from_be_bytes_i128]:
    Source: 'rust_primitives/src/lib.rs', lines 159:30-177:19
    Name pattern: [rust_primitives::arithmetic::from_be_bytes_i128]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::from_be_bytes_i128"]
axiom rust_primitives.arithmetic.from_be_bytes_i128
  : Array Std.U8 16#usize → Result Std.I128

/-- [rust_primitives::arithmetic::from_le_bytes_i128]:
    Source: 'rust_primitives/src/lib.rs', lines 159:30-180:19
    Name pattern: [rust_primitives::arithmetic::from_le_bytes_i128]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::from_le_bytes_i128"]
axiom rust_primitives.arithmetic.from_le_bytes_i128
  : Array Std.U8 16#usize → Result Std.I128

/-- [rust_primitives::arithmetic::from_be_bytes_isize]:
    Source: 'rust_primitives/src/lib.rs', lines 159:30-177:19
    Name pattern: [rust_primitives::arithmetic::from_be_bytes_isize]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::from_be_bytes_isize"]
axiom rust_primitives.arithmetic.from_be_bytes_isize
  : Array Std.U8 8#usize → Result Std.Isize

/-- [rust_primitives::arithmetic::from_le_bytes_isize]:
    Source: 'rust_primitives/src/lib.rs', lines 159:30-180:19
    Name pattern: [rust_primitives::arithmetic::from_le_bytes_isize]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::from_le_bytes_isize"]
axiom rust_primitives.arithmetic.from_le_bytes_isize
  : Array Std.U8 8#usize → Result Std.Isize

/-- [rust_primitives::arithmetic::count_ones_u8]:
    Source: 'rust_primitives/src/lib.rs', lines 162:16-162:61
    Name pattern: [rust_primitives::arithmetic::count_ones_u8]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::count_ones_u8"]
axiom rust_primitives.arithmetic.count_ones_u8 : Std.U8 → Result Std.U32

/-- [rust_primitives::arithmetic::count_ones_u16]:
    Source: 'rust_primitives/src/lib.rs', lines 162:16-162:61
    Name pattern: [rust_primitives::arithmetic::count_ones_u16]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::count_ones_u16"]
axiom rust_primitives.arithmetic.count_ones_u16 : Std.U16 → Result Std.U32

/-- [rust_primitives::arithmetic::count_ones_u32]:
    Source: 'rust_primitives/src/lib.rs', lines 162:16-162:61
    Name pattern: [rust_primitives::arithmetic::count_ones_u32]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::count_ones_u32"]
axiom rust_primitives.arithmetic.count_ones_u32 : Std.U32 → Result Std.U32

/-- [rust_primitives::arithmetic::count_ones_u64]:
    Source: 'rust_primitives/src/lib.rs', lines 162:16-162:61
    Name pattern: [rust_primitives::arithmetic::count_ones_u64]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::count_ones_u64"]
axiom rust_primitives.arithmetic.count_ones_u64 : Std.U64 → Result Std.U32

/-- [rust_primitives::arithmetic::count_ones_u128]:
    Source: 'rust_primitives/src/lib.rs', lines 162:16-162:61
    Name pattern: [rust_primitives::arithmetic::count_ones_u128]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::count_ones_u128"]
axiom rust_primitives.arithmetic.count_ones_u128 : Std.U128 → Result Std.U32

/-- [rust_primitives::arithmetic::count_ones_usize]:
    Source: 'rust_primitives/src/lib.rs', lines 162:16-162:61
    Name pattern: [rust_primitives::arithmetic::count_ones_usize]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::count_ones_usize"]
axiom rust_primitives.arithmetic.count_ones_usize
  : Std.Usize → Result Std.U32

/-- [rust_primitives::arithmetic::count_ones_i8]:
    Source: 'rust_primitives/src/lib.rs', lines 162:16-162:61
    Name pattern: [rust_primitives::arithmetic::count_ones_i8]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::count_ones_i8"]
axiom rust_primitives.arithmetic.count_ones_i8 : Std.I8 → Result Std.U32

/-- [rust_primitives::arithmetic::count_ones_i16]:
    Source: 'rust_primitives/src/lib.rs', lines 162:16-162:61
    Name pattern: [rust_primitives::arithmetic::count_ones_i16]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::count_ones_i16"]
axiom rust_primitives.arithmetic.count_ones_i16 : Std.I16 → Result Std.U32

/-- [rust_primitives::arithmetic::count_ones_i32]:
    Source: 'rust_primitives/src/lib.rs', lines 162:16-162:61
    Name pattern: [rust_primitives::arithmetic::count_ones_i32]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::count_ones_i32"]
axiom rust_primitives.arithmetic.count_ones_i32 : Std.I32 → Result Std.U32

/-- [rust_primitives::arithmetic::count_ones_i64]:
    Source: 'rust_primitives/src/lib.rs', lines 162:16-162:61
    Name pattern: [rust_primitives::arithmetic::count_ones_i64]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::count_ones_i64"]
axiom rust_primitives.arithmetic.count_ones_i64 : Std.I64 → Result Std.U32

/-- [rust_primitives::arithmetic::count_ones_i128]:
    Source: 'rust_primitives/src/lib.rs', lines 162:16-162:61
    Name pattern: [rust_primitives::arithmetic::count_ones_i128]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::count_ones_i128"]
axiom rust_primitives.arithmetic.count_ones_i128 : Std.I128 → Result Std.U32

/-- [rust_primitives::arithmetic::count_ones_isize]:
    Source: 'rust_primitives/src/lib.rs', lines 162:16-162:61
    Name pattern: [rust_primitives::arithmetic::count_ones_isize]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::count_ones_isize"]
axiom rust_primitives.arithmetic.count_ones_isize
  : Std.Isize → Result Std.U32

/-- [rust_primitives::arithmetic::leading_zeros_u8]:
    Source: 'rust_primitives/src/lib.rs', lines 171:16-171:64
    Name pattern: [rust_primitives::arithmetic::leading_zeros_u8]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::leading_zeros_u8"]
axiom rust_primitives.arithmetic.leading_zeros_u8 : Std.U8 → Result Std.U32

/-- [rust_primitives::arithmetic::leading_zeros_u16]:
    Source: 'rust_primitives/src/lib.rs', lines 171:16-171:64
    Name pattern: [rust_primitives::arithmetic::leading_zeros_u16]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::leading_zeros_u16"]
axiom rust_primitives.arithmetic.leading_zeros_u16 : Std.U16 → Result Std.U32

/-- [rust_primitives::arithmetic::leading_zeros_u32]:
    Source: 'rust_primitives/src/lib.rs', lines 171:16-171:64
    Name pattern: [rust_primitives::arithmetic::leading_zeros_u32]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::leading_zeros_u32"]
axiom rust_primitives.arithmetic.leading_zeros_u32 : Std.U32 → Result Std.U32

/-- [rust_primitives::arithmetic::leading_zeros_u64]:
    Source: 'rust_primitives/src/lib.rs', lines 171:16-171:64
    Name pattern: [rust_primitives::arithmetic::leading_zeros_u64]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::leading_zeros_u64"]
axiom rust_primitives.arithmetic.leading_zeros_u64 : Std.U64 → Result Std.U32

/-- [rust_primitives::arithmetic::leading_zeros_u128]:
    Source: 'rust_primitives/src/lib.rs', lines 171:16-171:64
    Name pattern: [rust_primitives::arithmetic::leading_zeros_u128]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::leading_zeros_u128"]
axiom rust_primitives.arithmetic.leading_zeros_u128
  : Std.U128 → Result Std.U32

/-- [rust_primitives::arithmetic::leading_zeros_usize]:
    Source: 'rust_primitives/src/lib.rs', lines 171:16-171:64
    Name pattern: [rust_primitives::arithmetic::leading_zeros_usize]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::leading_zeros_usize"]
axiom rust_primitives.arithmetic.leading_zeros_usize
  : Std.Usize → Result Std.U32

/-- [rust_primitives::arithmetic::leading_zeros_i8]:
    Source: 'rust_primitives/src/lib.rs', lines 171:16-171:64
    Name pattern: [rust_primitives::arithmetic::leading_zeros_i8]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::leading_zeros_i8"]
axiom rust_primitives.arithmetic.leading_zeros_i8 : Std.I8 → Result Std.U32

/-- [rust_primitives::arithmetic::leading_zeros_i16]:
    Source: 'rust_primitives/src/lib.rs', lines 171:16-171:64
    Name pattern: [rust_primitives::arithmetic::leading_zeros_i16]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::leading_zeros_i16"]
axiom rust_primitives.arithmetic.leading_zeros_i16 : Std.I16 → Result Std.U32

/-- [rust_primitives::arithmetic::leading_zeros_i32]:
    Source: 'rust_primitives/src/lib.rs', lines 171:16-171:64
    Name pattern: [rust_primitives::arithmetic::leading_zeros_i32]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::leading_zeros_i32"]
axiom rust_primitives.arithmetic.leading_zeros_i32 : Std.I32 → Result Std.U32

/-- [rust_primitives::arithmetic::leading_zeros_i64]:
    Source: 'rust_primitives/src/lib.rs', lines 171:16-171:64
    Name pattern: [rust_primitives::arithmetic::leading_zeros_i64]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::leading_zeros_i64"]
axiom rust_primitives.arithmetic.leading_zeros_i64 : Std.I64 → Result Std.U32

/-- [rust_primitives::arithmetic::leading_zeros_i128]:
    Source: 'rust_primitives/src/lib.rs', lines 171:16-171:64
    Name pattern: [rust_primitives::arithmetic::leading_zeros_i128]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::leading_zeros_i128"]
axiom rust_primitives.arithmetic.leading_zeros_i128
  : Std.I128 → Result Std.U32

/-- [rust_primitives::arithmetic::leading_zeros_isize]:
    Source: 'rust_primitives/src/lib.rs', lines 171:16-171:64
    Name pattern: [rust_primitives::arithmetic::leading_zeros_isize]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::leading_zeros_isize"]
axiom rust_primitives.arithmetic.leading_zeros_isize
  : Std.Isize → Result Std.U32

/-- [rust_primitives::arithmetic::ilog2_u8]:
    Source: 'rust_primitives/src/lib.rs', lines 174:16-174:56
    Name pattern: [rust_primitives::arithmetic::ilog2_u8]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::ilog2_u8"]
axiom rust_primitives.arithmetic.ilog2_u8 : Std.U8 → Result Std.U32

/-- [rust_primitives::arithmetic::ilog2_u16]:
    Source: 'rust_primitives/src/lib.rs', lines 174:16-174:56
    Name pattern: [rust_primitives::arithmetic::ilog2_u16]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::ilog2_u16"]
axiom rust_primitives.arithmetic.ilog2_u16 : Std.U16 → Result Std.U32

/-- [rust_primitives::arithmetic::ilog2_u32]:
    Source: 'rust_primitives/src/lib.rs', lines 174:16-174:56
    Name pattern: [rust_primitives::arithmetic::ilog2_u32]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::ilog2_u32"]
axiom rust_primitives.arithmetic.ilog2_u32 : Std.U32 → Result Std.U32

/-- [rust_primitives::arithmetic::ilog2_u64]:
    Source: 'rust_primitives/src/lib.rs', lines 174:16-174:56
    Name pattern: [rust_primitives::arithmetic::ilog2_u64]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::ilog2_u64"]
axiom rust_primitives.arithmetic.ilog2_u64 : Std.U64 → Result Std.U32

/-- [rust_primitives::arithmetic::ilog2_u128]:
    Source: 'rust_primitives/src/lib.rs', lines 174:16-174:56
    Name pattern: [rust_primitives::arithmetic::ilog2_u128]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::ilog2_u128"]
axiom rust_primitives.arithmetic.ilog2_u128 : Std.U128 → Result Std.U32

/-- [rust_primitives::arithmetic::ilog2_usize]:
    Source: 'rust_primitives/src/lib.rs', lines 174:16-174:56
    Name pattern: [rust_primitives::arithmetic::ilog2_usize]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::ilog2_usize"]
axiom rust_primitives.arithmetic.ilog2_usize : Std.Usize → Result Std.U32

/-- [rust_primitives::arithmetic::ilog2_i8]:
    Source: 'rust_primitives/src/lib.rs', lines 174:16-174:56
    Name pattern: [rust_primitives::arithmetic::ilog2_i8]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::ilog2_i8"]
axiom rust_primitives.arithmetic.ilog2_i8 : Std.I8 → Result Std.U32

/-- [rust_primitives::arithmetic::ilog2_i16]:
    Source: 'rust_primitives/src/lib.rs', lines 174:16-174:56
    Name pattern: [rust_primitives::arithmetic::ilog2_i16]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::ilog2_i16"]
axiom rust_primitives.arithmetic.ilog2_i16 : Std.I16 → Result Std.U32

/-- [rust_primitives::arithmetic::ilog2_i32]:
    Source: 'rust_primitives/src/lib.rs', lines 174:16-174:56
    Name pattern: [rust_primitives::arithmetic::ilog2_i32]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::ilog2_i32"]
axiom rust_primitives.arithmetic.ilog2_i32 : Std.I32 → Result Std.U32

/-- [rust_primitives::arithmetic::ilog2_i64]:
    Source: 'rust_primitives/src/lib.rs', lines 174:16-174:56
    Name pattern: [rust_primitives::arithmetic::ilog2_i64]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::ilog2_i64"]
axiom rust_primitives.arithmetic.ilog2_i64 : Std.I64 → Result Std.U32

/-- [rust_primitives::arithmetic::ilog2_i128]:
    Source: 'rust_primitives/src/lib.rs', lines 174:16-174:56
    Name pattern: [rust_primitives::arithmetic::ilog2_i128]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::ilog2_i128"]
axiom rust_primitives.arithmetic.ilog2_i128 : Std.I128 → Result Std.U32

/-- [rust_primitives::arithmetic::ilog2_isize]:
    Source: 'rust_primitives/src/lib.rs', lines 174:16-174:56
    Name pattern: [rust_primitives::arithmetic::ilog2_isize]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::ilog2_isize"]
axiom rust_primitives.arithmetic.ilog2_isize : Std.Isize → Result Std.U32

/-- [rust_primitives::arithmetic::to_be_bytes_u8]:
    Source: 'rust_primitives/src/lib.rs', lines 183:16-183:75
    Name pattern: [rust_primitives::arithmetic::to_be_bytes_u8]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::to_be_bytes_u8"]
axiom rust_primitives.arithmetic.to_be_bytes_u8
  : Std.U8 → Result (Array Std.U8 1#usize)

/-- [rust_primitives::arithmetic::to_be_bytes_u16]:
    Source: 'rust_primitives/src/lib.rs', lines 183:16-183:75
    Name pattern: [rust_primitives::arithmetic::to_be_bytes_u16]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::to_be_bytes_u16"]
axiom rust_primitives.arithmetic.to_be_bytes_u16
  : Std.U16 → Result (Array Std.U8 2#usize)

/-- [rust_primitives::arithmetic::to_be_bytes_u32]:
    Source: 'rust_primitives/src/lib.rs', lines 183:16-183:75
    Name pattern: [rust_primitives::arithmetic::to_be_bytes_u32]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::to_be_bytes_u32"]
axiom rust_primitives.arithmetic.to_be_bytes_u32
  : Std.U32 → Result (Array Std.U8 4#usize)

/-- [rust_primitives::arithmetic::to_be_bytes_u64]:
    Source: 'rust_primitives/src/lib.rs', lines 183:16-183:75
    Name pattern: [rust_primitives::arithmetic::to_be_bytes_u64]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::to_be_bytes_u64"]
axiom rust_primitives.arithmetic.to_be_bytes_u64
  : Std.U64 → Result (Array Std.U8 8#usize)

/-- [rust_primitives::arithmetic::to_be_bytes_u128]:
    Source: 'rust_primitives/src/lib.rs', lines 183:16-183:75
    Name pattern: [rust_primitives::arithmetic::to_be_bytes_u128]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::to_be_bytes_u128"]
axiom rust_primitives.arithmetic.to_be_bytes_u128
  : Std.U128 → Result (Array Std.U8 16#usize)

/-- [rust_primitives::arithmetic::to_be_bytes_usize]:
    Source: 'rust_primitives/src/lib.rs', lines 183:16-183:75
    Name pattern: [rust_primitives::arithmetic::to_be_bytes_usize]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::to_be_bytes_usize"]
axiom rust_primitives.arithmetic.to_be_bytes_usize
  : Std.Usize → Result (Array Std.U8 8#usize)

/-- [rust_primitives::arithmetic::to_be_bytes_i8]:
    Source: 'rust_primitives/src/lib.rs', lines 183:16-183:75
    Name pattern: [rust_primitives::arithmetic::to_be_bytes_i8]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::to_be_bytes_i8"]
axiom rust_primitives.arithmetic.to_be_bytes_i8
  : Std.I8 → Result (Array Std.U8 1#usize)

/-- [rust_primitives::arithmetic::to_be_bytes_i16]:
    Source: 'rust_primitives/src/lib.rs', lines 183:16-183:75
    Name pattern: [rust_primitives::arithmetic::to_be_bytes_i16]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::to_be_bytes_i16"]
axiom rust_primitives.arithmetic.to_be_bytes_i16
  : Std.I16 → Result (Array Std.U8 2#usize)

/-- [rust_primitives::arithmetic::to_be_bytes_i32]:
    Source: 'rust_primitives/src/lib.rs', lines 183:16-183:75
    Name pattern: [rust_primitives::arithmetic::to_be_bytes_i32]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::to_be_bytes_i32"]
axiom rust_primitives.arithmetic.to_be_bytes_i32
  : Std.I32 → Result (Array Std.U8 4#usize)

/-- [rust_primitives::arithmetic::to_be_bytes_i64]:
    Source: 'rust_primitives/src/lib.rs', lines 183:16-183:75
    Name pattern: [rust_primitives::arithmetic::to_be_bytes_i64]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::to_be_bytes_i64"]
axiom rust_primitives.arithmetic.to_be_bytes_i64
  : Std.I64 → Result (Array Std.U8 8#usize)

/-- [rust_primitives::arithmetic::to_be_bytes_i128]:
    Source: 'rust_primitives/src/lib.rs', lines 183:16-183:75
    Name pattern: [rust_primitives::arithmetic::to_be_bytes_i128]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::to_be_bytes_i128"]
axiom rust_primitives.arithmetic.to_be_bytes_i128
  : Std.I128 → Result (Array Std.U8 16#usize)

/-- [rust_primitives::arithmetic::to_be_bytes_isize]:
    Source: 'rust_primitives/src/lib.rs', lines 183:16-183:75
    Name pattern: [rust_primitives::arithmetic::to_be_bytes_isize]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::to_be_bytes_isize"]
axiom rust_primitives.arithmetic.to_be_bytes_isize
  : Std.Isize → Result (Array Std.U8 8#usize)

/-- [rust_primitives::arithmetic::to_le_bytes_u8]:
    Source: 'rust_primitives/src/lib.rs', lines 186:16-186:75
    Name pattern: [rust_primitives::arithmetic::to_le_bytes_u8]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::to_le_bytes_u8"]
axiom rust_primitives.arithmetic.to_le_bytes_u8
  : Std.U8 → Result (Array Std.U8 1#usize)

/-- [rust_primitives::arithmetic::to_le_bytes_u16]:
    Source: 'rust_primitives/src/lib.rs', lines 186:16-186:75
    Name pattern: [rust_primitives::arithmetic::to_le_bytes_u16]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::to_le_bytes_u16"]
axiom rust_primitives.arithmetic.to_le_bytes_u16
  : Std.U16 → Result (Array Std.U8 2#usize)

/-- [rust_primitives::arithmetic::to_le_bytes_u32]:
    Source: 'rust_primitives/src/lib.rs', lines 186:16-186:75
    Name pattern: [rust_primitives::arithmetic::to_le_bytes_u32]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::to_le_bytes_u32"]
axiom rust_primitives.arithmetic.to_le_bytes_u32
  : Std.U32 → Result (Array Std.U8 4#usize)

/-- [rust_primitives::arithmetic::to_le_bytes_u64]:
    Source: 'rust_primitives/src/lib.rs', lines 186:16-186:75
    Name pattern: [rust_primitives::arithmetic::to_le_bytes_u64]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::to_le_bytes_u64"]
axiom rust_primitives.arithmetic.to_le_bytes_u64
  : Std.U64 → Result (Array Std.U8 8#usize)

/-- [rust_primitives::arithmetic::to_le_bytes_u128]:
    Source: 'rust_primitives/src/lib.rs', lines 186:16-186:75
    Name pattern: [rust_primitives::arithmetic::to_le_bytes_u128]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::to_le_bytes_u128"]
axiom rust_primitives.arithmetic.to_le_bytes_u128
  : Std.U128 → Result (Array Std.U8 16#usize)

/-- [rust_primitives::arithmetic::to_le_bytes_usize]:
    Source: 'rust_primitives/src/lib.rs', lines 186:16-186:75
    Name pattern: [rust_primitives::arithmetic::to_le_bytes_usize]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::to_le_bytes_usize"]
axiom rust_primitives.arithmetic.to_le_bytes_usize
  : Std.Usize → Result (Array Std.U8 8#usize)

/-- [rust_primitives::arithmetic::to_le_bytes_i8]:
    Source: 'rust_primitives/src/lib.rs', lines 186:16-186:75
    Name pattern: [rust_primitives::arithmetic::to_le_bytes_i8]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::to_le_bytes_i8"]
axiom rust_primitives.arithmetic.to_le_bytes_i8
  : Std.I8 → Result (Array Std.U8 1#usize)

/-- [rust_primitives::arithmetic::to_le_bytes_i16]:
    Source: 'rust_primitives/src/lib.rs', lines 186:16-186:75
    Name pattern: [rust_primitives::arithmetic::to_le_bytes_i16]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::to_le_bytes_i16"]
axiom rust_primitives.arithmetic.to_le_bytes_i16
  : Std.I16 → Result (Array Std.U8 2#usize)

/-- [rust_primitives::arithmetic::to_le_bytes_i32]:
    Source: 'rust_primitives/src/lib.rs', lines 186:16-186:75
    Name pattern: [rust_primitives::arithmetic::to_le_bytes_i32]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::to_le_bytes_i32"]
axiom rust_primitives.arithmetic.to_le_bytes_i32
  : Std.I32 → Result (Array Std.U8 4#usize)

/-- [rust_primitives::arithmetic::to_le_bytes_i64]:
    Source: 'rust_primitives/src/lib.rs', lines 186:16-186:75
    Name pattern: [rust_primitives::arithmetic::to_le_bytes_i64]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::to_le_bytes_i64"]
axiom rust_primitives.arithmetic.to_le_bytes_i64
  : Std.I64 → Result (Array Std.U8 8#usize)

/-- [rust_primitives::arithmetic::to_le_bytes_i128]:
    Source: 'rust_primitives/src/lib.rs', lines 186:16-186:75
    Name pattern: [rust_primitives::arithmetic::to_le_bytes_i128]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::to_le_bytes_i128"]
axiom rust_primitives.arithmetic.to_le_bytes_i128
  : Std.I128 → Result (Array Std.U8 16#usize)

/-- [rust_primitives::arithmetic::to_le_bytes_isize]:
    Source: 'rust_primitives/src/lib.rs', lines 186:16-186:75
    Name pattern: [rust_primitives::arithmetic::to_le_bytes_isize]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::to_le_bytes_isize"]
axiom rust_primitives.arithmetic.to_le_bytes_isize
  : Std.Isize → Result (Array Std.U8 8#usize)

/-- [rust_primitives::arithmetic::abs_i8]:
    Source: 'rust_primitives/src/lib.rs', lines 197:20-197:39
    Name pattern: [rust_primitives::arithmetic::abs_i8]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::abs_i8"]
axiom rust_primitives.arithmetic.abs_i8 : Std.I8 → Result Std.I8

/-- [rust_primitives::arithmetic::abs_i16]:
    Source: 'rust_primitives/src/lib.rs', lines 197:20-197:39
    Name pattern: [rust_primitives::arithmetic::abs_i16]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::abs_i16"]
axiom rust_primitives.arithmetic.abs_i16 : Std.I16 → Result Std.I16

/-- [rust_primitives::arithmetic::abs_i32]:
    Source: 'rust_primitives/src/lib.rs', lines 197:20-197:39
    Name pattern: [rust_primitives::arithmetic::abs_i32]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::abs_i32"]
axiom rust_primitives.arithmetic.abs_i32 : Std.I32 → Result Std.I32

/-- [rust_primitives::arithmetic::abs_i64]:
    Source: 'rust_primitives/src/lib.rs', lines 197:20-197:39
    Name pattern: [rust_primitives::arithmetic::abs_i64]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::abs_i64"]
axiom rust_primitives.arithmetic.abs_i64 : Std.I64 → Result Std.I64

/-- [rust_primitives::arithmetic::abs_i128]:
    Source: 'rust_primitives/src/lib.rs', lines 197:20-197:39
    Name pattern: [rust_primitives::arithmetic::abs_i128]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::abs_i128"]
axiom rust_primitives.arithmetic.abs_i128 : Std.I128 → Result Std.I128

/-- [rust_primitives::arithmetic::abs_isize]:
    Source: 'rust_primitives/src/lib.rs', lines 197:20-197:39
    Name pattern: [rust_primitives::arithmetic::abs_isize]
    Visibility: public -/
@[rust_fun "rust_primitives::arithmetic::abs_isize"]
axiom rust_primitives.arithmetic.abs_isize : Std.Isize → Result Std.Isize

/-- [rust_primitives::arithmetic::SIZE_BITS]
    Source: 'rust_primitives/src/lib.rs', lines 208:4-208:28
    Name pattern: [rust_primitives::arithmetic::SIZE_BITS]
    Visibility: public -/
@[rust_const "rust_primitives::arithmetic::SIZE_BITS"]
axiom rust_primitives.arithmetic.SIZE_BITS : Result Std.U32

/-- [rust_primitives::arithmetic::USIZE_MAX]
    Source: 'rust_primitives/src/lib.rs', lines 209:4-209:30
    Name pattern: [rust_primitives::arithmetic::USIZE_MAX]
    Visibility: public -/
@[rust_const "rust_primitives::arithmetic::USIZE_MAX"]
axiom rust_primitives.arithmetic.USIZE_MAX : Result Std.Usize

/-- [rust_primitives::arithmetic::ISIZE_MAX]
    Source: 'rust_primitives/src/lib.rs', lines 210:4-210:30
    Name pattern: [rust_primitives::arithmetic::ISIZE_MAX]
    Visibility: public -/
@[rust_const "rust_primitives::arithmetic::ISIZE_MAX"]
axiom rust_primitives.arithmetic.ISIZE_MAX : Result Std.Isize

/-- [rust_primitives::arithmetic::ISIZE_MIN]
    Source: 'rust_primitives/src/lib.rs', lines 211:4-211:30
    Name pattern: [rust_primitives::arithmetic::ISIZE_MIN]
    Visibility: public -/
@[rust_const "rust_primitives::arithmetic::ISIZE_MIN"]
axiom rust_primitives.arithmetic.ISIZE_MIN : Result Std.Isize

/-- [alloc::string::{alloc::string::String}::new]:
    Source: '/rustc/library/alloc/src/string.rs', lines 437:4-437:32
    Name pattern: [alloc::string::{alloc::string::String}::new]
    Visibility: public -/
@[rust_fun "alloc::string::{alloc::string::String}::new"]
axiom alloc.string.String.new : Result String

/-- [rust_primitives::sequence::seq_empty]:
    Source: '/home/alex/Projects/rust-core-models/lean/rust_primitives/src/lib.rs', lines 48:4-48:35
    Name pattern: [rust_primitives::sequence::seq_empty]
    Visibility: public -/
@[rust_fun "rust_primitives::sequence::seq_empty"]
axiom rust_primitives.sequence.seq_empty
  (T : Type) : Result (rust_primitives.sequence.Seq T)

/-- [rust_primitives::sequence::seq_from_boxed_slice]:
    Source: '/home/alex/Projects/rust-core-models/lean/rust_primitives/src/lib.rs', lines 54:4-54:57
    Name pattern: [rust_primitives::sequence::seq_from_boxed_slice]
    Visibility: public -/
@[rust_fun "rust_primitives::sequence::seq_from_boxed_slice"]
axiom rust_primitives.sequence.seq_from_boxed_slice
  {T : Type} : Slice T → Result (rust_primitives.sequence.Seq T)

/-- [rust_primitives::sequence::seq_to_slice]:
    Source: '/home/alex/Projects/rust-core-models/lean/rust_primitives/src/lib.rs', lines 60:4-60:46
    Name pattern: [rust_primitives::sequence::seq_to_slice]
    Visibility: public -/
@[rust_fun "rust_primitives::sequence::seq_to_slice"]
axiom rust_primitives.sequence.seq_to_slice
  {T : Type} : rust_primitives.sequence.Seq T → Result (Slice T)

/-- [rust_primitives::sequence::seq_concat]:
    Source: '/home/alex/Projects/rust-core-models/lean/rust_primitives/src/lib.rs', lines 63:4-63:58
    Name pattern: [rust_primitives::sequence::seq_concat]
    Visibility: public -/
@[rust_fun "rust_primitives::sequence::seq_concat"]
axiom rust_primitives.sequence.seq_concat
  {T : Type} :
  rust_primitives.sequence.Seq T → rust_primitives.sequence.Seq T → Result
    ((rust_primitives.sequence.Seq T) × (rust_primitives.sequence.Seq T))

/-- [rust_primitives::sequence::seq_extend]:
    Source: '/home/alex/Projects/rust-core-models/lean/rust_primitives/src/lib.rs', lines 66:4-68:17
    Name pattern: [rust_primitives::sequence::seq_extend]
    Visibility: public -/
@[rust_fun "rust_primitives::sequence::seq_extend"]
axiom rust_primitives.sequence.seq_extend
  {T : Type} (corecloneCloneInst : core.clone.Clone T) :
  rust_primitives.sequence.Seq T → Slice T → Result
    (rust_primitives.sequence.Seq T)

/-- [rust_primitives::sequence::seq_push]:
    Source: '/home/alex/Projects/rust-core-models/lean/rust_primitives/src/lib.rs', lines 72:4-72:45
    Name pattern: [rust_primitives::sequence::seq_push]
    Visibility: public -/
@[rust_fun "rust_primitives::sequence::seq_push"]
axiom rust_primitives.sequence.seq_push
  {T : Type} :
  rust_primitives.sequence.Seq T → T → Result (rust_primitives.sequence.Seq
    T)

/-- [rust_primitives::sequence::seq_create]:
    Source: '/home/alex/Projects/rust-core-models/lean/rust_primitives/src/lib.rs', lines 78:4-78:57
    Name pattern: [rust_primitives::sequence::seq_create]
    Visibility: public -/
@[rust_fun "rust_primitives::sequence::seq_create"]
axiom rust_primitives.sequence.seq_create
  {T : Type} (corecloneCloneInst : core.clone.Clone T) :
  T → Std.Usize → Result (rust_primitives.sequence.Seq T)

/-- [rust_primitives::sequence::seq_drain]:
    Source: '/home/alex/Projects/rust-core-models/lean/rust_primitives/src/lib.rs', lines 84:4-84:69
    Name pattern: [rust_primitives::sequence::seq_drain]
    Visibility: public -/
@[rust_fun "rust_primitives::sequence::seq_drain"]
axiom rust_primitives.sequence.seq_drain
  {T : Type} :
  rust_primitives.sequence.Seq T → Std.Usize → Std.Usize → Result
    ((rust_primitives.sequence.Seq T) × (rust_primitives.sequence.Seq T))

/-- [rust_primitives::sequence::seq_index]:
    Source: '/home/alex/Projects/rust-core-models/lean/rust_primitives/src/lib.rs', lines 90:4-90:51
    Name pattern: [rust_primitives::sequence::seq_index]
    Visibility: public -/
@[rust_fun "rust_primitives::sequence::seq_index"]
axiom rust_primitives.sequence.seq_index
  {T : Type} : rust_primitives.sequence.Seq T → Std.Usize → Result T

end CoreModels
