-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [core_models]: external types.
-- This is a template file: rename it to "TypesExternal.lean" and fill the holes.
import Aeneas
import CoreModels.Command
import CoreModels.Primitives
open Aeneas
open Aeneas.Std hiding namespace core
open Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/-- [rust_primitives::sequence::Seq]
    Source: 'rust_primitives/src/lib.rs', lines 47:4-47:21
    Name pattern: [rust_primitives::sequence::Seq]
    Visibility: public -/
@[rust_type "rust_primitives::sequence::Seq"]
axiom rust_primitives.sequence.Seq (T : Type) : Type

