-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [core_models]: type definitions
import Aeneas
import CoreModels.Command
import CoreModels.TypesPrologue
import CoreModels.TypesExternal
open Aeneas
open Aeneas.Std hiding namespace core alloc
open Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

namespace core_models

/-- [core_models::array::TryFromSliceError]
    Source: 'core-models/src/core/array.rs', lines 4:0-4:29
    Visibility: public -/
@[reducible]
def array.TryFromSliceError := Unit

/-- [core_models::array::Dummy]
    Source: 'core-models/src/core/array.rs', lines 8:0-8:40 -/
@[reducible]
def array.Dummy (T : Type) (N : Std.Usize) := Array T N

/-- [core_models::array::{core_models::array::Dummy<T, N>}::each_ref::closure]
    Source: 'core-models/src/core/array.rs', lines 46:22-46:43 -/
@[reducible]
def array.Dummy.each_ref.closure (T : Type) (N : Std.Usize) := Array T N

/-- Trait declaration: [core_models::iter::traits::collect::IntoIterator]
    Source: 'core-models/src/core/iter.rs', lines 385:8-394:9
    Visibility: public -/
structure iter.traits.collect.IntoIterator (Self : Type) (Self_Item : Type)
  (Self_IntoIter : Type) where
  into_iter : Self → Result Self_IntoIter

/-- [core_models::array::iter::IntoIter]
    Source: 'core-models/src/core/array.rs', lines 145:4-145:55
    Visibility: public -/
@[reducible]
def array.iter.IntoIter (T : Type) (N : Std.Usize) :=
  rust_primitives.sequence.Seq T

/-- Trait declaration: [core_models::ops::index::Index]
    Source: 'core-models/src/core/ops.rs', lines 144:4-147:5
    Visibility: public -/
structure ops.index.Index (Self : Type) (Idx : Type) (Self_Output : Type) where
  index : Self → Idx → Result Self_Output

/-- [core_models::ops::range::Range]
    Source: 'core-models/src/core/ops.rs', lines 293:4-296:5
    Visibility: public -/
structure ops.range.Range (T : Type) where
  start : T
  «end» : T

/-- [core_models::ops::range::RangeTo]
    Source: 'core-models/src/core/ops.rs', lines 285:4-287:5
    Visibility: public -/
structure ops.range.RangeTo (T : Type) where
  «end» : T

/-- [core_models::ops::range::RangeFrom]
    Source: 'core-models/src/core/ops.rs', lines 289:4-291:5
    Visibility: public -/
structure ops.range.RangeFrom (T : Type) where
  start : T

/-- [core_models::ops::range::RangeFull]
    Source: 'core-models/src/core/ops.rs', lines 298:4-298:25
    Visibility: public -/
@[reducible]
def ops.range.RangeFull := Unit

/-- Trait declaration: [core_models::clone::Clone]
    Source: 'core-models/src/core/clone.rs', lines 13:0-16:1
    Visibility: public -/
structure clone.Clone (Self : Type) where
  clone : Self → Result Self

/-- Trait declaration: [core_models::cmp::PartialEq]
    Source: 'core-models/src/core/cmp.rs', lines 5:0-12:1
    Visibility: public -/
structure cmp.PartialEq (Self : Type) (Rhs : Type) where
  eq : Self → Rhs → Result Bool

/-
/-- [core_models::option::Option]
    Source: 'core-models/src/core/option.rs', lines 3:0-8:1
    Visibility: public -/
@[discriminant isize]
inductive option.Option (T : Type) where
| Some : T → option.Option T
| None : option.Option T
-/

/-- Trait declaration: [core_models::iter::traits::iterator::Iterator]
    Source: 'core-models/src/core/iter.rs', lines 15:8-19:9
    Visibility: public -/
structure iter.traits.iterator.Iterator (Self : Type) (Self_Item : Type) where
  next : Self → Result ((option.Option Self_Item) × Self)

/-- Trait declaration: [core_models::borrow::Borrow]
    Source: 'core-models/src/core/borrow.rs', lines 2:0-5:1 -/
structure borrow.Borrow (Self : Type) (Borrowed : Type) where
  borrow : Self → Result Borrowed

/-- Trait declaration: [core_models::cmp::Eq]
    Source: 'core-models/src/core/cmp.rs', lines 15:0-15:32
    Visibility: public -/
structure cmp.Eq (Self : Type) where
  PartialEqInst : cmp.PartialEq Self Self

/-
/-- [core_models::cmp::Ordering]
    Source: 'core-models/src/core/cmp.rs', lines 19:0-26:1
    Visibility: public -/
@[discriminant isize [-1,0,1]]
inductive cmp.Ordering where
| Less : cmp.Ordering
| Equal : cmp.Ordering
| Greater : cmp.Ordering
-/

/-- Trait declaration: [core_models::cmp::PartialOrd]
    Source: 'core-models/src/core/cmp.rs', lines 30:0-37:1
    Visibility: public -/
structure cmp.PartialOrd (Self : Type) (Rhs : Type) where
  PartialEqInst : cmp.PartialEq Self Rhs
  partial_cmp : Self → Rhs → Result (option.Option cmp.Ordering)

/-- Trait declaration: [core_models::cmp::Neq]
    Source: 'core-models/src/core/cmp.rs', lines 42:0-45:1 -/
structure cmp.Neq (Self : Type) (Rhs : Type) where
  neq : Self → Rhs → Result Bool

/-- Trait declaration: [core_models::cmp::PartialOrdDefaults]
    Source: 'core-models/src/core/cmp.rs', lines 55:0-72:1 -/
structure cmp.PartialOrdDefaults (Self : Type) (Rhs : Type) where
  lt : forall (PartialOrdInst : cmp.PartialOrd Self Rhs), Self → Rhs →
    Result Bool
  le : forall (PartialOrdInst : cmp.PartialOrd Self Rhs), Self → Rhs →
    Result Bool
  gt : forall (PartialOrdInst : cmp.PartialOrd Self Rhs), Self → Rhs →
    Result Bool
  ge : forall (PartialOrdInst : cmp.PartialOrd Self Rhs), Self → Rhs →
    Result Bool

/-- Trait declaration: [core_models::cmp::Ord]
    Source: 'core-models/src/core/cmp.rs', lines 109:0-113:1
    Visibility: public -/
structure cmp.Ord (Self : Type) where
  EqInst : cmp.Eq Self
  PartialOrdInst : cmp.PartialOrd Self Self
  cmp : Self → Self → Result cmp.Ordering

/-- [core_models::cmp::Reverse]
    Source: 'core-models/src/core/cmp.rs', lines 132:0-132:29
    Visibility: public -/
@[reducible]
def cmp.Reverse (T : Type) := T

/-
/-- [core_models::result::Result]
    Source: 'core-models/src/core/result.rs', lines 3:0-8:1
    Visibility: public -/
@[discriminant isize]
inductive result.Result (T : Type) (E : Type) where
| Ok : T → result.Result T E
| Err : E → result.Result T E
-/

/-- Trait declaration: [core_models::convert::TryInto]
    Source: 'core-models/src/core/convert.rs', lines 5:0-10:1 -/
structure convert.TryInto (Self : Type) (T : Type) (Self_Error : Type) where
  try_into : Self → Result (result.Result T Self_Error)

/-- Trait declaration: [core_models::convert::Into]
    Source: 'core-models/src/core/convert.rs', lines 14:0-18:1 -/
structure convert.Into (Self : Type) (T : Type) where
  into : Self → Result T

/-- Trait declaration: [core_models::convert::From]
    Source: 'core-models/src/core/convert.rs', lines 22:0-26:1 -/
structure convert.From (Self : Type) (T : Type) where
  «from» : T → Result Self

/-- Trait declaration: [core_models::convert::TryFrom]
    Source: 'core-models/src/core/convert.rs', lines 30:0-35:1
    Visibility: public -/
structure convert.TryFrom (Self : Type) (T : Type) (Self_Error : Type) where
  try_from : T → Result (result.Result Self Self_Error)

/-- [core_models::convert::Infallible]
    Source: 'core-models/src/core/convert.rs', lines 44:0-44:22
    Visibility: public -/
@[reducible]
def convert.Infallible := Unit

/-- [core_models::convert::{core_models::convert::TryFrom<&0 ([T]), core_models::array::TryFromSliceError> for [T; N]}::try_from::closure]
    Source: 'core-models/src/core/convert.rs', lines 59:61-61:13 -/
@[reducible]
def convert.TryFromArrayShared0SliceTryFromSliceError.try_from.closure (T :
  Type) (N : Std.Usize) :=
  Slice T

/-- Trait declaration: [core_models::convert::AsRef]
    Source: 'core-models/src/core/convert.rs', lines 83:0-87:1 -/
structure convert.AsRef (Self : Type) (T : Type) where
  as_ref : Self → Result T

/-- [core_models::num::error::TryFromIntError]
    Source: 'core-models/src/core/num/error.rs', lines 6:0-6:42
    Visibility: public -/
@[reducible]
def num.error.TryFromIntError := Unit

/-- Trait declaration: [core_models::default::Default]
    Source: 'core-models/src/core/default.rs', lines 3:0-7:1
    Visibility: public -/
structure default.Default (Self : Type) where
  default : Result Self

/-- [core_models::fmt::Formatter]
    Source: 'core-models/src/core/fmt.rs', lines 10:0-10:21
    Visibility: public -/
@[reducible]
def fmt.Formatter := Unit

/-- [core_models::fmt::Error]
    Source: 'core-models/src/core/fmt.rs', lines 4:0-4:17
    Visibility: public -/
@[reducible]
def fmt.Error := Unit

/-- Trait declaration: [core_models::fmt::Debug]
    Source: 'core-models/src/core/fmt.rs', lines 19:0-22:1
    Visibility: public -/
structure fmt.Debug (Self : Type) where
  dbg_fmt : Self → fmt.Formatter → Result ((result.Result Unit fmt.Error)
    × fmt.Formatter)

/-- Trait declaration: [core_models::fmt::Display]
    Source: 'core-models/src/core/fmt.rs', lines 13:0-16:1
    Visibility: public -/
structure fmt.Display (Self : Type) where
  fmt : Self → fmt.Formatter → Result ((result.Result Unit fmt.Error) ×
    fmt.Formatter)

/-- Trait declaration: [core_models::error::Error]
    Source: 'core-models/src/core/error.rs', lines 4:0-4:35
    Visibility: public -/
structure error.Error (Self : Type) where
  fmtDisplayInst : fmt.Display Self
  fmtDebugInst : fmt.Debug Self

/-- [core_models::f32::f32]
    Source: 'core-models/src/core/f32.rs', lines 4:0-4:11 -/
@[reducible]
def f32.f32 := Unit

/-- [core_models::fmt::Arguments]
    Source: 'core-models/src/core/fmt.rs', lines 25:0-25:33
    Visibility: public -/
@[reducible]
def fmt.Arguments := Unit

/-- [core_models::fmt::rt::ArgumentType]
    Source: 'core-models/src/core/fmt.rs', lines 52:4-59:5 -/
@[discriminant isize]
inductive fmt.rt.ArgumentType where
| Placeholder : core_models.Phantom Unit → fmt.rt.ArgumentType

/-- [core_models::fmt::rt::Argument]
    Source: 'core-models/src/core/fmt.rs', lines 61:4-63:5
    Visibility: public -/
structure fmt.rt.Argument where
  ty : fmt.rt.ArgumentType

/-- [core_models::fmt::rt::Count]
    Source: 'core-models/src/core/fmt.rs', lines 101:4-105:5 -/
@[discriminant isize]
inductive fmt.rt.Count where
| Is : Std.U16 → fmt.rt.Count
| Param : Std.U16 → fmt.rt.Count
| Implied : fmt.rt.Count

/-- [core_models::fmt::rt::Placeholder]
    Source: 'core-models/src/core/fmt.rs', lines 107:4-112:5 -/
structure fmt.rt.Placeholder where
  position : Std.Usize
  flags : Std.U32
  precision : fmt.rt.Count
  width : fmt.rt.Count

/-- [core_models::fmt::rt::UnsafeArg]
    Source: 'core-models/src/core/fmt.rs', lines 114:4-114:21 -/
@[reducible]
def fmt.rt.UnsafeArg := Unit

/-- Trait declaration: [core_models::hash::Hasher]
    Source: 'core-models/src/core/hash.rs', lines 2:0-2:19
    Visibility: public -/
structure hash.Hasher (Self : Type) where

/-- Trait declaration: [core_models::hash::Hash]
    Source: 'core-models/src/core/hash.rs', lines 6:0-10:1
    Visibility: public -/
structure hash.Hash (Self : Type) where
  hash : forall {H : Type} (HasherInst : hash.Hasher H), Self → H → Result
    H

/-- [core_models::iter::adapters::skip::Skip]
    Source: 'core-models/src/core/iter.rs', lines 696:8-699:9
    Visibility: public -/
structure iter.adapters.skip.Skip (I : Type) where
  iter : I
  n : Std.Usize

/-- [core_models::iter::adapters::chain::Chain]
    Source: 'core-models/src/core/iter.rs', lines 665:8-668:9
    Visibility: public -/
structure iter.adapters.chain.Chain (A : Type) (B : Type) where
  a : option.Option A
  b : B

/-- [core_models::iter::adapters::filter::Filter]
    Source: 'core-models/src/core/iter.rs', lines 632:8-635:9
    Visibility: public -/
structure iter.adapters.filter.Filter (I : Type) (P : Type) where
  iter : I
  predicate : P

/-- [core_models::iter::adapters::zip::Zip]
    Source: 'core-models/src/core/iter.rs', lines 605:8-608:9
    Visibility: public -/
structure iter.adapters.zip.Zip (I1 : Type) (I2 : Type) where
  it1 : I1
  it2 : I2

/-- [core_models::iter::adapters::flatten::Flatten]
    Source: 'core-models/src/core/iter.rs', lines 561:8-567:9
    Visibility: public -/
structure iter.adapters.flatten.Flatten (I : Type) (Clause0_Item : Type)
  (Clause1_Item : Type) where
  it : I
  current : option.Option Clause0_Item

/-- [core_models::iter::adapters::flat_map::FlatMap]
    Source: 'core-models/src/core/iter.rs', lines 523:8-527:9
    Visibility: public -/
structure iter.adapters.flat_map.FlatMap (I : Type) (U : Type) (F : Type) where
  it : I
  f : F
  current : option.Option U

/-- [core_models::iter::adapters::take::Take]
    Source: 'core-models/src/core/iter.rs', lines 496:8-499:9
    Visibility: public -/
structure iter.adapters.take.Take (I : Type) where
  iter : I
  n : Std.Usize

/-- [core_models::iter::adapters::map::Map]
    Source: 'core-models/src/core/iter.rs', lines 469:8-472:9
    Visibility: public -/
structure iter.adapters.map.Map (I : Type) (F : Type) where
  iter : I
  f : F

/-- [core_models::iter::adapters::step_by::StepBy]
    Source: 'core-models/src/core/iter.rs', lines 441:8-444:9
    Visibility: public -/
structure iter.adapters.step_by.StepBy (I : Type) where
  iter : I
  step : Std.Usize

/-- [core_models::iter::adapters::enumerate::Enumerate]
    Source: 'core-models/src/core/iter.rs', lines 409:8-412:9
    Visibility: public -/
structure iter.adapters.enumerate.Enumerate (I : Type) where
  iter : I
  count : Std.Usize

/-- Trait declaration: [core_models::iter::traits::collect::FromIterator]
    Source: 'core-models/src/core/iter.rs', lines 397:8-400:9
    Visibility: public -/
structure iter.traits.collect.FromIterator (Self : Type) (A : Type) where
  from_iter : forall {T : Type} {Clause0_Item : Type} {Clause0_IntoIter : Type}
    (IntoIteratorInst : iter.traits.collect.IntoIterator T Clause0_Item
    Clause0_IntoIter), T → Result Self

/-- Trait declaration: [core_models::iter::traits::iterator::IteratorMethods]
    Source: 'core-models/src/core/iter.rs', lines 22:8-77:9 -/
structure iter.traits.iterator.IteratorMethods (Self : Type) (Self_Clause0_Item
  : Type) where
  IteratorInst : iter.traits.iterator.Iterator Self Self_Clause0_Item
  fold : forall {B : Type} {F : Type} (core_modelsopsfunctionFnPPairPInst :
    core_models.ops.function.Fn F (B × Self_Clause0_Item) B), Self → B → F
    → Result B
  enumerate : Self → Result (iter.adapters.enumerate.Enumerate Self)
  step_by : Self → Std.Usize → Result (iter.adapters.step_by.StepBy Self)
  map : forall {O : Type} {F : Type} (core_modelsopsfunctionFnPTupleFPInst :
    core_models.ops.function.Fn F Self_Clause0_Item O), Self → F → Result
    (iter.adapters.map.Map Self F)
  all : forall {F : Type} (core_modelsopsfunctionFnPTuplePBoolInst :
    core_models.ops.function.Fn F Self_Clause0_Item Bool), Self → F →
    Result Bool
  take : Self → Std.Usize → Result (iter.adapters.take.Take Self)
  flat_map : forall {U : Type} {F : Type} {Clause0_Item : Type} (IteratorInst1
    : iter.traits.iterator.Iterator U Clause0_Item)
    (core_modelsopsfunctionFnPTupleFPInst : core_models.ops.function.Fn F
    Self_Clause0_Item U), Self → F → Result (iter.adapters.flat_map.FlatMap
    Self U F)
  flatten : forall {Clause0_Item : Type} (IteratorInst1 :
    iter.traits.iterator.Iterator Self_Clause0_Item Clause0_Item), Self →
    Result (iter.adapters.flatten.Flatten Self Self_Clause0_Item Clause0_Item)
  zip : forall {I2 : Type} {Clause0_Item : Type} (IteratorInst1 :
    iter.traits.iterator.Iterator I2 Clause0_Item), Self → I2 → Result
    (iter.adapters.zip.Zip Self I2)
  filter : forall {P : Type} (core_modelsopsfunctionFnPTupleSharedPBoolInst :
    core_models.ops.function.Fn P Self_Clause0_Item Bool), Self → P →
    Result (iter.adapters.filter.Filter Self P)
  chain : forall {U : Type} (IteratorInst1 : iter.traits.iterator.Iterator U
    Self_Clause0_Item), Self → U → Result (iter.adapters.chain.Chain Self
    U)
  skip : Self → Std.Usize → Result (iter.adapters.skip.Skip Self)
  any : forall {F : Type} (core_modelsopsfunctionFnPTuplePBoolInst :
    core_models.ops.function.Fn F Self_Clause0_Item Bool), Self → F →
    Result Bool
  find : forall {P : Type} (core_modelsopsfunctionFnPTupleSharedPBoolInst :
    core_models.ops.function.Fn P Self_Clause0_Item Bool), Self → P →
    Result (option.Option Self_Clause0_Item)
  find_map : forall {B : Type} {F : Type}
    (core_modelsopsfunctionFnPTupleFOptionInst : core_models.ops.function.Fn F
    Self_Clause0_Item (option.Option B)), Self → F → Result (option.Option
    B)
  position : forall {P : Type} (core_modelsopsfunctionFnPTuplePBoolInst :
    core_models.ops.function.Fn P Self_Clause0_Item Bool), Self → P →
    Result (option.Option Std.Usize)
  count : Self → Result Std.Usize
  nth : Self → Std.Usize → Result (option.Option Self_Clause0_Item)
  last : Self → Result (option.Option Self_Clause0_Item)
  for_each : forall {F : Type} (core_modelsopsfunctionFnPTuplePTupleInst :
    core_models.ops.function.Fn F Self_Clause0_Item Unit), Self → F →
    Result Unit
  «reduce» : forall {F : Type} (core_modelsopsfunctionFnPPairPInst :
    core_models.ops.function.Fn F (Self_Clause0_Item × Self_Clause0_Item)
    Self_Clause0_Item), Self → F → Result (option.Option Self_Clause0_Item)
  min : forall (cmpOrdInst : cmp.Ord Self_Clause0_Item), Self → Result
    (option.Option Self_Clause0_Item)
  max : forall (cmpOrdInst : cmp.Ord Self_Clause0_Item), Self → Result
    (option.Option Self_Clause0_Item)
  collect : forall {B : Type} (collectFromIteratorInst :
    iter.traits.collect.FromIterator B Self_Clause0_Item), Self → Result B

/-- Trait declaration: [core_models::iter::range::Step]
    Source: 'core-models/src/core/iter.rs', lines 728:4-748:5
    Visibility: public -/
structure iter.range.Step (Self : Type) where
  cloneCloneInst : clone.Clone Self
  core_modelscmpPartialOrdInst : core_models.cmp.PartialOrd Self Self
  steps_between : Self → Self → Result (Std.Usize × (option.Option
    Std.Usize))
  forward_checked : Self → Std.Usize → Result (option.Option Self)
  backward_checked : Self → Std.Usize → Result (option.Option Self)
  forward : Self → Std.Usize → Result Self
  forward_unchecked : Self → Std.Usize → Result Self
  backward : Self → Std.Usize → Result Self
  backward_unchecked : Self → Std.Usize → Result Self

/-- Trait declaration: [core_models::marker::Copy]
    Source: 'core-models/src/core/marker.rs', lines 4:0-4:24
    Visibility: public -/
structure marker.Copy (Self : Type) where
  cloneCloneInst : clone.Clone Self

/-- Trait declaration: [core_models::marker::Send]
    Source: 'core-models/src/core/marker.rs', lines 6:0-6:17
    Visibility: public -/
structure marker.Send (Self : Type) where

/-- Trait declaration: [core_models::marker::Sync]
    Source: 'core-models/src/core/marker.rs', lines 8:0-8:17
    Visibility: public -/
structure marker.Sync (Self : Type) where

/-- Trait declaration: [core_models::marker::Sized]
    Source: 'core-models/src/core/marker.rs', lines 10:0-10:18
    Visibility: public -/
structure marker.Sized (Self : Type) where

/-- Trait declaration: [core_models::marker::StructuralPartialEq]
    Source: 'core-models/src/core/marker.rs', lines 12:0-12:32
    Visibility: public -/
structure marker.StructuralPartialEq (Self : Type) where

/-
/-- [core_models::marker::PhantomData]
    Source: 'core-models/src/core/marker.rs', lines 48:0-48:25 -/
@[reducible]
def marker.PhantomData (T : Type) := T
-/  -- replaced by core_models.Phantom (see rewrite_alloc_phantom_data)

/-- [core_models::mem::manually_drop::ManuallyDrop]
    Source: 'core-models/src/core/mem.rs', lines 118:4-120:5
    Visibility: public -/
structure mem.manually_drop.ManuallyDrop (T : Type) where
  value : T

/-- [core_models::num::error::IntErrorKind]
    Source: 'core-models/src/core/num/error.rs', lines 24:0-24:24
    Visibility: public -/
@[reducible]
def num.error.IntErrorKind := Unit

/-- [core_models::num::error::ParseIntError]
    Source: 'core-models/src/core/num/error.rs', lines 9:0-11:1
    Visibility: public -/
structure num.error.ParseIntError where
  kind : num.error.IntErrorKind

/-- [core_models::num::u8]
    Source: 'core-models/src/core/num/mod.rs', lines 451:0-451:14
    Visibility: public -/
@[reducible]
def num.u8 := Unit

/-- [core_models::num::u16]
    Source: 'core-models/src/core/num/mod.rs', lines 454:0-454:15
    Visibility: public -/
@[reducible]
def num.u16 := Unit

/-- [core_models::num::u32]
    Source: 'core-models/src/core/num/mod.rs', lines 457:0-457:15
    Visibility: public -/
@[reducible]
def num.u32 := Unit

/-- [core_models::num::u64]
    Source: 'core-models/src/core/num/mod.rs', lines 460:0-460:15
    Visibility: public -/
@[reducible]
def num.u64 := Unit

/-- [core_models::num::u128]
    Source: 'core-models/src/core/num/mod.rs', lines 463:0-463:16
    Visibility: public -/
@[reducible]
def num.u128 := Unit

/-- [core_models::num::usize]
    Source: 'core-models/src/core/num/mod.rs', lines 466:0-466:17
    Visibility: public -/
@[reducible]
def num.usize := Unit

/-- [core_models::num::i8]
    Source: 'core-models/src/core/num/mod.rs', lines 469:0-469:14
    Visibility: public -/
@[reducible]
def num.i8 := Unit

/-- [core_models::num::i16]
    Source: 'core-models/src/core/num/mod.rs', lines 472:0-472:15
    Visibility: public -/
@[reducible]
def num.i16 := Unit

/-- [core_models::num::i32]
    Source: 'core-models/src/core/num/mod.rs', lines 475:0-475:15
    Visibility: public -/
@[reducible]
def num.i32 := Unit

/-- [core_models::num::i64]
    Source: 'core-models/src/core/num/mod.rs', lines 478:0-478:15
    Visibility: public -/
@[reducible]
def num.i64 := Unit

/-- [core_models::num::i128]
    Source: 'core-models/src/core/num/mod.rs', lines 481:0-481:16
    Visibility: public -/
@[reducible]
def num.i128 := Unit

/-- [core_models::num::isize]
    Source: 'core-models/src/core/num/mod.rs', lines 484:0-484:17
    Visibility: public -/
@[reducible]
def num.isize := Unit

/-- Trait declaration: [core_models::ops::arith::Add]
    Source: 'core-models/src/core/ops.rs', lines 3:4-6:5
    Visibility: public -/
structure ops.arith.Add (Self : Type) (Rhs : Type) (Self_Output : Type) where
  add : Self → Rhs → Result Self_Output

/-- Trait declaration: [core_models::ops::arith::Sub]
    Source: 'core-models/src/core/ops.rs', lines 8:4-11:5
    Visibility: public -/
structure ops.arith.Sub (Self : Type) (Rhs : Type) (Self_Output : Type) where
  sub : Self → Rhs → Result Self_Output

/-- Trait declaration: [core_models::ops::arith::Mul]
    Source: 'core-models/src/core/ops.rs', lines 13:4-16:5
    Visibility: public -/
structure ops.arith.Mul (Self : Type) (Rhs : Type) (Self_Output : Type) where
  mul : Self → Rhs → Result Self_Output

/-- Trait declaration: [core_models::ops::arith::Div]
    Source: 'core-models/src/core/ops.rs', lines 18:4-21:5
    Visibility: public -/
structure ops.arith.Div (Self : Type) (Rhs : Type) (Self_Output : Type) where
  div : Self → Rhs → Result Self_Output

/-- Trait declaration: [core_models::ops::arith::Neg]
    Source: 'core-models/src/core/ops.rs', lines 23:4-26:5
    Visibility: public -/
structure ops.arith.Neg (Self : Type) (Self_Output : Type) where
  neg : Self → Result Self_Output

/-- Trait declaration: [core_models::ops::arith::Rem]
    Source: 'core-models/src/core/ops.rs', lines 28:4-31:5
    Visibility: public -/
structure ops.arith.Rem (Self : Type) (Rhs : Type) (Self_Output : Type) where
  rem : Self → Rhs → Result Self_Output

/-- Trait declaration: [core_models::ops::arith::AddAssign]
    Source: 'core-models/src/core/ops.rs', lines 33:4-35:5
    Visibility: public -/
structure ops.arith.AddAssign (Self : Type) (Rhs : Type) where
  add_assign : Self → Rhs → Result Self

/-- Trait declaration: [core_models::ops::arith::SubAssign]
    Source: 'core-models/src/core/ops.rs', lines 37:4-39:5
    Visibility: public -/
structure ops.arith.SubAssign (Self : Type) (Rhs : Type) where
  sub_assign : Self → Rhs → Result Self

/-- Trait declaration: [core_models::ops::arith::MulAssign]
    Source: 'core-models/src/core/ops.rs', lines 41:4-43:5
    Visibility: public -/
structure ops.arith.MulAssign (Self : Type) (Rhs : Type) where
  mul_assign : Self → Rhs → Result Self

/-- Trait declaration: [core_models::ops::arith::DivAssign]
    Source: 'core-models/src/core/ops.rs', lines 45:4-47:5
    Visibility: public -/
structure ops.arith.DivAssign (Self : Type) (Rhs : Type) where
  div_assign : Self → Rhs → Result Self

/-- Trait declaration: [core_models::ops::arith::RemAssign]
    Source: 'core-models/src/core/ops.rs', lines 49:4-51:5
    Visibility: public -/
structure ops.arith.RemAssign (Self : Type) (Rhs : Type) where
  rem_assign : Self → Rhs → Result Self

/-- Trait declaration: [core_models::ops::bit::Shr]
    Source: 'core-models/src/core/ops.rs', lines 81:4-84:5
    Visibility: public -/
structure ops.bit.Shr (Self : Type) (Rhs : Type) (Self_Output : Type) where
  shr : Self → Rhs → Result Self_Output

/-- Trait declaration: [core_models::ops::bit::Shl]
    Source: 'core-models/src/core/ops.rs', lines 86:4-89:5
    Visibility: public -/
structure ops.bit.Shl (Self : Type) (Rhs : Type) (Self_Output : Type) where
  shl : Self → Rhs → Result Self_Output

/-- Trait declaration: [core_models::ops::bit::BitXor]
    Source: 'core-models/src/core/ops.rs', lines 91:4-94:5
    Visibility: public -/
structure ops.bit.BitXor (Self : Type) (Rhs : Type) (Self_Output : Type) where
  bitxor : Self → Rhs → Result Self_Output

/-- Trait declaration: [core_models::ops::bit::BitAnd]
    Source: 'core-models/src/core/ops.rs', lines 96:4-99:5
    Visibility: public -/
structure ops.bit.BitAnd (Self : Type) (Rhs : Type) (Self_Output : Type) where
  bitand : Self → Rhs → Result Self_Output

/-- Trait declaration: [core_models::ops::bit::BitOr]
    Source: 'core-models/src/core/ops.rs', lines 101:4-104:5
    Visibility: public -/
structure ops.bit.BitOr (Self : Type) (Rhs : Type) (Self_Output : Type) where
  bitor : Self → Rhs → Result Self_Output

/-- Trait declaration: [core_models::ops::bit::Not]
    Source: 'core-models/src/core/ops.rs', lines 106:4-109:5
    Visibility: public -/
structure ops.bit.Not (Self : Type) (Self_Output : Type) where
  not : Self → Result Self_Output

/-- Trait declaration: [core_models::ops::bit::ShrAssign]
    Source: 'core-models/src/core/ops.rs', lines 111:4-113:5
    Visibility: public -/
structure ops.bit.ShrAssign (Self : Type) (Rhs : Type) where
  shr_assign : Self → Rhs → Result Self

/-- Trait declaration: [core_models::ops::bit::ShlAssign]
    Source: 'core-models/src/core/ops.rs', lines 115:4-117:5
    Visibility: public -/
structure ops.bit.ShlAssign (Self : Type) (Rhs : Type) where
  shl_assign : Self → Rhs → Result Self

/-- Trait declaration: [core_models::ops::bit::BitXorAssign]
    Source: 'core-models/src/core/ops.rs', lines 119:4-121:5
    Visibility: public -/
structure ops.bit.BitXorAssign (Self : Type) (Rhs : Type) where
  bitxor_assign : Self → Rhs → Result Self

/-- Trait declaration: [core_models::ops::bit::BitAndAssign]
    Source: 'core-models/src/core/ops.rs', lines 123:4-125:5
    Visibility: public -/
structure ops.bit.BitAndAssign (Self : Type) (Rhs : Type) where
  bitand_assign : Self → Rhs → Result Self

/-- Trait declaration: [core_models::ops::bit::BitOrAssign]
    Source: 'core-models/src/core/ops.rs', lines 127:4-129:5
    Visibility: public -/
structure ops.bit.BitOrAssign (Self : Type) (Rhs : Type) where
  bitor_assign : Self → Rhs → Result Self

/-- [core_models::ops::control_flow::ControlFlow]
    Source: 'core-models/src/core/ops.rs', lines 134:4-139:5
    Visibility: public -/
@[discriminant isize]
inductive ops.control_flow.ControlFlow (B : Type) (C : Type) where
| Continue : C → ops.control_flow.ControlFlow B C
| Break : B → ops.control_flow.ControlFlow B C

/-
/-- Trait declaration: [core_models::ops::function::FnOnce]
    Source: 'core-models/src/core/ops.rs', lines 153:4-157:5
    Visibility: public -/
structure ops.function.FnOnce (Self : Type) (Args : Type) (Self_Output : Type)
  where
  call_once : Self → Args → Result Self_Output
-/

/-
/-- Trait declaration: [core_models::ops::function::FnMut]
    Source: 'core-models/src/core/ops.rs', lines 161:4-164:5
    Visibility: public -/
structure ops.function.FnMut (Self : Type) (Args : Type) (Self_Clause0_Output :
  Type) where
  FnOnceInst : ops.function.FnOnce Self Args Self_Clause0_Output
  call_mut : Self → Args → Result Self_Clause0_Output
-/

/-
/-- Trait declaration: [core_models::ops::function::Fn]
    Source: 'core-models/src/core/ops.rs', lines 168:4-171:5
    Visibility: public -/
structure ops.function.Fn (Self : Type) (Args : Type)
  (Self_Clause0_Clause0_Output : Type) where
  FnMutInst : ops.function.FnMut Self Args Self_Clause0_Clause0_Output
  call : Self → Args → Result Self_Clause0_Clause0_Output
-/

/-- Trait declaration: [core_models::ops::try_trait::FromResidual]
    Source: 'core-models/src/core/ops.rs', lines 247:4-249:5 -/
structure ops.try_trait.FromResidual (Self : Type) (R : Type) where
  from_residual : R → Result Self

/-- Trait declaration: [core_models::ops::try_trait::Try]
    Source: 'core-models/src/core/ops.rs', lines 252:4-257:5 -/
structure ops.try_trait.Try (Self : Type) (Self_Output : Type) (Self_Residual :
  Type) where
  from_output : Self_Output → Result Self
  branch : Self → Result (ops.control_flow.ControlFlow Self_Residual
    Self_Output)

/-- Trait declaration: [core_models::ops::deref::Deref]
    Source: 'core-models/src/core/ops.rs', lines 262:4-266:5
    Visibility: public -/
structure ops.deref.Deref (Self : Type) (Self_Target : Type) where
  deref : Self → Result Self_Target

/-- Trait declaration: [core_models::ops::drop::Drop]
    Source: 'core-models/src/core/ops.rs', lines 278:4-280:5 -/
structure ops.drop.Drop (Self : Type) where
  drop : Self → Result Self

/-- [core_models::ops::range::RangeInclusive]
    Source: 'core-models/src/core/ops.rs', lines 300:4-303:5
    Visibility: public -/
structure ops.range.RangeInclusive (T : Type) where
  start : T
  «end» : T

/-- [core_models::slice::Slice]
    Source: 'core-models/src/core/slice.rs', lines 5:0-5:19 -/
@[reducible]
def slice.Slice (T : Type) := T

/-- [core_models::slice::iter::Chunks]
    Source: 'core-models/src/core/slice.rs', lines 12:4-15:5
    Visibility: public -/
structure slice.iter.Chunks (T : Type) where
  cs : Std.Usize
  elements : Slice T

/-- [core_models::slice::iter::ChunksExact]
    Source: 'core-models/src/core/slice.rs', lines 22:4-25:5
    Visibility: public -/
structure slice.iter.ChunksExact (T : Type) where
  cs : Std.Usize
  elements : Slice T

/-- [core_models::slice::iter::Iter]
    Source: 'core-models/src/core/slice.rs', lines 32:4-32:43
    Visibility: public -/
@[reducible]
def slice.iter.Iter (T : Type) := rust_primitives.sequence.Seq T

/-- [core_models::slice::iter::Windows]
    Source: 'core-models/src/core/slice.rs', lines 80:4-83:5
    Visibility: public -/
structure slice.iter.Windows (T : Type) where
  size : Std.Usize
  elements : Slice T

/-- [core_models::str::error::Utf8Error]
    Source: 'core-models/src/core/str.rs', lines 10:4-10:25
    Visibility: public -/
@[reducible]
def str.error.Utf8Error := Unit

/-- [core_models::str::iter::Split]
    Source: 'core-models/src/core/str.rs', lines 14:4-14:23 -/
@[reducible]
def str.iter.Split (T : Type) := T

/-- Trait declaration: [core_models::str::traits::FromStr]
    Source: 'core-models/src/core/str.rs', lines 18:4-21:5 -/
structure str.traits.FromStr (Self : Type) (Self_Err : Type) where
  from_str : Str → Result (result.Result Self Self_Err)

end core_models
